microsoft/Qcodes

- docs_requirements.txt
- requirements.txt
- test_requirements.txt
I think this went out of sync since dependabot does not handle env markers correctly
> make importlib_metadata requirements consistent across requirementes files

- qcodes/configuration/qcodesrc_schema.json
- setup.py
This is in preparation for eventually being able to use draft 2019-09 (aka. draft-08) which adds support for deprecating properties https://stackoverflow.com/questions/48461197/how-do-i-mark-a-property-in-json-schema-as-deprecated as soon as that is supported by the python jsonschema package. https://github.com/Julian/jsonschema/issues/613
> Use the latest json schema draft supported by python jsonschema validator

- .github/actions/setup-ubuntu-latest-xvfb/action.yml
- .github/workflows/docs.yaml
- .github/workflows/pytest-non-local.yaml
- .github/workflows/pytest.yaml
- .github/workflows/verify-science-deps-installable.yaml
* Correct an incorrect name of a task
* Remove dependencies previously required to build 3.9 packages from source
* Explicitly install xvfb (its installed by default but that looks likely to change in ubuntu 20.04 which will soon be the new latest image)
* Stop using now deprecated flag to enable 2020 resolver. The resolver is now on by default
> GitHub actions cleanup

- qcodes/logger/logger.py
opencensus seems to sometime have invalid certificates that will trigger warnings from `urllib3.connections` 
@astafan8 The default Filter only supports filtering by name. Here I have just opted for the simple solution. We could also add a subclass that allows us to filter by message. What do you think?
> filter urllib3.connection related warnings from console logger

- qcodes/utils/helpers.py
fix issues such as  `Argument 2 to deep_update has incompatible type 
Dict[str, StepOutputDict]; expected Mapping[Hashable, Any]`
by making the arguments typevars with the correct bound
> Slightly more flexible type check

- qcodes/tests/drivers/test_tektronix_AWG70000A.py
This line is intermittently covered by tests as is causing coverage failures such as https://codecov.io/gh/QCoDeS/Qcodes/pull/2584/changes in non related CI runs. This adds a test that explicitly covers this line. The line is intermittently covered since the data generated in the forged sequence is sampled from a normal distribution that may or may not clip the output.
> awg70000 add test of warning when waveform is clipped

- qcodes/dataset/data_export.py
- qcodes/dataset/descriptions/detect_shapes.py
- qcodes/dataset/sqlite/database.py
- qcodes/dataset/sqlite/queries.py
- qcodes/instrument_drivers/AlazarTech/ATS9360.py
- qcodes/instrument_drivers/AlazarTech/ATS9373.py
- qcodes/instrument_drivers/AlazarTech/ATS_acquisition_controllers.py
- qcodes/instrument_drivers/agilent/E8267C.py
- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
- qcodes/instrument_drivers/tektronix/AWG5014.py
- qcodes/instrument_drivers/tektronix/Keithley_2450.py
- qcodes/instrument_drivers/tektronix/keithley_7510.py
- qcodes/math_utils/field_vector.py
- qcodes/tests/dataset/conftest.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/helpers/test_json_encoder.py
- qcodes/tests/validators/test_complex.py
- qcodes/utils/helpers.py
- qcodes/utils/types.py
- qcodes/utils/validators.py
- test_requirements.txt
Checked locally with numpy 1.20 rc1
* Some numpy types are now generic so give them an explicit Any. Use types in strings to support older numpy versions
* np.int, np.float and np.complex which are aliases for the build in python types are deprecated. 
* Use the dtype constructor explicitly when needed
* Various fixes for interaction between the python types and numpy types
EDIT:
while this does run with older versions of numpy it does not type check. Not sure what the best solution is.
We can add ignores to those lines or just wait until numpy 1.20 is officially released. Or we could disable the non explicit generics for now.
> Add support for type checking with upcomming Numpy 1.20 release. 

- docs/conf.py
This is no longer needed according to the install instructions https://sphinx-rtd-theme.readthedocs.io/en/stable/
> Remove non needed html theme path

- docs_requirements.txt
- requirements.txt
- science_requirements.txt
- test_requirements.txt
Seems like dependabot does not do this correctly when using an environmental marker.
> bump importlib-metadata to 3.4.0

- qcodes/instrument_drivers/Keysight/keysight_e4980a.py
- Set signal mode at driver initialization
- Set snapshot_exclude attribute of volt and curr level params
@jenshnielsen
> Set signal mode and snapshot_exclude attributes of volt and curr level params when needed (Keysight E4980A)

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
- qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
- qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/commandhandler.py
- qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/server.py
- qcodes/instrument_drivers/rigol/DS4000.py
- test_requirements.txt
Replaces https://github.com/QCoDeS/Qcodes/pull/2645
* Mypy now requires that you use the same name for a named tuple variable and its name. Apparently that has 
always been recommended. 
* Handle that `msvcrt` module is now correctly detected on Windows but missing on other platforms
> Add support for Mypy 0.800

- qcodes/tests/dataset/__init__.py
- qcodes/tests/dataset/test_dataset_basic.py
To silence warning about it being imported before rewrite.
As recommended here https://docs.pytest.org/en/stable/writing_plugins.html#assertion-rewriting
> move pytest assert rewrite to before import of the relevant module

- .github/workflows/pytest-min-versions.yaml
- .github/workflows/pytest.yaml
- azure-pipelines.yml
- qcodes/.coveragerc
- setup.cfg
* Move coverage config to setup.cfg
* Simplify logic by running tests from toplevel dir
* Hopefully silence warning about module qcodes not being covered
> Coverage cleanup

- MANIFEST.in
Avoids manually having to include it in Conda build from pypi
> add license to sdist

- qcodes/utils/dataset/doNd.py
Not sure how this happened but get was being called twice on the same parameter
> remove typo in paramcaller

- .github/workflows/upload_to_pypi.yaml
> ensure wheel setuptools and pip is up to date before building packages

- .github/workflows/docs.yaml
Currently the docs renders the version number as 0+unknown. This is a quick fix to get the right version number back. 
It may be worth investigating using a tree or a blob less clone to speed this up. https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
@astafan8
> fetch full git history when building docs so tag can be included in docs build info

- .github/static/environment_forge_full.yml
- environment.yml
- setup.cfg
- test_requirements.txt
Since we are no longer using this to generate test fixtures the dependency can go
> remove dependency on gitpython

- qcodes/tests/test_station.py
otheriwse there will be a warning that a read meassge from instrument does not contain termination character.
> Use correct visa address for lakeshore pyvisa sim in station test

- qcodes/dataset/data_set.py
Used to first load the data to verify shape and then reload in _load_to_xarray_dataarray_dict
Fix this by refactoring _load_to_xarray_dataarray_dict to take a loaded dataset
> avoid loading data twice in to_xarray_dataset

- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_cache.py
- qcodes/tests/dataset/test_dataset_basic.py
Tests to be done via https://github.com/QCoDeS/Qcodes/pull/2771
> Add pandas and xarray methods to dataset.cache matching the dataset

- docs_requirements.txt
as my fix has made it into an upstream release we can revert back to that
> use new version of sphinx json schema with string escape

- setup.cfg
as can be seen from running testAggregator
the following code will fail
```
import numpy as np
npoints=1
z_start_stop=[-9223372036854775809, -9223372036854775809]
np.linspace(z_start_stop[0], z_start_stop[1], npoints).reshape(npoints, 1)
```
with
```
AttributeError: 'float' object has no attribute 'ndim'
```
for numpy 1.16.0, 1.16.1 and 1.16.2. This has been fixed in 1.16.3
An example of this can be seen in https://github.com/QCoDeS/Qcodes/pull/2849
This is intermittent since the values in z_start_stop are generated by hypothesis and this only happens for sufficiently large numbers probably due to an overflow or something similar
> Fix intermittend (hypothesis) failure by bumping min supported numpy version to 1.16.3

- qcodes/dataset/data_set.py
- qcodes/tests/dataset/test_dataset_basic.py
Fixes #2847.
- support exporting dataset with multiindex with non-unique entries to xarray
- add station snapshot to xarray attributes
- update docstring
@jenshnielsen
> support export to xarray for data with non unique indices

- qcodes/instrument_drivers/american_magnetics/AMI430.py
This adds the ramping_state to the Exception message to get to know which state the magnet is, when it is not ramping.
> Added ramping_state to set_field Exception

- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_cache.py
- qcodes/dataset/exporters/__init__.py
- qcodes/dataset/exporters/export_to_pandas.py
- qcodes/dataset/exporters/export_to_pandas_xarray.py
- qcodes/dataset/exporters/export_to_xarray.py
This will eventually enable us to reuse these in other dataset implementations. 
This could also have been achieved by making a base class but since the coupling to the dataset is not very strong
and they are also used from the cache I think it makes more sense to move them into their own module
> Move private dataset export functions to their own module

- qcodes/instrument/base.py
- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/tests/drivers/test_ami430.py
Useful when defining AMI430_3D in station YAML config file (**after** defining the individual AMI430 axes)
as requested by @jdwatson.
also: Make error message explicit when instrument with name does not exist.
> AMI430 3D driver: allow instantiating from names of existing AMI430 instances, next to from AMI430 instances only

- qcodes/tests/legacy/test_data.py
- qcodes/tests/legacy/test_generic_formatter.py
- qcodes/tests/legacy/test_loop.py
Otherwise there is a risk of race condition when multiple datasets are created at the same time by tests executing in parallel. 
An example of that can be seen here https://github.com/QCoDeS/Qcodes/pull/2894/checks?check_run_id=2401386164
> Name legacy test datasets

- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/tests/drivers/test_ami430.py
> AMI430 3D driver: add docstring, extra test for initializing from AMI430 by name

- .github/actions/prepare-cache-pip/action.yml
This will hopefully avoid a permission error when pip tries to replace pip on windows
> use python -m pip to upgrade pip in github actions

- docs_requirements.txt
- requirements.txt
- test_requirements.txt
Perhaps this will enable dependabot to parse them correctly?
Since it has no problem with the pywin32 related env markers
> try changing formatting for env markers differently

- .pre-commit-config.yaml
- pyproject.toml
This adds darker https://github.com/akaihola/darker as a pre commit hook. Darker basically works as a incremental version of black that only reformat the code that has been changed in a given pr
> Add darker to precommit hooks

- qcodes/tests/test_deprecate.py
- qcodes/tests/test_visa.py
* use pytests warning fixture 
* Port some tests to pytest style
This should eventually help us get to a point where warnings can become errors for testing
> tests: cleanup warning handling 

- qcodes/utils/dataset/doNd.py
doNd functions will currently modify post_delay values on swept parameters that will propagate outside of the doNd function. This will modify sweep rates of the parameter if post_delay/step values are used to limit sweep rates in qcodes.
Ideally this would also be added to the interrupt handle context but didnt include it there as I am not too familiar with python contexts.
Also moved dataset definition up to before the context starts as a keyboard interrupt throws an error due to dataset not being defined.
PR has been tested on offline computer but not actual measurements for now.
> Make doNd reset original post_delay values + fix to keyboard interrupt

- qcodes/utils/helpers.py
There was an empty line missing before the bullets in the docstring, so the formatting was wrong.
> Fix NumpyJSONEncoder docstring

- qcodes/instrument/base.py
- qcodes/instrument/delegate/delegate_channel_instrument.py
- qcodes/instrument/delegate/delegate_instrument.py
- qcodes/instrument/delegate/grouped_parameter.py
- qcodes/instrument/delegate/instrument_group.py
- qcodes/instrument/group_parameter.py
- qcodes/instrument/parameter.py
This has the benefit of clarifying that the mappings are imitable and allows the functions to take other mappings with  the dict interface ordereddict etc
> replace the use of Dict with Mapping for input args within instrument module

- qcodes/dataset/data_set_cache.py
That way the imaginary part will also be nan useful when plotting especially
> use nan + i*nan as placeholder for complex numbers

- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_sqlite_base.py
This will help decouple the sqlite backend from the dataset implementation
> Allow time stamps to be passed to set_run_timestamp and mark_run_completed. 

- setup.cfg
This will add a handy changelog link to the sidebar of https://pypi.org/project/qcodes/ (under project links)
> Add changelog link to docs

- qcodes/dataset/data_set_protocol.py
Since they seem to logically belong together with the completed property. Note that I have left out the started property since that is really just Either running or completed.
> add pristine and running properties to protocol

- .pre-commit-config.yaml
- qcodes/configuration/qcodesrc_schema.json
The current format is invalid. It should either be just a single item type or like this pr suggest a list of item types which defines exactly the type of each element
Since cutoff_percentile always has two numbers this seems like the correct format.
See https://json-schema.org/understanding-json-schema/reference/array.html for some details 
This also adds a pre-commit hook that check that json is valid which would have caught this. I had to exclude asv.conf.json since it contains comments which is not valid json
> Fix invalid array syntax in json schema 

- qcodes/configuration/qcodesrc.json
- qcodes/configuration/qcodesrc_schema.json
- qcodes/utils/dataset/doNd.py
Create a setting for use_threads in the config to be used in `process_params_meas` for doNd functions. Allows control of the setting in the config file rather than a required input at runtime. 
Additionally makes the measure function public for external use of threaded parameter calls. This could be split out to a separate PR but included here in case there are no objections/concerns with this change.
Bug fix: moved dataset reference up in new dond to handle keyboardinterrupts similar to other functions in file.
> Use threaded setting from config in dond functions, and make process_params_meas public

- docs/conf.py
Looks like docs build fails in https://github.com/QCoDeS/Qcodes/pull/3105 this seems to fix it
> fix link to pyvisa intersphinx

- qcodes/dataset/descriptions/rundescriber.py
@jenshnielsen what do you think, should this be happening or not?
for latest version of the class, this seems very fair, but i'm not sure what should happen for the case where RunDescriber from V2 data (without shapes, because there were no notion of shapes back then) is compared with RunDescriber from V3 data (that has the shapes or has None as the shape) and the interdependencies part is equal. or am i overthinking this too much?
> Compare shapes in RunDescriber equality method

- qcodes/dataset/exporters/export_to_xarray.py
- qcodes/tests/dataset/test_dataset_export.py
> Improve xarray metadata export

- qcodes/instrument_drivers/AlazarTech/ATS.py
Fixes #3117
- in mode 'TS' the buffer size = reccord size / nr of buffers
> Alazar ATS drivers: Fix buffer size for mode='TS' and buffers_per_acquisition > 1

- .github/workflows/docs.yaml
This will hopefully go some of the way in fixing https://github.com/QCoDeS/Qcodes/issues/3109 since the
gh-pages branch is fairly heavy and grows with every commit
> Do not preserve gh pages branch history

- .github/static/environment_forge_full.yml
- qcodes/dataset/data_set.py
- qcodes/tests/dataset/test_dataset_export.py
- requirements.txt
- setup.cfg
> Export complex numbers to netcdf

- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_protocol.py
- qcodes/dataset/exporters/export_info.py
- qcodes/dataset/sqlite/db_upgrades/__init__.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_dataset_export.py
- qcodes/tests/dataset/test_export_info.py
This will eventually make it easier to export and reimport datasets
> add export info metadata to dataset

- qcodes/tests/test_threading.py
Trying to debug a failed test on the master branch. This will hopefully make sure that all threads have started before any of them end and therefor does end up with a reused id.
> Give threads time to start in tests

- qcodes/dataset/data_export.py
- qcodes/dataset/sqlite/queries.py
- qcodes/utils/numpy_utils.py
Extract method from where this was already fixed and reuse it.
Perhaps we should think of another location for this method.
> Fix numpy deprecation for ragged arrays

- qcodes/dataset/measurements.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/measurement/test_measurement_context_manager.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_dataset_basic.py
- Decouple measurement name from dataset results table name to allow special characters in the measurement name
- Update failing tests
> Decouple measurement name from dataset results table name 

- qcodes/dataset/data_set.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_dataset_basic.py
otherwise there will be a confusing error message from sqlite
> Don't allow metadata tags that are not valid python identifiers

- qcodes/instrument/base.py
- qcodes/tests/test_abstract_instrument.py
It turns out that this approach has unintended side effects when multiple inheritance is used. This will effectively generate init methods for any class that does not have an init method but inherits from something that has an init method. In multiple inheritance scenarios this may change the order in which init methods are called. See https://gist.github.com/jenshnielsen/c3f6457f3510d638722c58e1e163ddee for an example of how this can happen.
> Revert checking of abstract parameters in post init

- qcodes/tests/legacy/test_loop.py
This test is a source of random failures and not really well designed since it relies on a time resolution that may not be there
> remove bare wait test

- qcodes/tests/delegate/test_device.py
* Test needs an experiment to add data to otherwise it cannot run standalone.
* Test was setting v on a device with non zero post delay and a small step size making it much slower than needed
> Fix delegate test

- qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
Bug fix taken from #3191
Not sure why this instrument uses channel instead of instrument but perhaps the intent was to avoid a snapshot so set snapshot_value to false as it makes no sense to snapshot this value.
Also sneaked in a few cleanups. 
Use public root instrument attr and make sure that trace_ready is always set
> forward instrument to parameter baseclass in rto driver

- docs_requirements.txt
- requirements.txt
- test_requirements.txt
Now that ipykernel supports importlib meatadata we can upgrade this again. dependabot does not do this automatically due to the env marker (a bug in dependabot)
> Bump importlib metadata

- .github/static/environment_forge_full.yml
- docs/conf.py
- docs/examples/writing_drivers/Creating-Instrument-Drivers.ipynb
- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/agilent/Agilent_34400A.py
- qcodes/instrument_drivers/weinschel/Weinschel_8320.py
- qcodes/sphinx_extensions/parse_parameter_attr.py
- qcodes/tests/sphinx_extension/test_parse_parameter_attr.py
- setup.cfg
- test_requirements.txt
This adds a Sphinx extension that documents parameter attributes on instrument classes. There are documented using a proxy object that contains a `__repr__` that contains the code to construct the parameter class. 
As an example this is how the Wenishel looks on this class 
In the longer term this can be improved to more nicely format the repr using `autodoc-process-docstring` or `autodoc-process-signature`
This pr replaces #3188
> Document Parameter attributes

- qcodes/logger/logger.py
- qcodes/tests/test_installation_info.py
- qcodes/tests/test_logger.py
- qcodes/utils/installation_info.py
Towards reproducible experiments! A small step is that we log the versions of installed packages in the environment where QCoDeS runs. 
- Add function to get a list (well, dict) of all installed packages and their versions
- Log this information upon import
I did a quick and dirty comparison of import times before and after these changes, and there is no significant overhead.
@QCoDeS/core
> Log all installed packages

- docs/examples/DataSet/Using_doNd_functions_in_comparison_to_Measurement_context_manager_for_performing_measurements.ipynb
- qcodes/utils/dataset/doNd.py
This PR enables dond to take inner actions. The actions are passed in the Sweep instances.
The logic is as follows: actions for a sweep parameter will be called when the set value of that parameter is changed. I didn't put comments in the code, but I think it would be nice to add a few comments.
I couldn't find a a good way to unit test actions, so it is still missing if we want to have the test.
@jenshnielsen
> Add post sweep actions to doND sweeps

- pyproject.toml
- setup.py
Versioneer is not pep518 compliant so to make this work I have added the local dir to path as suggested as a work around here https://snarky.ca/what-the-heck-is-pyproject-toml/
> make qcodes install mostly pep517/518 compliant

- setup.cfg
Since we are using pkg_resources which is part of setuptools at runtime.
This was previously effectively an implicit dependency. This was not an issue since almost all python envs comes with a version of setuptools
> Explicitly depend on setuptools

- qcodes/logger/logger.py
- qcodes/tests/test_logger.py
This prevents issues where the broken pipe character (used for delimiting messages) cannot be written to the log file if the file has a different encoding. Reading the documentation it is not clear to which extend this may also be an issue for the stream handler used for the console logging. This writes to stderr. According to https://docs.python.org/3/library/sys.html#sys.stderr the encoding of stderr should be defined by local on oses other than windows so this probably works without issues on windows (but there are some limitations as noted in the stderr documentation) On most other platforms I would expect local encoding to be utf8 anyway.
> Logging: explicitly set encoding for file handler

- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
otherwise when in the SMU is used in current sourcing mode and the voltage hits the voltage compliance limit, the measurement_status property of the current/voltage parameters did not reflect that.
> Keithley 2600: support returning both voltage and current compliance limit errors

- qcodes/instrument_drivers/stanford_research/SR86x.py
otherwise a deprecation warning comes up.
> Make SR86xBufferReadout parameter take kwargs and pass them to base class

- CONTRIBUTING.rst
clarify that email is mostly for signing up to slack not support in it self
> Update contributing document

- test_requirements.txt
I have manually removed types-enum34 since that is a backport package that we do not use. it seems like mypy cannot tell this apart from the stdlib module of the same name
@astafan8
> add type packages discovered by mypy --install-types

- qcodes/dataset/database_extract_runs.py
refactor _extract_single_dataset_into_db
into _add_run_to_runs_table and _populate_results_table
so that one can be reused in the future without the other
Lifted from #3094
> refactor _extract_single_dataset_into_db

- qcodes/dataset/data_set.py
the self.add_metadata call just above takes care to make this query atomic so add_snapshot should too
> make call to add_meta_data atomic

- qcodes/dataset/database_extract_runs.py
- qcodes/dataset/sqlite/queries.py
Avoids importing query_helpers into extract runs and seems to be more clean and may enable reuse of these methods ultimately
> move queries to the right module

- qcodes/tests/helpers/test_json_encoder.py
- qcodes/utils/helpers.py
When importing uncertainties. Since this is a deprecation warning in a third party package there is not much we can do to fix it
> silence deprecation warning from uncertainties

- qcodes/utils/dataset/doNd.py
This is a small PR to relocate two nested functions from dond to the global scope.
The functions are still private functions, we can discuss if some of the doNd private functions can be in the public API, for example _parse_dond_arguments, then we can think about a better name.
@jenshnielsen 
@astafan8
> Extract nested helper functions from dond's to module level

- qcodes/tests/delegate/test_delegate_instrument.py
This for instance fails here https://github.com/QCoDeS/Qcodes/runs/4073011897?check_suite_focus=true
The field is calculated from ramp time and rate so the value may not be exact
> Fix flaky test

- docs/changes/newsfragments/3555.improved_driver
- qcodes/instrument_drivers/Keysight/Keysight_N5173B.py
- qcodes/instrument_drivers/Keysight/Keysight_N5183B.py
- qcodes/instrument_drivers/Keysight/N51x1.py
This PR improves the drivers for Keysight N51x1 and N51x3 signal generators by:
- Adding explicit support for N5173B
- Fixing the power range of N5183B
- Fixing the frequency range options for N51x1
@jenshnielsen
> Fix power and frequency ranges of Keysight N51x1 and N51x3 signal generators

- docs/changes/newsfragments/3586.improved
- docs/examples/DataSet/Exporting-data-to-other-file-formats.ipynb
- qcodes/configuration/qcodesrc.json
- qcodes/configuration/qcodesrc_schema.json
- qcodes/dataset/data_set_protocol.py
- qcodes/dataset/export_config.py
- qcodes/tests/dataset/measurement/test_measurement_context_manager.py
- qcodes/tests/dataset/test_dataset_export.py
- qcodes/tests/dataset/test_dataset_in_memory.py
This makes it possible to configure the exported name. So far it is possible to include captured_run_id and guid. 
This is technically an api break since it now uses captured_run_id and not run_id but I do think that is for the better.
> Make export configurable

- bors.toml
Require python 3.10 for bors to merge to staging and master
> Bors: require python 3.10

- qcodes/tests/delegate/test_delegate_instrument.py
the field may not ramp exactly to 0
since this is implemented as fp math
see an example of this here https://github.com/QCoDeS/Qcodes/runs/4260183190?check_suite_focus=true
> Fix random test failure

- docs/changes/newsfragments/3484.Underthehood
This fragment should have been included in 0.30.0 but was not since it was incorrectly formatted (the file name should be underthehood not Underthehood)
> remove incorrect news fragment

- qcodes/instrument/sims/AMI430.yaml
- qcodes/tests/drivers/test_ami430.py
This test was broken in several ways.
1) The test compares the field rate limit in T/S against the current
rate limits in A/s. This means that ix.ramp_rate(target_ramp_rate)
did not actually raise the error tested for.
2) The test only asserted that any Exception was raised not checking
for a specific type of exception.
3) excinfo.value.args inside the context manager raises a AttributeError
which is then in turn caught by the pytest.raises context manager.
This makes the test pass incorrectly.
4) This in turn causes pytest to leave the tests in an inconsistent state
which results in other tests passing asserts that they should not. 
This means the tests pass if running after this one but don't if they are executed before this test (or independently).
For now I have commented out the …
> Fix ami430 tests

- docs/changes/newsfragments/3662.improved
- qcodes/instrument/parameter.py
- qcodes/tests/parameter/test_delegate_parameter.py
- qcodes/tests/parameter/test_parameter_scale_offset.py
> Allow getting an uninitialized DelegateParameter with offset or scale

- docs/changes/newsfragments/3682.improved
- qcodes/dataset/data_set_cache.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_dataset_export.py
This makes it so that get parameter data for an empty dataset returns a dict with empty arrays rather than an empty dict. This makes other things more consistent down the line and makes fixes such as the ones in https://github.com/QCoDeS/Qcodes/pull/3679 not needed 
Todo:
> Let get_parameter_data return empty datasets in a more consistent way

- qcodes/monitor/monitor.py
- qcodes/tests/test_monitor.py
test_parameter was not correctly closing the connection before closing the event loop. Using a async context manager makes it simpler to ensure this is the case
> Cleanup websockets test errors

- qcodes/tests/test_abstract_instrument.py
and give all drivers in this module unique names which will help debug issues with incorrectly closed instruments.
> Close driver in abstract instrument test

- qcodes/dataset/sqlite/query_helpers.py
- qcodes/instrument_drivers/AlazarTech/ATS9360.py
- qcodes/instrument_drivers/AlazarTech/ATS9373.py
- qcodes/instrument_drivers/Keysight/keysight_e4980a.py
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
- qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
- qcodes/instrument_drivers/rigol/DS4000.py
- qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
- qcodes/tests/test_installation_info.py
- qcodes/utils/installation_info.py
- setup.cfg
All of distutils is deprecated in python 3.10 and the recommended alternative for LooseVersion is packaging.version.parse
This removes all use of distutils outside versioneer
> Drop use of Distutils LooseVersion

- .github/workflows/pytest-non-local.yaml
- pyproject.toml
- setup.cfg
This was added in pytest 6.0 which is anyway the oldest version that we support. 
Pytest recommends against using setup.cfg for config now https://docs.pytest.org/en/6.2.x/customize.html#setup-cfg
> move pytest related config to pyproject.toml

- qcodes/logger/logger.py
This saves around 0.7 s when doing a fresh import without activating logging
> Only import Azure opencensus when needed

- docs/changes/newsfragments/3696.improved
- qcodes/instrument/base.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_instrument.py
This commit fixes the issue of an instrument instance being registered in the instance dictionary even if the instrument creation failed. This will allow users to retry instrument connection when the first attempt fails without having to restart the interpreter or modify private variables in the Instrument class.
It certainly resolves a source of frustration when trying to debug failing instrument connections 😆 
This partially closes #1882, and should also allow us to be smarter about logging successful connections or cleaning up gracefully on failure.
@jenshnielsen @astafan8 What do you think?
> Only record instrument instances when successfully created

- qcodes/configuration/config.py
- qcodes/utils/installation_info.py
Avoid an import time dependency on pkg_resources. This takes 0.3-4 s to import
To do this 
* Make import lazy in two instances where it is only used for logging
* Dont use this to generate absolute paths to config files. This does in principle mean that these are no longer zip safe. However QCoDeS is currently not marked as zip safe and running from a zip file is not really something we want to support
> Speedup avoid loading pkg_resources at startup

- docs/changes/newsfragments/3764.breaking
- qcodes/__init__.py
- qcodes/configuration/qcodesrc.json
- qcodes/configuration/qcodesrc_schema.json
- qcodes/utils/magic.py
This changes the configuration such that the legacy IPython magic becomes off by default. Avoiding to unconditionally import IPython on startup. This saves ~ 0.3/4 sec or so
> Speedup import: disable ipython magic by default

- docs/changes/newsfragments/3762.breaking
- qcodes/data/hdf5_format.py
- qcodes/tests/test_installation_info.py
- qcodes/version.py
this is already statically avaliable as ``qcodes.__version__``
This shaves of 0.3 sec or so from the start up time. 
It may be worthwile deprecating the version module. However https://github.com/QCoDeS/Qcodes/pull/3731 fixes this anyway in a way that ensures version is only calculated once per session
> Avoid calculating version twice on startup

- qcodes/plots/pyqtgraph.py
It seems like the changes in #https://github.com/QCoDeS/Qcodes/pull/3733 made TestQtPlot.test_simple_plot fail for me locally with an error about AttributeError: 'AxisItem' object has no attribute '_qcodes_label' 
This seems to be related to the pyqt remote object used here as the AxisItem clearly has this item assigned. As a work around we use getattr here which does seem to solve the issue
> work around issue in pyqt plot with remote process

- qcodes/__init__.py
- qcodes/dataset/measurements.py
Websockets is a hard dependency at the moment so this does not make a lot of sense to wrap the import logic like this.
This is done on top of https://github.com/QCoDeS/Qcodes/pull/3781 which should be merged first
The reordering of imports done by darker here triggered another circular import which is fixed by correcting the measurement module to not use station from the top level
> Remove websockets import wrapper

- qcodes/interactive_widget.py
Fixes 
<ipython-input-1-71c4ab7913f1>:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
from IPython.core.display import display
> fix IPython deprecation warning

- qcodes/utils/dataset/doNd.py
This PR adds a break_condition argument to dond, do1d and do2d to interrupt a measurement based on the return value.
It uses the existing code for handling KeyboardInterrupts, but modifies it to raise a new BreakConditionInterrupt instead.
While I did not include it in this PR to keep it simple, maybe its beneficial to pass some more data from the current iteration to the break condition function?
> add break conditions to dond, do1d, do2d

- docs/changes/newsfragments/3718.new
- docs/examples/writing_drivers/abstract_instruments.ipynb
- qcodes/instrument/base.py
- qcodes/tests/test_abstract_instrument.py
This is a start of re implementing the abstract parameter interface reverted in https://github.com/QCoDeS/Qcodes/pull/3197 and https://github.com/QCoDeS/Qcodes/pull/3217 based on top of https://github.com/QCoDeS/Qcodes/pull/3696
Compared to the solution based on init subclass this works a bit differently. The metaclass in use is only implemented for the Instrument class but not for the InstrumentChannel. Changing this would require metaclass inheritance which is a bad idea. 
This meas that it is not an error to create an InstrumentChannel with abstract parameters but it is an error to attach such a thing to an instrument at instrument creation time. I don't think this is a big issue since that is how most instruments are created. 
Still need to update docs again and verify if there are …
> Reimplement abstract instrument

- docs_requirements.txt
- qcodes/dataset/sqlite/queries.py
- qcodes/instrument/mockers/simulated_ats_api.py
- qcodes/instrument_drivers/AlazarTech/ATS.py
- qcodes/instrument_drivers/AlazarTech/ATS_acquisition_controllers.py
- qcodes/instrument_drivers/Galil/dmc_41x3.py
- qcodes/instrument_drivers/HP/HP8753D.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
- qcodes/instrument_drivers/stanford_research/SR830.py
- qcodes/instrument_drivers/stanford_research/SR86x.py
- qcodes/math_utils/field_vector.py
- qcodes/utils/validators.py
- requirements.txt
- test_requirements.txt
Numpy 1.22 adds a fair amount of types so there are a few tweaks to get it correct. 
The most important ones are probably the changes around fromstring / frombuffer. 
* fromstring is effectively deprecated in the format that we use it and it is recommended to use frombuffer as done here
* using from buffer with a ctypes array seems to be not recommended so we use the numpy ctypes api here. This results in a simplifications since we no longer have to manually map between ctypes and numpy types
> Support numpy 1.22

- MANIFEST.in
- pyproject.toml
With setuptools 56 the licence is automatically included and there is no need to specify it in the manifest. 
This means that we have one less file to clutter the main source dir
> Remove manifest

- qcodes/monitor/monitor.py
- qcodes/tests/test_monitor.py
Add function argument for monitor creation to allow grouping of parameters according to channels rather than instrument. Specifically, group according to `parameter.instrument` instead of `parameter.root_insturment`. Default behavior is the current behavior with sorting by `root_instrument`.
Code has been tested on qcodes version 0.30.0 on one system.
Potentially it could be nice to be able to pass in a manual sorting by allowing direct input of the parameter dictionary rather than going through `_get_metadata`.
> Channel ordered monitor

- docs/changes/newsfragments/3835.improved
- qcodes/instrument/channel.py
- qcodes/tests/test_channels.py
And register this as such so that 
isinstance and issubclass works as expected
Partially taken from #3834
> Let ChannelList implement the collections.abc.Sequence interface

- docs/changes/newsfragments/3644.Underthehood
The format is nnnn.underthehood not nnnn.Underthehood so this was never included (and deleted). Remove now to avoid this being imitated
> remove wrongly named news fragment

- docs/changes/newsfragments/3834.improved
- qcodes/instrument/base.py
> Register InstrumentModules separately from ChannelLists

- docs/changes/newsfragments/3833.improved_driver
- docs/examples/driver_examples/Qcodes example with AMI430.ipynb
- qcodes/instrument_drivers/american_magnetics/AMI430_visa.py
- qcodes/tests/drivers/test_ami430.py
- qcodes/tests/drivers/test_ami430_visa.py
Taken from https://github.com/QCoDeS/Qcodes/pull/3833 without experiments to make connections more robust
> Add VISA version of AMI430 driver

- qcodes/tests/delegate/conftest.py
- qcodes/tests/drivers/test_stahl.py
This is discovered using pytest-randomly https://github.com/pytest-dev/pytest-randomly
which randomly reorders the tests. 
* station fixture was being modified in tests so its not safe to reuse at session scope
* Stahl drivers tests were sensitive to what was in the logger before test started executing. Rewrite using caplog from pytest
There failures can be systematically reproduced using 
```
pytest.exe --randomly-seed=3202135262
```
Note that there are more ordering issues not yet fixed here
> Fix some tests that depends on shared state

- qcodes/instrument/base.py
- qcodes/tests/test_abstract_instrument.py
Now that we can split modules and channellists this can be done
in a cleaner way. This also means that we can now check channels that are not added individually but in a list
> Cleanup check for is abstract in instrument.

- docs/changes/newsfragments/3851.new
- pyproject.toml
- qcodes/__init__.py
- qcodes/instrument/__init__.py
- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/instrument_drivers/AimTTi/AimTTi_PL601P_channels.py
- qcodes/instrument_drivers/Harvard/Decadac.py
- qcodes/instrument_drivers/Keysight/Infiniium.py
- qcodes/instrument_drivers/Keysight/N52xx.py
- qcodes/instrument_drivers/Lakeshore/Model_325.py
- qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
- qcodes/instrument_drivers/Minicircuits/Base_SPDT.py
- qcodes/instrument_drivers/Minicircuits/RC_SP4T.py
- qcodes/instrument_drivers/Minicircuits/RC_SPDT.py
- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/rigol/DG1062.py
- qcodes/instrument_drivers/rigol/DS1074Z.py
- qcodes/instrument_drivers/rigol/DS4000.py
- qcodes/instrument_drivers/rigol/private/DP8xx.py
- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
- qcodes/instrument_drivers/rohde_schwarz/private/HMC804x.py
- qcodes/instrument_drivers/stanford_research/SR86x.py
- qcodes/instrument_drivers/tektronix/AWG70000A.py
- qcodes/instrument_drivers/tektronix/TPS2012.py
- qcodes/station.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_channels.py
This creates a cleaner interface where the ChannelTuple does not contain modifying methods (which would just raise)
* ChannelList now implementes the full MutableSequece ABC
* All drivers that used lock have been updated to convert the channellist to a channeltuple
* Instrument and station has been updated to allow channeltuples. 
* Code coverage of ChannelList/Tuple has been improved to almost 100 % 
One could significantly cleanup the code by removing the whole lock functionality but that will need to be left till 
the things has been deprecated for a while. 
Question? Should we get rid of the whole `_channels` being a tuple or a list. That would significantly simplify the typing and remove the need for casting in the list implementation.
Possible future improvements
> Split ChannelList into a ChannelTuple and a ChannelList

- environment.yml
- qcodes/utils/installation_info.py
- requirements.txt
- setup.cfg
The feature we are using from there is liberally one line in a call to pkg_resources. We might as well do that directly
> Drop dependency on requirements parser

- qcodes/instrument_drivers/Keysight/N52xx.py
Since run_sweep prints a warning message on a keyboard interrupt by catching the exception - it makes it difficult to interrupt a sweep on using the PNA. Let's raise the exception after printing the warning.
> Stop N52xx intercepting keyboard interrupts

- qcodes/station.py
To clarify that using both arguments is an error
NoReturn is used for a function that unconditionally raises an error.
See https://mypy.readthedocs.io/en/stable/more_types.html#the-noreturn-type
> Improve typing of load_all_instruments

- docs/changes/newsfragments/3884.improved
- qcodes/instrument/parameter.py
This warning in it current form is hard to track down to anything meaningful so
Change it to 
* Include full name with instrument, 
* set stacklevel to see where its called from
> better warning when excluding parameter from snapshot

- docs/changes/newsfragments/3890.improved
- pyproject.toml
Otherwise as far as pip is concerned `0.32.0+nnxxxx` is equal to `0.32.0` i.e.
`pip install qcodes==0.32.0` will do nothing if you have a dev version of qcodes installed (in the form `0.32.0+nnxx`)
This is as expected if you read pip 440 carefully https://www.python.org/dev/peps/pep-0440/
> Add devN marker to signal a dev release

- bors.toml
This only lightly documented setting controls how long bors waits for ci to go green and then merge to staging/
This can easily take more than the default 30 min since some of our jobs are ~ 30 min without wait time
Note I don't think this will solve all our issues like this since bors is supposed to comment if this happens. 
but i did see a comment like that in https://github.com/QCoDeS/Qcodes/pull/3893 
Looks like there is a deeper issue in https://github.com/bors-ng/bors-ng/issues/1434
> Wait 2 hours for github jobs to finish

- qcodes/tests/dataset/test_sqlite_base.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/conftest.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1500.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1500_module.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1511b_smu.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1517a_smu.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1520a_cmu.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_sampling_measurement.py
Passing None to pytest.warns is deprecated. Followed https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests to update the code
Also sneaked in some cleanup of imports and fixtures in the b1500 tests since I was there
> fix pytest7 deprecation warnings

- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/tests/test_instrument.py
Instead always let name return the full name
This has no user facing changes since name was always equivalent to full_name for instrument sub classes but avoids some internal logic.
> avoid generating full name twice

- docs/changes/newsfragments/3911.improved
- qcodes/instrument/channel.py
- qcodes/tests/test_channels.py
Which is different from the repr of the ChannelList
> add repr for ChannelTuple

- .github/static/environment_forge_full.yml
For some reason solving the env on 3.7 has become very slow (~20 min on ubuntu)
We have other tests covering 3.7 lets upgrade this.
> run conda jobs against python 3.9

- qcodes/instrument/base.py
- qcodes/tests/test_instrument.py
Contains the changes from https://github.com/QCoDeS/Qcodes/pull/3912 which should be merged before this.
instrument.close stripes the attributes of an instrument but not of the modules within the instrument. It is unclear to me if it really makes sense to strip the atters but if we do that we should also do it here
> Strip attributes from channels when closing an instrument.

- qcodes/configuration/config.py
- qcodes/data/data_array.py
- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/utils/validators.py
This silences a warning from pyright/pycharm about there not being a module abc in collections.
I suspect the automatic import of acb only works because of the deprecated import of abc members into the main module so its probably better this way
> explicitly import collections.abc

- docs/changes/newsfragments/3929.improved
- qcodes/instrument/parameter.py
Inspired by the typing hacks needed in https://github.com/QCoDeS/Qcodes/pull/3916 to make unit a property 
This eliminates the need for those hacks See https://github.com/QCoDeS/Qcodes/pull/3916/files#diff-5478d126afe3357045220d8be1ef9c6859ee8427f28984ff8d169b9ab1b75902R126
> Promote unit of parameter to be a property

- docs/changes/newsfragments/3932.improved
- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_in_memory.py
- qcodes/dataset/data_set_protocol.py
- qcodes/dataset/exporters/export_to_xarray.py
- qcodes/tests/dataset/measurement/test_measurement_context_manager.py
- qcodes/tests/dataset/test_dataset_export.py
- qcodes/tests/dataset/test_dataset_in_memory.py
Otherwise, adding metadata after the export happened will not propagate it to the exported netcdf file.
todo:
> Add metadata to netcdf file where the DataSet is exported to

- qcodes/instrument/parameter.py
This is the same issue as showed up in #3916 Here we work around it in the same way by explicitly annotating the member attribute
> _SetParamContext: explicitly annotate Parameter to work around mypy issue

- qcodes/configuration/config.py
* Remove ignore by allowing any object to be passed to contains (and return False if not a str)
* Make explicit in type annotation that keys must be str
* Take a generic mapping as input to constructor
> Config: Cleanup typing of dotdict

- docs/changes/newsfragments/3944.improved
- qcodes/interactive_widget.py
Total time is end - start not the other way around
Also rewrite code to avoid type ignores
> Correct calculation of time in interactive widget

- docs/changes/newsfragments/3956.improved
- qcodes/dataset/dataset_helpers.py
- qcodes/dataset/descriptions/dependencies.py
- qcodes/dataset/descriptions/rundescriber.py
- qcodes/dataset/descriptions/versioning/converters.py
- qcodes/dataset/descriptions/versioning/serialization.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_sqlite_base.py
Resolves https://github.com/QCoDeS/Qcodes/issues/3953 by ensuring that the full run description is copied to the new dataset
> Directly use rundescriber to create run when exporting datasets to a new database file

- docs/changes/newsfragments/3945.improved
- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_cache.py
- qcodes/dataset/data_set_in_memory.py
- qcodes/dataset/descriptions/dependencies.py
- qcodes/tests/dataset/conftest.py
- qcodes/tests/dataset/test_data_set_cache.py
- qcodes/tests/dataset/test_datasaver.py
- qcodes/tests/dataset/test_dataset_in_memory.py
- qcodes/tests/dataset/test_string_data.py
The wrong from of meshgrid was being used
> Fix loading of >1 dim netcdf datasets from netcdf to DataSetinmem

- qcodes/__init__.py
I think it would make sense to add the initialised_database_at-context manager to the public api. A typical usage pattern would be to use it with `load_by_guid` or similar.
> Add initialised_database_at to public API

- qcodes/dataset/sqlite/database.py
Will catch a mis spelled journal mode as a typo
> Typing: Make journal modes a literal type in dataset module

- .github/workflows/darker.yaml
I 1.4.1 the recommended way to run darker jobs has changed.
See https://github.com/akaihola/darker#github-actions-integration
> Update darker job to match latest version

- docs/changes/newsfragments/3969.improved_driver
- qcodes/instrument_drivers/zurich_instruments/hdawg.py
- qcodes/instrument_drivers/zurich_instruments/hf2.py
- qcodes/instrument_drivers/zurich_instruments/mfli.py
- qcodes/instrument_drivers/zurich_instruments/pqsc.py
- qcodes/instrument_drivers/zurich_instruments/shfqa.py
- qcodes/instrument_drivers/zurich_instruments/shfsg.py
- qcodes/instrument_drivers/zurich_instruments/uhfli.py
- qcodes/instrument_drivers/zurich_instruments/uhfqa.py
- setup.cfg
Update driver stubs for Zurich Instruments devices.
With the latest release of LabOne 22.02 the QCoDeS driver for our instruments changed quite a bit. Not only did we add 
support for all of our devices but also we changed the import statements. 
This PR maps the existing stubs to the correct imports and adds new files for the newly supported device.
> Update: zhinst instrument driver stubs

- setup.cfg
See 
* https://nvd.nist.gov/vuln/detail/CVE-2020-25658
* https://nvd.nist.gov/vuln/detail/CVE-2022-21699
* https://nvd.nist.gov/vuln/detail/CVE-2021-20270
> Pin transitive dependencies to versions that fix known security issues

- qcodes/instrument/base.py
- qcodes/instrument_drivers/Keysight/private/error_handling.py
As recommended by mypy. This avoids having to subclass from abcmeta when defining the metaclass of the instrument and 
overall makes the inheritance a bit simpler. See https://mypy.readthedocs.io/en/latest/more_types.html#mixin-classes
> remove the need for InstrumentABC by using a protocol

- pyproject.toml
This mens that a prerelease will correctly be identifed as > current relase
> use next_version for prerelease version number

- qcodes/instrument/base.py
To allow subclasses (using multiple inheritance)
to inherit from ABC
This is a partial revert of https://github.com/QCoDeS/Qcodes/pull/4039
> Let instrument metaclass inherit from ABCMeta

- qcodes/instrument/parameter.py
The `context` variable is only constructed in `Parameter.validate` if required.
> Improve performance of qcodes parameter validation

- setup.cfg
There are sufficient api changes in the upcomming 8 series that our tests are failing so pin to 7 series until we can add support
> pin ipywidgets to 7

- docs/changes/newsfragments/4122.improved_driver
- qcodes/instrument_drivers/tektronix/Keithley_6500.py
Added single quotes around mode value in set_cmd of mode parameter of Keithley_6500
Closes #4121
> Set Keithley 6500 mode correctly

- docs/changes/newsfragments/4139.improved_driver
- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
Hi all,
I simply added a sweep class to return the magnitude in db when doing a magnitude/phase sweep.
Hopes everything is good.
> Add db/phase sweep for rohde_schwarz ZNB driver

- docs/changes/newsfragments/4161.new
- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/parameter/conftest.py
- qcodes/tests/parameter/test_parameter_cache.py
This is handy when some change e.g. touching the frontpanel invalidates our knowlege about the instrument.
> Add method to invalidate cache of an Instrument

- docs/examples/Station.ipynb
to fix header level rendering
before:
after:
So the lesson is that one should never skip a level :) in this case, there was first level 1 header and then level 3 header for "useful imports", and apparently sphinx or nbconverter just assumes that level 2 headers won't be there anymore or thinks that they are the same as level 3 headers.
> Station example notebook: fix header levels

- docs/changes/newsfragments/4219.breaking.1
- docs/changes/newsfragments/4219.breaking.2
- qcodes/instrument/visa.py
- qcodes/tests/test_visa.py
* Slightly better docs and logging
* Correct the backend name to reflect current pyvisa
* Remove deprecated fallback for visa address with library included
* Let pyvisa figure out the default termination char
> Small improvements to visa backend

- docs/examples/driver_examples/Qcodes example with Rigol DS1074Z.ipynb
the visa module has been deprecated from pyvisa
> rigol notebook remove unused and deprecated import

- docs/changes/newsfragments/4257.breaking
- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/conftest.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_instrument.py
Allow submodules that are not them self valid identifiers provided that full name is.
> Let instrument names be less restrictive.

- qcodes/__init__.py
- qcodes/dataset/__init__.py
Update toplevel qcodes.x api to import from the correct individual modules.
Also fixes a mixup where `get_guids_by_run_spec` was added to qcodes.x but not qcodes.dataset.x
> Update qcodes.x api

- docs/conf.py
This will become the default in sphinx 5 and makes the docs more readable
E.g. changes 
to
> use short parameter annotation in docs

- qcodes/instrument/instrument_base.py
- qcodes/instrument/ip_to_visa.py
- qcodes/instrument/visa.py
- qcodes/logger/__init__.py
- qcodes/tests/drivers/test_lakeshore.py
This is used outside the logging module so should be public IMHO @Dominik-Vogel
> Api: add get_instrument_logger to public api

- qcodes/instrument/channel.py
- qcodes/instrument/instrument_base.py
This improves the sphinx rendering of the type signature.
Compare:
To:
> Avoid passing classes as default args

- qcodes/__init__.py
- qcodes/instrument_drivers/Keysight/keysight_e4980a.py
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
- qcodes/logger/logger.py
- qcodes/tests/test_installation_info.py
- qcodes/utils/__init__.py
- qcodes/utils/installation_info.py
Stop using get_qcodes_version and deprecate. It does not seem to add any value over using qcodes.__version__ which is a convention
> Add public api for installation info functions

- docs/examples/legacy/Datasaving examples.ipynb
We don't recommend running the tests like this and it creates a dependency on the tests (and pytest) in the docs
> remove execution of test from docs of data.dataformat

- qcodes/validators/validators.py
> correctly render multitype examples

- docs/changes/newsfragments/4360.improved
- qcodes/dataset/plotting.py
For tick marks with long labels sometimes the axis label gets pushed out of the canvas window and not visible in the saved png files. Add argument with tight fitting of bbox for matplotlib savefig to ensure full figure with all labels is included in the saved png.
> do_nd: save plot with 'tight' bbox

- .github/workflows/pytest-min-versions.yaml
- docs/changes/newsfragments/4382.breaking
- pyproject.toml
- setup.cfg
- setup.py
This moves the supported and non experimental
parts of setuptools config to pyproject.toml
These are the parts standardized by pep621 and
supported in setuptools >=65 
These are the supported parts of https://github.com/QCoDeS/Qcodes/pull/4049
> migrate setuptools pep621 config to pyproject.toml

- pyproject.toml
- requirements.txt
I manually verified that
* both sdist and bdist have correct version both in metadata and _version.py
* pip install gives the correct version (including ``qcodes.__verison__`` from editable)
> Upgrade versioningit to 2.0.0

- docs/conf.py
- qcodes/instrument/instrument.py
- qcodes/instrument/instrument_meta.py
- qcodes/instrument/visa.py
Fixes #4370 by not using custom metaclass when documenting to work around sphinx documenting __call__ rather than __init__
This feels like a bit of a hack so not sure if its ok. Inspired by https://stackoverflow.com/questions/20843737/check-if-sphinx-doc-called-the-script
> Document correct signature for Instruments

- docs/changes/newsfragments/4426.breaking
- qcodes/instrument/visa.py
This has been deprecated since 0.19 (oktober 2020) so it seems fair to remove it now
> remove deprecated check_error from visa instrument

- docs/changes/newsfragments/4427.breaking
- qcodes/instrument/instrument.py
This was part of the long gone instrument server and is completely unused within qcodes.
> Remove unused shared_kwargs attribute from instrument

- docs/changes/newsfragments/4292.improved
- qcodes/instrument/channel.py
- qcodes/instrument/instrument_base.py
- qcodes/parameters/function.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_channels.py
This IMHO eliminates the only important feature Functions has over a regular method on a InstrumentModule/Channel
TODO
> ChannelTuple: add ability to call regular callable

- docs/api/instrument/index.rst
- docs_requirements.txt
This currently requires a branch of sphinx to fix documenting inherited attributes. That branch is open as https://github.com/sphinx-doc/sphinx/pull/10691
To install sphinx 5.x we need the master branch of autodocsumm. That does not otherwise carry any fixes
This is done as a branch that carries my changes directly on top of 5.0.x since 5.1.0 broke the build. See https://github.com/sphinx-doc/sphinx/issues/10701
@astafan8 What do you think is it acceptable to build with a patched version of sphinx until that is merged.
This will also enable us to activate autodocsumm for https://github.com/QCoDeS/Qcodes/pull/4371 which will make that way more readable
> Docs: Enable autosummary for instrument module

- pyproject.toml
- requirements.txt
Autodocsumm 0.2.9 is out with support for sphinx 5 so switch to a release
> Switch autodocsumm back to release

- docs/Makefile
- docs/drivers_api/srs.rst
- docs/make.bat
- qcodes/instrument_drivers/stanford_research/SG384.py
- qcodes/instrument_drivers/stanford_research/SR560.py
- qcodes/instrument_drivers/stanford_research/SR830.py
- qcodes/instrument_drivers/stanford_research/SR860.py
- qcodes/instrument_drivers/stanford_research/SR865.py
- qcodes/instrument_drivers/stanford_research/SR865A.py
- qcodes/instrument_drivers/stanford_research/SR86x.py
- qcodes/instrument_drivers/stanford_research/__init__.py
I have left the drivers in the format SR860. I guess one could argue that they should be named SRSSR860 since SR is part of the model number but that feels too much.
> Update Stanford drivers to conform to docs standard

- qcodes/tests/dataset/test_database_creation_and_upgrading.py
Partial fix for https://github.com/QCoDeS/qcodes_generate_test_db/issues/8
Also:
* There are no fixtures for the current version so don't try to run test_getting_db_version on that version.
* Unify the skip logic for consistent output message
> Add better skip messages to tests if missing fixutures

- CONTRIBUTING.rst
- docs/start/index.rst
- qcodes/tests/common.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_fix_functions.py
Improve `pytest.skip` messages when db-file are missing to point out at submodule qcodes_db_fixtures.
Explicitly recommend cloning with submodules, include the `git clone` command and options in the documentation.
Fix related error 404 in CONTRIBUTING.rst.
See QCoDeS/qcodes_generate_test_db#8
> Improve instructions for db-file fixtures

- docs/changes/newsfragments/4472.improved_driver
- qcodes/instrument_drivers/Keysight/N51x1.py
> Added the parameter `auto_freq_ref` to N51x1 Keysight signal generators class

- qcodes/tests/dataset/test_dataset_basic.py
This test has started failing on windows ci build. In the long term we should make the guid more robust against low resolution clocks. This is just to unblock ci
> xfail failing tests on windows

- qcodes/dataset/__init__.py
- qcodes/dataset/sqlite/connection.py
- qcodes/dataset/sqlite/database.py
Many functions of the public API, like the `load_by_*`s,  are using a `ConnectionPlus` to avoid creating a new connection on every call. This PR exposes `connect` in order to provide the user a way of creating such a connection. `ConnectionPlus` is exposed to enable typing.
> Add `connect` and `ConnectionPlus` to public API

- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_dataset_loading.py
These tests also fail due to lack of time resolution
> xfail 2 more tests on windows

- .github/dependabot.yml
- .github/workflows/pytest-min-versions.yaml
- qcodes/tests/drivers/test_tektronix_dpo7200xx.py
There are times where a lot of jobs are opened on the same day
There is no benefit for not opening all of them at once
These have the same random failures as the regular tests
> CI / test improvements 

- .github/workflows/docs.yaml
- .pre-commit-config.yaml
- docs/conf.py
- qcodes/calibrations/keithley.py
- qcodes/dataset/data_set_cache.py
- qcodes/dataset/data_set_in_memory.py
- qcodes/dataset/data_set_protocol.py
- qcodes/dataset/exporters/export_to_csv.py
- qcodes/dataset/exporters/export_to_pandas.py
- qcodes/dataset/exporters/export_to_xarray.py
- qcodes/instrument/delegate/delegate_channel_instrument.py
- qcodes/instrument/delegate/delegate_instrument.py
- qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
- qcodes/instrument_drivers/Minicircuits/Base_SPDT.py
- qcodes/interactive_widget.py
- qcodes/parameters/cache.py
- qcodes/parameters/multi_channel_instrument_parameter.py
This enables the new style type annotations in pep851 and pep604. Since these things are not supported for python <3.10
this only works in files that uses `from __future__ import annotations` I imagine that if we do this we would gradually add that to all files after this is merged. The actual transforms are done by pyupgrade by removing `--keep-runtime-typing` from the options
One drawback is that the new syntax still cannot be used in Type aliases. 
Another issue is that this does not build docs without warnings for python <3.10 
I have therefor changed the build to upload from 3.10 build and allow sphinx warnings for python < 3.10
See [pep 585](https://peps.python.org/pep-0585/) and [pep 604](https://peps.python.org/pep-0604/) for more context.
> Enable pep 585 and pep 604 using from __future__ import annotations

- docs/changes/newsfragments/4460.new
- qcodes/instrument/instrument.py
- qcodes/instrument/instrument_base.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_channels.py
- qcodes/tests/test_instrument.py
Add a label to InstrumentBase that can store a nicely-formatted instrument name. The implementation is similar to the label in Parameter. Previously discussed [here](https://github.com/QCoDeS/Qcodes/discussions/4411).
docstrings, an example notebook or restructured text files.
> Give InstrumentBase a label that can be nicely formatted

- qcodes/instrument_drivers/agilent/Agilent_34400A.py
This restores a name of a deprecated non conformant class as it was in 0.34.1
> Fix typo in Agilent alias

- pyproject.toml
The old one is deprecated and this is less verbose and nicer.
Note that the format documented in the readme is actually wrong https://github.com/twisted/towncrier/pull/425
> Use Towncriers new config format

- .pre-commit-config.yaml
With the landing of #4248 we no longer have case conflicts in the QCoDeS codebase. Lets ensure we don't get them again
> add precommit hook to ensure no case conflicts

- .github/workflows/pytest.yaml
- bors.toml
This can be reverted once a mypy version with https://github.com/python/mypy/pull/13500 is out
> Restrict python patch version in ci

- docs/changes/newsfragments/4602.improved
- qcodes/validators/validators.py
I noticed that sometimes the settings of validators are accessed for use, but at the moment they are private attrbiutes, so this PR makes them public properties. For those validators that has their settings as public attributes, setters for the properties are added.
> Expose validator settings as properties

- qcodes/utils/json_utils.py
Latest version of uncertainties no longer triggers a warning on import
> remove warnings filter

- docs/changes/newsfragments/4621.improved
- qcodes/tests/helpers/test_json_encoder.py
- qcodes/utils/json_utils.py
Fixes #4620 
Note that this does not in any way attempt to support bytes that cannot be converted to a string but at least these will not trigger an infinite recursion.
> Avoid recursion for bytes / bytearrays in json encoder

- qcodes/utils/dataset/doNd.py
Restore `do0d` to `qcodes.utils.dataset.doNd`. It seems to have been accidentally removed in commit 934aa4575b7bc341bd04ca5fca7b3fa622b46b64
@jenshnielsen
> Fix Breaking: Restore do0d

- benchmarking/README.rst
- benchmarking/asv.conf.json
- docs/changes/newsfragments/4446.improved
- qcodes/dataset/data_set.py
- qcodes/dataset/experiment_container.py
- qcodes/dataset/sqlite/database.py
- qcodes/dataset/sqlite/db_upgrades/upgrade_2_to_3.py
- qcodes/dataset/sqlite/queries.py
- qcodes/dataset/sqlite/query_helpers.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_sqlite_base.py
- qcodes/tests/dataset/test_sqlite_connection.py
Saving and loading data from the SQL database rely on `_adapt_xxx` and `_convert_xxx` methods. However, currently they are using many `numpy` functions (`np.isnan`, `np.isinf`, `np.save`, `np.load`) that are slow when dealing with arrays containing single values. This PR makes the following changes that significantly improve data loading and saving performance:
- For `float`: Replace `numpy` functions by `math` functions, use `math.isinfinite` instead of combining `isnan` and `isinf`;
- For `complex`: Do not save complex single values as `numpy` arrays of one value. It saves both time and space if we avoid reading and writing the relatively large `numpy` header. This changes the representation of the data in the database, but it's fully backwards compatible (and tested);
- For `array`: …
> Significant performance improvements to AddResult / GetParameter

- qcodes/instrument_drivers/AlazarTech/ATS.py
With the upcoming mypy 0.980 mypy will enforce that a generic Typevar output is matched by a generic input such that it can infer the type of the output. This reveals that `acquire` would return an unbound typevar. This fixes that by matching it to the type of the ```acquisition_controller ```
Note that the code is typed to accept acquisition_controller being None but that will actually unconditionally raise. 
```python
if acquisition_controller is None:
raise RuntimeError("Cannot call acquire without an "
"acquisition_controller")
```
Also add `from __future__ import annotations` to make types cleaner
> Alazar generic output must be input

- pyproject.toml
- qcodes/configuration/config.py
Use types-jsonschema and update the code to validate. 
In the process refactor the validation method to avoid nesting logic and make it more clear
> Config: simplify JSON validation and make it typecheck

- docs/changes/newsfragments/4658.breaking
- qcodes/dataset/sqlite/queries.py
- qcodes/dataset/sqlite/query_helpers.py
- qcodes/tests/dataset/test_metadata.py
- qcodes/tests/dataset/test_sqlite_base.py
``DataSet.get_metadata`` method for retrieving a metadata value for a
given tag is now case-sensitive with respect to the tag.
For example, if metadata was added with ``dataset.add_metadata('something', 1)``,
it can only be retrieved by using its exact casing of the tag,
``dataset.get_metadata('something')``, and not e.g.
``dataset.get_metadata('SomeThinG')``. In the previous versions of QCoDeS,
any casing of the tag in ``DataSet.get_metadata`` would work and return the
value stored under that tag. Note that this change brings consistency
with how getting metadata via the ``dataset.metadata`` works:
``dataset.metadata['something']`` does return the value, and
``dataset.metadata['SomeThinG']`` does not.
Also adds extra testing for ``one()`` helper function and clarifies docstrings of a few …
> DataSet.get_metadata to return value only if the casing of the tag matches the column name in the database

- qcodes/tests/test_instrument.py
This fixes a warning from pytest that these cannot be collected as tests
> Mark two clases with test in the name as not tests

- docs/changes/newsfragments/4674.breaking
- qcodes/__init__.py
> Remove deprecated import of loop etc at the top level of qcodes

- qcodes/utils/helpers.py
The internal function compare_dictionaries has moved to the testing module but we import it here for backwards compatibility.
That triggers an unwanted import of pytest so to fix this we opt for coping it deprecated here rather than importing it.
> Avoid utils depending on pytest

- qcodes/monitor/monitor.py
This makes use of `asyncio.run` and async context managers to manage the state of the context manager. 
We use a future + call_soon_threasafe to signal that the loop should exit as recommended by the websockets docs
Note that this also fixes a deprecation warning from asyncio
May close https://github.com/QCoDeS/Qcodes/issues/4712
> Monitor simplify eventloop handling

- qcodes/instrument/instrument_base.py
This PR changes an except statement in `InstrumentBase.snapshot_base` from `except:` to `except Exception`.
This allows other errors, e.g. a `KeyboardInterrupt`, to halt the snapshot.
Without this modification, a snapshot can take a long time if there is a communication error.
> Add Exception to except

- .github/dependabot.yml
This should prevent dependabot from issuing upgrades for x~=1.1.0 to 1.1.1 when 1.1.1 is released since that is already matched by ~=
See https://github.blog/changelog/2022-10-24-reduce-dependabot-version-updates-in-your-python-projects-with-the-increase-if-necessary-strategy/
> Dependabot python use increase-if-necessary

- qcodes/tests/common.py
- qcodes/tests/conftest.py
- qcodes/tests/dataset/measurement/test_measurement_context_manager.py
- qcodes/tests/dataset/test_guids.py
- qcodes/tests/dataset/test_subscribing.py
- qcodes/tests/test_config.py
- qcodes/tests/test_plot_utils.py
- qcodes/tests/test_station.py
Extracted from https://github.com/QCoDeS/Qcodes/pull/4763
* Using fixtures avoids the patterns of tests that are completely within a context manger improving readability
* Since the context mangers cooperate, we avoid the logic of having to patch config objects within the test
> Replace config context managers with pytest fixtures

- .github/workflows/pytest.yaml
- pyproject.toml
Adding action to record test duration comparison on serial run unit tests. Let's see if this adds any insight to our test flow.
> adding test duration comparison in CI

- docs/changes/newsfragments/4763.breaking
- docs/examples/DataSet/Extracting-runs-from-one-DB-file-to-another.ipynb
- qcodes/configuration/qcodesrc.json
- qcodes/configuration/qcodesrc_schema.json
- qcodes/dataset/data_set.py
- qcodes/dataset/guids.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_dataset_loading.py
- qcodes/tests/dataset/test_guids.py
The current time resolution, especially on windows, is insufficient to ensure that we always avoid collisions in guids. Since sample names are available within the dataset metadata and the sample part of the guid is cumbersome to use I suggest that we replace that with a random string.
The broad plan is 
* Make guid type configurable
* Warn if the sample name guid is set to something other than the default value. 
* Update tests that have problems with guid collisions to use the new guid type
* Eventually change the default to the new type
For now we ami to completely remove the support of setting a sample_id. If actual use shows up we are open to allow this to be enabled as an explicit option
> Add random sample to guid

- docs/changes/newsfragments/4779.improved
- qcodes/calibrations/keithley.py
When running the calibrate_keithley_smu_v method to calibrate a Keithley SMU, as documented [here](https://qcodes.github.io/Qcodes/examples/driver_examples/Qcodes%20example%20with%20Keithley%202600.html#Recalibration), the calibration gives the following error:
ERROR CODE: 5029
SMU A: Cannot save without changing cal adjustment date
SMU B: Cannot save without changing cal adjustment date
This PR addresses this error by changing the calibration adjustment date before saving the new calibration.
> Keithley calibration: adjust calibration date before saving new calibration

- pyproject.toml
- qcodes/data/hdf5_format.py
- qcodes/dataset/descriptions/versioning/serialization.py
- qcodes/station.py
- requirements.txt
This PR uses the [lazy_loader](https://github.com/scientific-python/lazy_loader) package to make the qcodes import time lower. The lazy_loader package has been adapoted by several scientific python packages, for details see https://scientific-python.org/specs/spec-0001/
The h5py and ruamal components have been selected because they take time in the import and are only used in components that not all users will use (e.g. the legacy dataset and the Monitor). The PR is intended to be fully backwards compatible.
More gains can be made with non-backwards compatible changes. For example in the main qcodes `__init__.py` the number of direct imports which could be reduced.
Also see #4543
@jenshnielsen
> Make h5py and ruamel lazy loading

- .github/workflows/pytest.yaml
PR to only upload to blueracer test duration action if running with os linux and python 3.11.
This was needed because blue racer currently doesn't have support for matrix builds.
> run blueracer action with linux on 3.11 only

- docs/changes/newsfragments/4801.improved
- qcodes/dataset/dond/do_nd_utils.py
- qcodes/tests/dataset/dond/test_do1d.py
> log.warning instead of raise exception if measurement has been interrupted.

- docs/changes/newsfragments/4802.improved
- qcodes/dataset/data_set_in_memory.py
- qcodes/tests/dataset/test_dataset_export.py
data_array.coords is not guaranteed to return
in the same order as its written. However, this is guaranteed for data_array.dims so use that to order coords when loading
TODO
> Load coordinates from netcdf in the correct order.

- qcodes/instrument_drivers/Keithley/_Keithley_2600.py
- qcodes/instrument_drivers/Keysight/keysightb1500/constants.py
- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
Python 3.11 added StrEnum to the std library so lets use that when available rather than rolling out our own
> Use StrEnum from std lib when avilable

- qcodes/plots/pyqtgraph.py
- qcodes/tests/common.py
- qcodes/tests/conftest.py
- qcodes/tests/dataset/conftest.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_dataset_in_memory_bacis.py
- qcodes/tests/instrument_mocks.py
Mypy 0.990 has started triggering notes on annotations in functions that are not type checked. This is essentially because these type annotations have no effect since, they are not checked. This fixes that by adding partial type annotations to those functions.
> Add just enough types to avoid mypy notes

- docs/changes/newsfragments/4818.improved
- qcodes/dataset/database_extract_runs.py
- qcodes/dataset/legacy_import.py
- qcodes/dataset/sqlite/database.py
- qcodes/tests/dataset/measurement/test_load_legacy_data.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_database_extract_runs.py
> Consistently allow pathlib.Path in all relevant public dataset methods

- .github/workflows/pytest.yaml
- pyproject.toml
It seems like blueracer changed their integration but the documentation is unclear. This has never really worked correctly for us. We can come back to this when/if blueracer is more mature.
To get a little bit more feedback I have added ``--durations=20`` to print the run time of the slowest 20 tests to std out when running in CI
> remove non-working blueracer, replace with manual print of durations

- requirements.txt
The new version causes a huge number of warnings. Not caught due to #4830 
Warnings are due to https://github.com/ipython/ipython/issues/13845
> Revert ipython to 8.6.0

- docs/examples/DataSet/Exporting-data-to-other-file-formats.ipynb
- pyproject.toml
- qcodes/dataset/data_set_protocol.py
- qcodes/extensions/__init__.py
- qcodes/extensions/_log_export_info.py
- qcodes/extensions/_print_export_info.py
- qcodes/tests/dataset/test_dataset_export.py
This is useful for kicking of postprocessing, backup, upload etc.
> Add dataset export entry point

- docs/changes/newsfragments/4876.improved
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_sqlite_base.py
Otherwise one may very easily trigger an unintentional change of the time stamp
> make it a no op to mark a run completed twice

- docs/changes/newsfragments/4886.improved
- qcodes/plots/pyqtgraph.py
Update the scale transformation in qcodes.plots.pyqtgraph to use the modern interface. I think the old interface was deprecated a very long time ago (see commnent in https://github.com/pyqtgraph/pyqtgraph/pull/1533).
Fixes #4756. @rsokolewicz Could you check this PR with the quantify plotting?
@jenshnielsen
> Update scale transformation in pyqtgraph plot

- docs/changes/newsfragments/4887.underthehood
- qcodes/instrument/instrument_base.py
- qcodes/parameters/parameter_base.py
The parameter validator spends a large amount of time in generating the validation context (only used if the validation fails), instead of the actual parameter validation. Profiling results with snakeviz:
This PR reduces the overhead by using a `cached_propery` decorator. This is possible since the instrument and parameter name are immutable in qcodes.
@jenshnielsen
> Reduce overhead in parameter validation

- qcodes/tests/dataset/dond/test_do0d.py
- qcodes/tests/dataset/test_dataset_export.py
One test was missing the fixture causing it to write to the default db
The other tests were incorrectly using mark on fixtures which is not supported. This was partially fixed
by applying the experiment fixture again to the test but that would result in the wrong order
Discovered as part of https://github.com/QCoDeS/Qcodes/pull/4899 and https://github.com/QCoDeS/Qcodes/pull/4906
> Fix use of experiment fixture

- qcodes/calibrations/keithley.py
- qcodes/instrument_drivers/Keithley/__init__.py
I wanted to update the types in the calibration module to use the official api but noticed that there were no good way of saying give me any of the supported 26xx drivers. This fixes that by adding a Union type
> Driver Keithley add union type

- docs/changes/newsfragments/4922.breaking
- qcodes/tests/driver_test_case.py
- qcodes/tests/drivers/test_Agilent_E8257D.py
- qcodes/tests/drivers/test_weinchel.py
This has no good reason to live in the test module. This is a breaking change but I don't expect this to be used in a way where this is important enough for a shim to be added
> Move DriverTestCase to the test module

- docs/changes/newsfragments/4923.breaking
- qcodes/instrument_drivers/__init__.py
- qcodes/instrument_drivers/devices.py
- qcodes/parameters/voltage_divider.py
This is not an instrument but a Parameter so it makes more sense for it to live there. 
Since DelegateParamerer does the same more general and better deprecate this one
> Move VoltageDivider into parameters and deprecate

- docs/Makefile
- docs/drivers_api/Oxford.rst
- docs/make.bat
- qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
- qcodes/instrument_drivers/oxford/__init__.py
- qcodes/instrument_drivers/oxford/triton.py
> Update oxford drivers to conform with standard

- docs/changes/newsfragments/4623.improved_driver
- docs/examples/driver_examples/Qcodes example with Minicircuits Switch boxes (USB-XSPDT).ipynb
- pyproject.toml
- qcodes/instrument_drivers/Minicircuits/USB_SPDT.py
There are two different dll files depending on the version of .NET on the system:
.Net 4.5 and above: mcl_RF_Switch_Controller_NET45.dll
Earlier .Net versions: mcl_RF_Switch_Controller64.dll
Had a quick look but couldn't find an easy way to check the .NET version from python although would expect it should be possible. The most rudimentary solution is to just try importing both and renaming the package in python as shown suggested here but would be nice with a cleaner implementation.
> Minicircuits 4SPDT driver fix for .NET 4.5+ versions

- .github/workflows/pytest.yaml
- CONTRIBUTING.rst
- docs/changes/newsfragments/4938.improved
- pyproject.toml
- qcodes/instrument/instrument.py
- qcodes/instrument_drivers/Keithley/_Keithley_2600.py
Fix one last remaining type checking issue too
* Also fix a use of deprecated MeasurementStatus 
* Remove deleted modules from type exclusions
> Check pyright in CI

- qcodes/instrument/sims/Keithley_2600.yaml
Adding extra address to pyvisa sim yaml on the Keysight 2600 SMU to fix bug when instantiating two simulated SMU's.
> Allow two simulated keysight 2600 smu's

- qcodes/instrument/sims/Keysight_34465A.yaml
Similar to https://github.com/QCoDeS/Qcodes/pull/4949 its nice to have the option to use 2 dmms in a mock experiment
> Add support for 2 simulated keysight dmms

- docs/examples/DataSet/Exporting-data-to-other-file-formats.ipynb
- qcodes/dataset/data_set_protocol.py
- qcodes/dataset/measurements.py
- qcodes/extensions/_log_export_info.py
- qcodes/tests/dataset/test_dataset_export.py
This makes it future proof and should happen now since the functionality has not been in qcodes before this release to avoid it being an api break
By using **kwargs we ensure this is forwards compatible.
> Extend export entry point event to take kwargs

- .pre-commit-config.yaml
This fixes an installation issue due to a new
version of poetry triggered by precommit
> Upgrade isort to 5.12.0

- .github/workflows/pytest.yaml
- qcodes/logger/logger.py
Pyright 1.1.292 finds a new error in the log filter probably due to improvements to typeshed 
The filter should and does return a bool but the annotated return type was wrong
> Pyright 1.1.292

- pyproject.toml
- qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/commandhandler.py
- qcodes/utils/qt_helpers.py
Also correct error message in dynacool driver to recommend the correct package and fix a type issue in qt_helper
> Add pywin32 types

- qcodes/instrument_drivers/Minicircuits/USBHIDMixin.py
- qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/commandhandler.py
- qcodes/utils/qt_helpers.py
These modules may not be installed (and cannot on non windows pcs)
Done on top of https://github.com/QCoDeS/Qcodes/pull/4978 which should be merged first
> Silence pyright warnings

- requirements.txt
Now that rtd theme has support for sphinx 6 / docutils 0.18 this should be supported
> upgrade sphinx to 6.1.3 with patch

- qcodes/tests/test_station.py
See warning here https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#use-fixtures-in-classes-and-modules-with-usefixtures
> Fix: usefixtures cannot be used in a new fixture

- docs/changes/newsfragments/5007.improved_driver
- qcodes/tests/test_installation_info.py
- qcodes/utils/installation_info.py
Packaging 22 dropped LegacyVersion. We mostly handled this by converting any letters in the version str to a number using ord. However, the version str for keysight also contained extra info and looks something like this "A.02.17-02.40-02.17-00.52-04-01"
From packaging 22 and upwards this is an error. We fix that by splitting on `-` and only using the first part. The converter is only used for Keysight versions so adding it there seems safe. 
This was not caught in the Keysight 34xxx driver tests since the test only runs for a simulated instrument that has the dig option marked installed and this path in the code is only taken if the dig option is not present in the options str. 
Extend the tests for the converter to 
* include this type of version field
* Ensure what comes out of the …
> Fix #5007 Handle version str with extra info 

- docs/changes/newsfragments/5013.improved_driver
- qcodes/instrument/sims/Keithley_3706A.yaml
- qcodes/instrument_drivers/Keithley/Keithley_3706A.py
- qcodes/tests/drivers/test_keithley_3706A.py
When instantiating an object of the class `Keithley3706A`, the interlock status is checked for each card that is installed in the unit. When querying the unit for the interlock status (for a specific slot), the unit can return any of the following values:
See page 742 of https://download.tek.com/manual/3700AS-901-01D_Jul_2018_Ref_0.pdf. The interlock state is mapped using a dictionary (`interlock_status` in the `get_interlock_state` method), where the returned value is used as the key to find the appropriate status string. However, this dictionary was initially defined using only two keys, `0` and `1`. When querying the interlock status, the possible return values are `nil`, `0`, `1`, `2`, and `3`. As some of these return values are not included as keys in the `interlock_status` …
> fix(Keithley3706A): Fix interlock status dictionary

- docs/changes/newsfragments/5021.improved_driver
- qcodes/instrument_drivers/AimTTi/Aim_TTi_QL355_TP.py
- qcodes/instrument_drivers/AimTTi/_AimTTi_PL_P.py
- qcodes/instrument_drivers/AimTTi/__init__.py
Hi,
I have added AimTTi QL355TP power supply. 
I also moved the lookup table for other power supplies in case someone wants to easily add his device.
> Add support for AimTTi QL355TP

- docs/changes/newsfragments/5028.new
- docs/examples/Station.ipynb
- qcodes/instrument/channel.py
- qcodes/instrument/instrument_base.py
- qcodes/metadatable/__init__.py
- qcodes/metadatable/metadatable_base.py
- qcodes/parameters/function.py
- qcodes/parameters/parameter_base.py
- qcodes/station.py
- qcodes/tests/common.py
- qcodes/tests/parameter/test_function.py
- qcodes/tests/test_channels.py
- qcodes/tests/test_station.py
This is handy since you can then look up any parameter from its name in the snapshot.
Slightly complicated by the fact that a name could it self contain `_` we handle that by trying to merge the next name_part into the name that we are trying to lookup if the name cannot be found but we do not try to handle all possibilities. E.g. it is possible for the complete name to not be unique
To make this possible change the baseclass of all components to have short_name and full_name properties
> Add ability to lookup component in station by full name

- qcodes/metadatable/metadatable_base.py
- qcodes/tests/test_metadata.py
This communicates via the typesystem what was always documented in the docstring of the method
Also ignore the error in the single test that actually does this.
> Mark snapshot method as final

- docs/changes/newsfragments/5031.breaking
- qcodes/configuration/qcodesrc.json
- qcodes/configuration/qcodesrc_schema.json
- qcodes/dataset/guids.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_guids.py
As earlier suggested this switches the default to replace sample by a random string eliminating duplicate guids. That was especially likely if generating lots of guids on the same system rapidly after each other on a system with low time resolution
> Dataset: change default guid type to use a random str

- qcodes/instrument/instrument_base.py
- qcodes/tests/drivers/test_yokogawa_gs200.py
- qcodes/tests/test_station.py
This makes it possible to get `voltage_range` on the Yokogawa gs200 as shown in the relevant test.
It does perhaps make the error message a little less clear in the context that you try to get `foo_bar` where `foo` is a component but `bar` is not but I think we can live with that
> get_component: In InstrumentBase fall back to a longer name  when not matching a last part of a name

- pyproject.toml
- qcodes/tests/test_interactive_widget.py
Ipywidgets from 8.0.5 no longer officially depends on it but the features we use requires it for now
https://github.com/jupyter-widgets/ipywidgets/issues/3731
> Add explicit dependency on ipykernel

- docs/changes/newsfragments/5090.improved_driver
- qcodes/instrument_drivers/Keysight/N52xx.py
This fixes #5089 and reenables auto_sweep.
I also fix the units for polar which should be a ratio rather than a voltage.
> Fix auto_sweep in Keysight N52xx Driver

- pyproject.toml
As documented here this is not needed
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use
> Drop wheel as a build time dependency

- README.rst
- docs/changes/0.38.1.rst
- docs/changes/index.rst
Since the readme is used as long description this breaks the rendering of the released package on pypi and prevents the release
> fix typo in readme

- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
By  forwarding kwargs to parameter base class as expected
> RS ZNB: Fix deprecation warnings on init

- .github/workflows/pytest.yaml
- qcodes/dataset/dond/do_nd.py
- qcodes/instrument_drivers/Keithley/Keithley_6500.py
- qcodes/instrument_drivers/tektronix/AWG5014.py
- qcodes/tests/delegate/conftest.py
* Upgrade the version of pyright that we use in CI to the latest version and fix a few issues that were now raised.
* Pyright now realized that you cannot pass a function from int to bool to a method that expects a function from str to bool so update the type to reflect that.
* Clarify that some types in the awg5014c driver are always lists of lists so its safe to index into them twice
* Silence an error about the output from tqdm being NoReturn, I did not look into why that is
> Typecheck with pyright 1.1.310

- docs/changes/newsfragments/5200.improved
- qcodes/configuration/qcodesrc.json
- qcodes/configuration/qcodesrc_schema.json
- qcodes/dataset/__init__.py
- qcodes/dataset/dond/do_nd.py
- qcodes/dataset/measurements.py
- qcodes/tests/dataset/dond/test_doNd.py
- qcodes/tests/dataset/measurement/test_shapes.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_dataset_export.py
- qcodes/tests/dataset/test_dataset_in_memory.py
- qcodes/tests/dataset/test_string_data.py
so it may be disabled for huge datasets
> Make in memory cache configurable

- docs/changes/newsfragments/5209.improved
- qcodes/dataset/data_set_in_memory.py
- qcodes/dataset/database_extract_runs.py
- qcodes/dataset/dataset_helpers.py
- qcodes/tests/dataset/test_dataset_in_mem_import.py
This should fix the issue of run_ids not getting incremented when importing netcdf datasets or datasets in memory in general.
Addressing the issue we have talked about @jenshnielsen .
I have replaced the table name return value, as I could not find it used anywhere and it is not a part of a public API.
> Update run_id when adding ds in mem to db

- docs/changes/newsfragments/5201.improved_driver
- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
R&S ZNB timeout was set to sweep time, plus a private attribute called `_additional_wait` .
This PR increases timeout to 1.5 * sweep time, and expose `additional_wait` attribute as public (no leading underscore).
> Change R&S ZNB timeout calculation

- qcodes/dataset/sqlite/queries.py
This PR add quotes around column names in sqlite query.
Closes #5217
> Add quote to escape sqlite keywords (Fixing #5217)

- requirements.txt
version 6.0.0 removed various deprecated functions but these are still used by towncrier which we use to build the docs.
This is fixed in https://github.com/twisted/towncrier/pull/529/ but not yet in a release
Also remove env marker from importlib_metadata. This file is only used to constrain requirements so there is no need
to use the env marker here. That is done in pyproject.toml and having it here prevents dependabot from bumping the version
> pin importlib_resources to 5 series

- docs/conf.py
Also remove a not needed and error prone path modification in the docs build.
> Silence warnings during docs build

- docs/changes/newsfragments/5297.improved
- qcodes/logger/instrument_logger.py
This enables opentelemetry to consume these fields as extras on the log record which it cannot do for the instrument itself since that is not a natively supported type.
> InstrumentLoggerAdaptor store instrument_name and type in record

- docs/changes/newsfragments/5329.improved
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/test_database_extract_runs.py
This fixes #5328 by ensuring that new runs are inserted with a captured counter/runid that matches the assigned run_id / counter
> Calculate new run_id/counter from run_id/counter

- docs/changes/newsfragments/5289.new
- docs/examples/logging/logging_example.ipynb
- pyproject.toml
- qcodes/dataset/dond/do_0d.py
- qcodes/dataset/dond/do_1d.py
- qcodes/dataset/dond/do_2d.py
- qcodes/dataset/dond/do_nd.py
- qcodes/dataset/measurement_extensions.py
- qcodes/dataset/measurements.py
This will make it possible to better track the duration and errors within experiments.
TODO
> Instrument Measurement and dond with opentelemetry

- .github/workflows/docs.yaml
- .github/workflows/pytest.yaml
In jobs such as https://github.com/QCoDeS/Qcodes/pull/5348 one matrix job failed due to network issues making all the jobs fail. It seems better to just let all the jobs run to the end
> CI don't fail all jobs on one job failure

- docs/changes/newsfragments/5341.improved
- pyproject.toml
- qcodes/instrument/visa.py
- qcodes/tests/test_instrument.py
- qcodes/tests/test_visa.py
Partial fix for #3774 it's tricky to do this generally since the finalizer cannot take a reference to the instrument it self and therefore also not a method on this such as `self.close`. 
For visa instruments this is possible to implement since we only need a reference to the visa_handle to close the connection. This could also be implemented more generally if we created a handle/closer class on all instruments. 
This also adds tests that confirms that visa instruments are closed once the instrument is out of scope and gc'ed. 
Closes https://github.com/QCoDeS/Qcodes/issues/5356 by closing the resource_manager in close if the backend is sim. Since this only applies to simulated instruments we don't add it to the finalizer but assume as always that a test must cleanup after it self.
> Use weakref finalize to close visa connections

- qcodes/_version.py
- qcodes/configuration/config.py
- qcodes/monitor/monitor.py
This replaces the remaining use of `__file__` with `files` from `imporlib.resources` in qcodes outside of the tests.
Note that there is a trade off here as we now have hardcoded the path to config and monitor dist files in the python file rather than the relative path to that file. I think its cleaner to hardcode the full path but I could see the argument the other way around too.
> Stop using __file__ outside tests

- qcodes/instrument/ip_to_visa.py
- qcodes/instrument/visa.py
- qcodes/instrument_drivers/Keithley/Keithley_s46.py
- qcodes/tests/drivers/test_ami430_visa.py
- qcodes/tests/drivers/test_keithley_s46.py
- qcodes/tests/drivers/test_keysight_34980a.py
When all pyvisa-sim instruments defined by a yaml file is closed reset the instruments. This in practice will ensure that every test will reset the state of pyvisa-sim instruments on exit since the test must close instruments anyway.
closes https://github.com/QCoDeS/Qcodes/issues/5356
See https://github.com/pyvisa/pyvisa-sim/issues/83 for details
> Instrument tests: Avoid leaking state between tests

- docs/start/index.rst
Added a section to the installation guide advising users to fetch tags from the upstream QCoDeS repository when installing from a forked repository.
> Update index.rst (Add instructions about fetching tags)

- .github/workflows/pytest.yaml
- qcodes/tests/dataset/helper_functions.py
Typechecking broke with the lastes version of pandas stubs. This fixes that. Also upgrade pyright to the latest version.
> Fix pandas type check

- qcodes/dataset/exporters/export_to_xarray.py
As the old method is deprecated as of xarray 2023.9.0
See https://docs.xarray.dev/en/stable/whats-new.html#breaking-changes (breaking changes for 2023.9.0)
> Create Coord before passing it to xarray

- qcodes/logger/logger.py
- qcodes/tests/common.py
- qcodes/tests/conftest.py
- qcodes/tests/dataset/dond/test_do0d.py
- qcodes/tests/dataset/dond/test_doNd.py
- qcodes/tests/dataset/measurement/test_measurement_context_manager.py
- qcodes/tests/dataset/measurement/test_shapes.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_dataset_export.py
- qcodes/tests/dataset/test_dataset_in_mem_import.py
- qcodes/tests/dataset/test_dataset_in_memory.py
- qcodes/tests/dataset/test_dataset_loading.py
- qcodes/tests/dataset/test_guids.py
- qcodes/tests/dataset/test_snapshot.py
- qcodes/tests/dataset/test_string_data.py
- qcodes/tests/dataset/test_subscribing.py
- qcodes/tests/delegate/conftest.py
- qcodes/tests/drivers/test_Keysight_33XXX.py
- qcodes/tests/drivers/test_Keysight_N6705B.py
- qcodes/tests/drivers/test_keithley_7510.py
- qcodes/tests/drivers/test_keysight_34934a.py
- qcodes/tests/drivers/test_tektronix_dpo7200xx.py
- qcodes/tests/test_config.py
- qcodes/tests/test_logger.py
- qcodes/tests/test_plot_utils.py
- qcodes/tests/test_station.py
Replace existing config fixtures with 2 auto use fixtures.
* A session fixture that makes sure that we load the default config and do not read / write config from any user folder. This makes sure that we dont fail tests due to config changes of the user or modify user configs. Also let this handle setting changes that we want to be different from the default. Disable telemetry, disable subscribers, set db path to a non existing file so test can't write to the default db if not using dataset / experiment fixtures.
* A function fixture that resets any modification that a test has made to the config, closes any instruments and resets the default station
Since these are auto use we can remove all explicit use of config fixtures.
In the process fix some issues.
* The old default_config fixture …
> Rework config fixtures

- pyproject.toml
rebased against main of ms/typing-stubs and removed matplotlib as matplotlib is now typed.
> upgrade type stubs

- qcodes/tests/conftest.py
- qcodes/tests/test_logger.py
* When possible avoid reading from log file but use caplog to get logging
* Rework cleanup fixture to not touch pytest handlers but only remove handlers inserted by the test
* Ensure that logging is off by default in tests
Closes https://github.com/QCoDeS/Qcodes/issues/5418
> Improve logger test

- docs/changes/newsfragments/5391.new
- pyproject.toml
- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_protocol.py
- qcodes/dataset/exporters/export_to_xarray.py
- qcodes/tests/dataset/test_dataset_export.py
Avoid loading a potentially huge dataset into memory just to be able to rewrite it to disk. 
This writes each row of a dataset to disk individually and then uses dask/xarray to lazily merge the dataset into one file
> Use Dask delayed to export large datasets to NetCDF

- docs/changes/newsfragments/5425.breaking
- pyproject.toml
- requirements.txt
They no longer have an effect since that code was only used in modules that are now part of the qcodes-loop package
> remove slack and qtplot extra install targets

- docs/changes/newsfragments/5399.breaking
- qcodes/dataset/sqlite/database.py
- qcodes/instrument_drivers/tektronix/AWG5014.py
- qcodes/tests/drivers/test_ami430.py
- qcodes/tests/drivers/test_ami430_visa.py
- qcodes/tests/validators/test_arrays.py
- qcodes/utils/numpy_utils.py
- qcodes/utils/types.py
- qcodes/validators/validators.py
Numpy 2.0 is scheduled to be released this year (https://github.com/numpy/numpy/issues/24300). In this PR we adapt qcodes to work with numpy 2.0.
The `numpy_non_concrete_floats_instantiable` and `numpy_non_concrete_complex_instantiable` are now empty, perhaps it is better to just remove them. (they are public, but not used in the qcodes codebase)
> Update qcodes to support numpy 2.0

- docs/changes/0.41.0.rst
- docs/changes/index.rst
- docs/changes/newsfragments/5334.new
- docs/changes/newsfragments/5367.breaking
- docs/changes/newsfragments/5381.new
- docs/changes/newsfragments/5391.new
- docs/changes/newsfragments/5399.breaking
- docs/changes/newsfragments/5425.breaking
- docs/changes/newsfragments/5426.new
> add changelog for 0.41.0

- .github/workflows/darker.yaml
This was required due to a bug in darker that has been fixed.
> Darker: remove no longer required workaround

- .github/workflows/darker.yaml
- docs/changes/0.41.1.rst
- docs/changes/index.rst
- qcodes/parameters/parameter_base.py
- qcodes/tests/parameter/test_validators.py
The intent was that it should not be possible to set a float step size if any of the validators was an Int validator. That was however not correctly implemented.
Adding changelog directly to save a bit of time on towncrier since I am going to cut a new release just after merging this
> Fix incorrect step logic in validator.

- pyproject.toml
Looks like the tests are no longer correctly excluded from the coverage so change paths to include src dir.
also remove exclusion of a non-existing file.
> fix coverage links

- .github/workflows/pytest.yaml
Otherwise codecov gets confused by the number of jobs in a branch build compared to pr
> don't upload coverage from merge groups

- docs/changes/newsfragments/5496.improved
- src/qcodes/instrument_drivers/agilent/Agilent_E8257D.py
Fixes https://github.com/QCoDeS/Qcodes/issues/5484
> fix call to incorrect parameter in Agilent8257D driver

- docs/changes/newsfragments/5517.improved
- src/qcodes/dataset/data_set_in_memory.py
- src/qcodes/dataset/data_set_protocol.py
- tests/dataset/test_dataset_export.py
> Fix expansion of multi index when loading im memory cache from a netcdf file

- tests/dataset/measurement/test_measurement_context_manager.py
It does not seem like these 2 plugins work well together and the use of Hypothesis is limited anyway.
This test seems to be even more unreliable with python 3.12 for some reason
> Remove Hypothesis from flaky test

- .github/workflows/docs.yaml
* Keep going on errors so we can see all errors on failures.
* Hash docs package cache including docs/conf.py this will ensure that the cache is different for docs and test jobs which correctly reflects that the two jobs install different packages
> Slight improvements to docs build

- docs/changes/newsfragments/5520.improved
- src/qcodes/instrument_drivers/Lakeshore/_lakeshore_model_335.py
According to the manual (https://www.lakeshore.com/docs/default-source/product-downloads/335_manual.pdf?sfvrsn=9f5c5b7f_7) , page 121:
> `input` Specifies which input to use for control: 0 = None, 1 = A, 2 = B
Here, we add the parameter mapping for the value 0.
> Lakeshore 335 Output: Add parameter mapping for input=None

- src/qcodes/dataset/data_set.py
- tests/dataset/test_dataset_export.py
Rather than using sys.getsizeof which has a huge overhead when the row size is small.
E.g. a dataset with many small rows. 
```
In [2]: import numpy as np
In [3]: d = np.array([[1,2,3],[4,5,6]])
In [4]: import sys
In [5]: sys.getsizeof(d)
Out[5]: 152
In [6]: d.dtype.itemsize * d.size
Out[6]: 24
```
Also add a test for exporting pure numeric datasets which was previously not covered.
And correct a warning from opentelemetry due to non str attributes on log messages
> Better treshold calculation for chunked output

- src/qcodes/dataset/dond/do_nd.py
- src/qcodes/dataset/measurement_extensions.py
One is no longer needed with newer pyright and the other one can be fixed by using buildin callable rather than isinstance checking against typing callable
> remove a few no longer needed type ignores

- docs/changes/newsfragments/improved_driver.5547
- src/qcodes/instrument_drivers/Keithley/Keithley_2450.py
Added a parameter to control whether or not ramp commands sent to Keithley 2450s block
> Optional blocking in Keithley 2450

- requirements.txt
This reverts commit 6db80ffb159dcf87546e2f1e4926e7484f1ac2d9.
6.27 way yanked
> Revert "Update ipykernel requirement from ~=6.26.0 to ~=6.27.0"

- docs/changes/newsfragments/improved_driver.5572
- src/qcodes/instrument_drivers/Keithley/Keithley_2450.py
Setting an initial value for the keithley output is quite dangerous, especially when recovering from a kernel crash. Initializing the instrument should leave the output state unchanged
> Remove initial value for output of Keithley 2450

- src/qcodes/dataset/sqlite/queries.py
- src/qcodes/dataset/sqlite/query_helpers.py
- tests/dataset/test_dataset_basic.py
Historically it has been possible to create a arbitrary table name. Such a name could contain `'` which would escape the quotes around the table name in length. This resolves that by replacing quotes internal to the str with their escaped form.
> Dataset: Fix quoted str when getting length of dataset and handle that users could have passed a list of floats as shape

- docs/changes/newsfragments/underthehood.5579
- src/qcodes/instrument_drivers/mock_instruments/__init__.py
- tests/test_instrument.py
fix typo key of dict returned by get_idn of Dummy instruments.
> Fix typo in DummyBase::get_idn

- .github/workflows/pytest.yaml
- pyproject.toml
- src/qcodes/instrument/instrument.py
Mainly interesting because pyright has added a new default mode that we opt out of until we have fixed typing issues in that mode
> Typecheck with pyright 1.1.339

- tests/dataset/measurement/test_measurement_context_manager.py
This test often fails probably because of timing
issues so add a bit more sleep time if the points have not been written
> Try to reduce flakiness of test

- docs/changes/newsfragments/5589.improved
- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/data_set_cache.py
- src/qcodes/dataset/data_set_in_memory.py
- src/qcodes/dataset/data_set_protocol.py
- src/qcodes/dataset/exporters/export_to_xarray.py
- tests/dataset/test_dataset_export.py
* Only automatically select multi index export if shapes are unset
* Allow the user to select which export type to use
> Smarter selection of multi index export to xarray

- tests/dataset/test_dataset_export.py
- tests/dataset/test_measurement_extensions.py
fixes 
> FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be
> more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
This fixes all places where we make use of .dims as a dict There are a number of places where we use it to get the names/number of the dimensions. Here we continue using .dims
> Fix XArray FutureWarning

- docs/changes/newsfragments/5618.improved
- src/qcodes/configuration/qcodesrc.json
- src/qcodes/configuration/qcodesrc_schema.json
- src/qcodes/dataset/data_set.py
- tests/dataset/test_dataset_export.py
There are unfortunately a few too many corner cases where this does not work well so leaving it off by default.
There may still be cases where this is useful so it can be enabled in those cases by temporarily setting the config. For now I have not added this as an option to the export method since it does not really seem to fit well in the api
TODO
> Make delayed/chunked export configurable and off by default

- tests/dataset/measurement/test_measurement_context_manager.py
This test remains flaky so try runnig it serially to hopefully reduce this
> Run flaky test in serial

- docs/changes/newsfragments/5320.improved
- src/qcodes/configuration/qcodesrc.json
- src/qcodes/configuration/qcodesrc_schema.json
- src/qcodes/dataset/__init__.py
- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/data_set_in_memory.py
- src/qcodes/dataset/load_config.py
- tests/dataset/test_dataset_in_memory.py
We've been having issues using Plottr in tandem with measurements because they access the sqlite database at the same time. We think that simultaneous read/write operations from both processes have been causing either one of them to crash. A potential solution I came up with is to have load_by_id load the dataset from an exported netcdf file, if it exists.
Please take a look and let me know if you think this is a reasonable solution, I'm currently testing it to see if it actually solves the problem.
> load_by_id optionally loads data from exported file

- tests/conftest.py
The monitor tests are somewhat flaky on windows failing with a not able to bind to socket error. One reason could be that the monitor is shutdown properly in other tests. This adds a auto fixture  to stop the monitor thread
> shut down monitor thread on test exit

- .github/workflows/pre-commit.yml
After moving to the Microsoft org we no longer can use the precommit-ci bot so we will do precommit hooks manually in github actions
> Add precommit action

- docs/changes/newsfragments/5641.improved
- src/qcodes/dataset/exporters/export_to_pandas.py
- tests/dataset/test_dataset_export.py
Handle that we could see coordinates of dtype object for other reasons than ragged arrays.
Specifically this can happen if we load a dataset from a netcdf file with xarray <2023.11.0 convert it to a qcodes dataset and try to convert it back to xarray
> More robust converting to pandas / xarray

- docs/changes/newsfragments/5627.improved
- src/qcodes/dataset/data_set_cache.py
- src/qcodes/dataset/data_set_in_memory.py
- tests/dataset/test_dataset_export.py
> Avoid roundtrip to qcodes format when loading as xarray from netcdf

- .github/workflows/darker.yaml
- .github/workflows/docs.yaml
- .github/workflows/pytest.yaml
This limits the damage a rouge job can do
> set default github token permission to read only.

- requirements.txt
This fixes the one remaining vulnerability in https://github.com/microsoft/Qcodes/security/code-scanning/52
> remove unused py package from requirements

- docs/changes/newsfragments/5711.improved
- src/qcodes/dataset/data_set_in_memory.py
- tests/dataset/test_dataset_export.py
This is an extension to #5627 which also avoids loading the data from a netcdf file into qcodes format when loading the file using load_by_guid etc.
> Make loading from netcdf lazy using load_by_guid etc.

- docs/changes/newsfragments/5712.breaking
- pyproject.toml
- src/qcodes/instrument/ip_to_visa.py
- src/qcodes/instrument_drivers/american_magnetics/AMI430.py
- tests/drivers/test_ami430.py
The visa one is better supported and has fewer issues.
> mark non visa AMI driver as deprecated.

- .github/workflows/pytest.yaml
- pyproject.toml
- src/qcodes/dataset/sqlite/queries.py
- src/qcodes/instrument_drivers/Keithley/_Keithley_2600.py
- src/qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
- src/qcodes/instrument_drivers/Minicircuits/USBHIDMixin.py
- src/qcodes/instrument_drivers/tektronix/AWG70000A.py
- src/qcodes/parameters/array_parameter.py
- src/qcodes/parameters/multi_parameter.py
- src/qcodes/sphinx_extensions/parse_parameter_attr.py
- src/qcodes/utils/deprecate.py
- src/qcodes/utils/spyder_utils.py
And enables most of standard type checkings
> Upgrade pyright to 1.1.349

- tests/test_field_vector.py
This should hopefully avoid corner cases in test_triangle_inequality where one of the vectors is very small but none zero
since the values are anyway limited to the resolution of the instruments there is little point in supporting more than 10 digits
Closes https://github.com/microsoft/Qcodes/issues/4425
> only use 10 digits when testing field vectors

- .github/workflows/pytest.yaml
This removes the dependency on requirements builder
> use uv to generate min requirements

- .github/workflows/pytest.yaml
- docs/changes/newsfragments/5721.breaking
- pyproject.toml
- src/qcodes/dataset/legacy_import.py
- src/qcodes/instrument/channel.py
- src/qcodes/instrument_drivers/AlazarTech/ATS_acquisition_controllers.py
- src/qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
- src/qcodes/instrument_drivers/Keysight/Infiniium.py
- src/qcodes/instrument_drivers/Keysight/Keysight_N9030B.py
- src/qcodes/instrument_drivers/Keysight/KtM960x.py
- src/qcodes/instrument_drivers/Keysight/N52xx.py
- src/qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
- src/qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_sampling_measurement.py
- src/qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
- src/qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
- src/qcodes/instrument_drivers/QDev/QDac_channels.py
- src/qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
- src/qcodes/parameters/parameter.py
- src/qcodes/parameters/parameter_base.py
- src/qcodes/tests/dataset/conftest.py
- src/qcodes/utils/json_utils.py
- tests/dataset/conftest.py
- tests/parameter/test_get_latest.py
- tests/parameter/test_manual_parameter.py
- tests/parameter/test_parameter_cache.py
This basically means checking that overrides are compatible with the base class
Breaking changes
* The first argument to NumpyJSONEncoder.default is not o not obj. I don't expect this to be called directly. Only public so it can be passed to a json encoder. 
* Unused arguments to QDac connect_messsage have changed. Not an issue since they are unused.
* Keysight N52XX and Infiniium Unused arguments to stub setpoints and unit methods have changed from val to setpoints / unit. Not an issue since these are unused stubs. 
* Alazar DemodulationAcquisitionController handle_data argument changed from data to buffer. Probably unlikely to be called as a kwarg.
* ~InstrumentModule/Channel obj -> value in Sequence/MutableSequence methods. IMHO unlikely to be called by arg since these are simple …
> Run pyright with standard checks

- README.rst
Only show the main branch runs in the readme badge. That way the badge will not show failing simply because a pr failed
> Readme badges show main branch runs

- pyproject.toml
- setup.py
This has been possible since version 2.2 so bump
min version accordingly.
Remove warnings for older pip versions since the relevant versions are now 6 years old
> Move versioningit config to pyproject.toml

- pyproject.toml
- src/qcodes/configuration/config.py
- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/sqlite/queries.py
- src/qcodes/instrument/visa.py
- src/qcodes/instrument_drivers/AlazarTech/ATS.py
- src/qcodes/instrument_drivers/Harvard/Decadac.py
- src/qcodes/instrument_drivers/Keysight/Keysight_B2962A.py
- src/qcodes/instrument_drivers/Keysight/keysight_34934a.py
- src/qcodes/instrument_drivers/mock_instruments/__init__.py
- src/qcodes/instrument_drivers/oxford/triton.py
- src/qcodes/instrument_drivers/rohde_schwarz/ZNB.py
- src/qcodes/instrument_drivers/signal_hound/SignalHound_USB_SA124B.py
- src/qcodes/instrument_drivers/stanford_research/SR560.py
- src/qcodes/instrument_drivers/tektronix/AWG5014.py
- src/qcodes/interactive_widget.py
- src/qcodes/parameters/group_parameter.py
- src/qcodes/parameters/parameter_base.py
- src/qcodes/station.py
- src/qcodes/tests/common.py
These will help the user write docstrings with fewer issues without having to do the sphinx compile round trip
> Enable additional Ruff pydocstyle lints

- src/qcodes/instrument/visa.py
handle.session may throw this error if the session is closed. In that case the connection is already closed so do nothing
> gracefully handle error from pyvisa

- pyproject.toml
- src/qcodes/dataset/exporters/export_to_xarray.py
- src/qcodes/dataset/plotting.py
- src/qcodes/interactive_widget.py
This improves import time by ensuring that dask and matplotlib are only imported lazily. With these improvements import time is ~1.1 sec for me. Out of these the main contributions are numpy contributes 0.172 s and jsonschema 0.229 s. These are not easily removed since numpy is used everywhere and jsonschema is required to validate the default config.
> Import speedup

- docs/changes/newsfragments/5887.improved
- src/qcodes/dist/schemas/station-template.schema.json
- src/qcodes/station.py
- src/qcodes/utils/__init__.py
- src/qcodes/utils/attribute_helpers.py
- tests/utils/test_getattr_indexed.py
Some drivers (see zurich-instruments) only expose parameters through an interface which needs indexing in addition to attribute access. This patch enables access to those parameters in the station yaml file.
> Simple indexed attribute access in station files

- docs/changes/newsfragments/5932.breaking
- docs/examples/Station.ipynb
- src/qcodes/instrument_drivers/tektronix/DPO7200xx.py
- src/qcodes/instrument_drivers/tektronix/__init__.py
These two DPO channels had a missing t in their names. 
I could be convinced that we should retain the old names as deprecated aliases but since these are not the top level instruments names I don't think that is required.
> Fix typos in two Tektronix channel classes

- .github/dependabot.yml
- .github/package.json
- .github/workflows/pytest.yaml
- .gitignore
Rather than installing the package this parses the version out of a packages.json file making the setup simpler
> Keep Pyright up to date as a npm package.

- src/qcodes/instrument_drivers/Keysight/Infiniium.py
This makes parameters be documented by sphinx even without a docstring.
> Infiniium: add type annotation to parameter attrs

- docs/changes/newsfragments/5991.breaking
- pyproject.toml
- requirements.txt
- src/qcodes/logger/logger.py
And remove default install of opencensus and opencensus azure integration.
Note that this does not yet remove opencensus from requirements.txt. This will happen once a release of qcodes with these changes is out. This is due to the "circular" dependencies between qcodes[test], qcodes-loop, and qcodes. 
TODO
> Deprecate opencensus integration

- src/qcodes/parameters/parameter.py
- src/qcodes/parameters/parameter_base.py
- tests/parameter/test_get_latest.py
- tests/parameter/test_parameter_cache.py
This private api is used in zhinst qcodes https://github.com/zhinst/zhinst-qcodes/blob/main/src/zhinst/qcodes/qcodes_adaptions.py#L202
This reverts an insignificant part of #5721
> revert changes to _get / _set_wrapper in ParameterBase

- docs/changes/newsfragments/6009.improved
- src/qcodes/instrument/instrument_base.py
- src/qcodes/instrument_drivers/mock_instruments/__init__.py
- tests/test_station.py
Enable component to be looked up from a channeltuple in case it has only been added as such.
> get_component allow lookup from channeltuple/list

- .github/workflows/docs.yaml
- src/qcodes/instrument_drivers/Lakeshore/Lakeshore_model_325.py
This overwrites two methods that have broken docstrings in the std library. Note that a proper fix is in https://github.com/python/cpython/pull/117847
This in turn will allow us to enable warnings as errors once again in the docs build
> Workaround broken docstrings in the python std library

- tests/test_visa.py
We call the self.session property on the visa resource.
This will give an unexpected error if self._seesion is not defined
> Fix issue in teardown of MockVisa

- docs/changes/newsfragments/6035.improved_driver
- src/qcodes/instrument_drivers/Keysight/N52xx.py
This PR adds trace manipulation commands to the Keysight PNA driver.
Specifically, we now allow the following interactions:
- `trace = pna.add_trace()`: Create a new trace (of any number) on the PNA
- `trace = pna.enable_trace(trace_num)`: Enable and return the given trace number
- `trace.disable()`: Disable a trace on the PNA
> Add trace manipulation commands to Keysight PNA driver

- pyproject.toml
- tests/dataset/test_measurement_extensions.py
- tests/dataset/test_string_data.py
- tests/drivers/test_lakeshore.py
- tests/test_visa.py
Over in https://github.com/microsoft/Qcodes/pull/4412 I would like to use [assert_type](https://docs.python.org/3/library/typing.html#typing.assert_type) to check that the right type is deducted for a parameter attribute. For that to make sense we should type check the tests. 
To enable this:
* Enable pyright on tests
* Update mock interfaces to match upstream interface
* Update some pyright ignores to match the current version of pyright
> Type check tests

- requirements.txt
Now that qcodes by default no longer depends on opencensus we can remove quite a few dependencies
> Regenerate requirements file

- src/qcodes/parameters/parameter.py
- src/qcodes/utils/abstractmethod.py
Ensure that qcodes_abstractmethod retains the type of the decorated method.
> Better typing of qcodes_abstractmethod

- src/qcodes/instrument/instrument.py
- tests/test_instrument.py
It turns out that overriding `__call__` for the metaclass will limit pyrights ability to check the type of the constructor. See https://github.com/microsoft/pyright/discussions/5561 
To work around this, we avoid using the metaclass when type checking. This is safe since the only taks of the metaclass is to register instruments which is a runtime only task.
> Fix typing of Instrument

- docs/changes/newsfragments/6084.improved
- src/qcodes/dataset/measurements.py
- tests/dataset/measurement/test_measurement_context_manager.py
(Partially) fixes https://github.com/microsoft/Qcodes/issues/6080.
> Test setpoints and basis types in register_parameter

- src/qcodes/parameters/parameter_base.py
- tests/parameter/test_parameter_context_manager.py
Currently, using the `set_to` context fails on exit for parameters whose value does not pass the set parser or validator. The only -- but common -- case where this happens are uninitialized parameters, in which case the value is `None`.
This change catches exceptions when setting the original value and then sets the cache value instead. The exception catch is very broad, but as far as I can tell, validators can raise any kind of exception they like. Only doing this if `original_value` is `None` might be a bit safer -- are there other cases?
> Allow parameter contexts for uninitialized parameters

- src/qcodes/instrument/instrument_base.py
- tests/drivers/test_lakeshore.py
This was left for backwards compatibility with zhinst drivers that no longer uses it so let's deprecate it now.
> Deprecate unused private `_name` property on instruments 

- src/qcodes/instrument_drivers/Keithley/Keithley_s46.py
- src/qcodes/parameters/array_parameter.py
- src/qcodes/parameters/multi_parameter.py
- src/qcodes/parameters/specialized_parameters.py
- tests/parameter/test_get_set_wrapping.py
This makes it less likely to mix up args in the rather long lists of args that these classes takes and to prepare for doing
something similar to #6012 for parameters.
> Pass parameter kwargs as kwargs

- docs/changes/newsfragments/6089.improved_driver
- docs/drivers_api/Agilent.rst
- src/qcodes/instrument_drivers/agilent/Agilent_34401A.py
- src/qcodes/instrument_drivers/agilent/Agilent_34410A.py
- src/qcodes/instrument_drivers/agilent/Agilent_34411A.py
- src/qcodes/instrument_drivers/agilent/Agilent_E8257D.py
- src/qcodes/instrument_drivers/agilent/Agilent_E8267C.py
- src/qcodes/instrument_drivers/agilent/_Agilent_344xxA.py
- src/qcodes/instrument_drivers/agilent/__init__.py
This is an example of applying #4412 to Agilent drivers
* Convert attributes to be assigned using automatic tool
* Move model specific parameters into submodels so they can be declared statically
* Document baseclass and disable documentation of inherited attributes. This is such that the duplication is reduced and the docs becomes more readable.
> Refactor Agilent drivers

- docs/changes/newsfragments/6106.improved_driver
- src/qcodes/instrument_drivers/AlazarTech/ATS.py
Fixes #6104.
The example now runs on my end (excepting trigger timeouts, which are likely to be device-sided).
> Fix Alazar drivers

- docs/changes/newsfragments/6105.improved_driver
- docs/drivers_api/AimTTi.rst
- src/qcodes/instrument_drivers/AimTTi/_AimTTi_PL_P.py
- src/qcodes/instrument_drivers/AimTTi/__init__.py
* Convert attributes to be assigned using automatic tool
* Document baseclass and disable documentation of inherited attributes. This is such that the duplication is reduced, and the docs becomes more readable.
> Refactor AimTTI drivers 

- docs/changes/newsfragments/6114.improved_driver
- docs/drivers_api/HP.rst
- docs/drivers_api/Harvard.rst
- docs/drivers_api/Ithaco.rst
- src/qcodes/instrument_drivers/HP/HP_8133A.py
- src/qcodes/instrument_drivers/HP/HP_83650A.py
- src/qcodes/instrument_drivers/HP/HP_8753D.py
- src/qcodes/instrument_drivers/Harvard/Decadac.py
- src/qcodes/instrument_drivers/ithaco/Ithaco_1211.py
* Convert all drivers  HP -> Ithaco to new add_parameter format.
* Don't document inherited attributes
TODO
>  Refactor drivers HP -> Ithaco

- docs/changes/newsfragments/6115.improved_driver
- docs/drivers_api/Keithley.rst
- src/qcodes/instrument_drivers/Keithley/Keithley_2000.py
- src/qcodes/instrument_drivers/Keithley/Keithley_2400.py
- src/qcodes/instrument_drivers/Keithley/Keithley_2450.py
- src/qcodes/instrument_drivers/Keithley/Keithley_3706A.py
- src/qcodes/instrument_drivers/Keithley/Keithley_6500.py
- src/qcodes/instrument_drivers/Keithley/Keithley_7510.py
- src/qcodes/instrument_drivers/Keithley/Keithley_s46.py
- src/qcodes/instrument_drivers/Keithley/_Keithley_2600.py
- src/qcodes/instrument_drivers/Keithley/__init__.py
Convert all Keithley drivers to new add_parameter format.
Don't document inherited attributes
Document base classes
A fix docs fixes
TODO
> Refactor Keithley drivers

- docs/changes/newsfragments/6073.improved
- src/qcodes/parameters/multi_channel_instrument_parameter.py
- tests/parameter/test_multi_channel_instrument_parameter.py
As of now, the `MultiChannelInstrumentParameter` is inconsistent; its setter does not accept the values returned by its getter as the first accepts a scalar `ParamRawDataType`, but the last returns a tuple thereof. This is particularly problematic as it breaks the `set_to` context manager.
This proposed change modifies the setter to allow both the current scalar behavior as well as a sequence, in which case it is zipped together with `self._channels`.
> Accept sequences of values for setting MultiChannelInstrumentParameter

- src/qcodes/monitor/monitor.py
Set a result rather than cancel the future
This avoids a potential exception in the async event loop
Unfortunately does not resolve #6099 but I think this is still worthwhile to merge
> Attempt to fix issue with monitor closing

- src/qcodes/math_utils/field_vector.py
- tests/drivers/test_ami430_visa.py
These are triggered due to floating point round off errors.
Since we do not accept warnings in the test suite these cause tests to fail
> Avoid triggering warnings + nan in fieldvector conversion

- docs/changes/newsfragments/6128.improved_driver
- docs/drivers_api/Lakeshore.rst
- src/qcodes/instrument_drivers/Lakeshore/Lakeshore_model_325.py
- src/qcodes/instrument_drivers/Lakeshore/Lakeshore_model_336.py
- src/qcodes/instrument_drivers/Lakeshore/Lakeshore_model_372.py
- src/qcodes/instrument_drivers/Lakeshore/Model_336.py
- src/qcodes/instrument_drivers/Lakeshore/Model_372.py
- src/qcodes/instrument_drivers/Lakeshore/__init__.py
- src/qcodes/instrument_drivers/Lakeshore/_lakeshore_model_335.py
- src/qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
- tests/drivers/test_lakeshore.py
> Lakeshore refactor

- docs/changes/0.46.0.rst
- src/qcodes/instrument/instrument_base.py
- src/qcodes/parameters/parameter_base.py
- tests/parameter/test_parameter_override.py
Since it now becomes more common for parameters to be assigned as real attributes it makes sense to also test for this
I have added a work around where a property of the same name is allowed to exist. This is done to support a known pattern where  a property is added to define an interface
> Error on setting parameter if this already exists as an attribute

- docs/changes/0.46.0.rst
- src/qcodes/parameters/parameter_base.py
- tests/parameter/test_parameter_override.py
This makes the error from #6174 a warning if the overridden attribute is not itself a parameter.
> Only warn on parameter overriding attribute if this is not a parameter

- src/qcodes/dataset/data_set_in_memory.py
One of the warnings in `data_set_in_memory.py` was missing the `f` in front of the string.
> hotfix: add f-string identifier to warning string 

- docs/changes/newsfragments/6248.improved_driver
- src/qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
Add power output parameters to LakeShore335 driver, this allows to configure the maximum heater current.
> LakeShore335: add power output parameters

- src/qcodes/instrument_drivers/Keysight/Infiniium.py
also fix channel numbers for trigger
> Keysight Infiniium: feat: add input (coupling & impedance) for channels

- src/qcodes/instrument_drivers/tektronix/AWG70000A.py
This change adds support for the `offset` parameter on Tektronix AWG channels.
See page 2-261 of the [AWG5200 Programmer Manual](https://download.tek.com/manual/AWG5200-Programmer-Manual-077133700-RevA.pdf) for full details on this command.  A summary of the syntax from that page is as follows:
```
SOURce[n]:]VOLTage[:LEVel][:IMMediate]:OFFSet
This command sets or returns the Offset (for DC output paths) for the waveform
associated with the specified channel.
Conditions This is a blocking command. (See page 2-9, Sequential, blocking, and overlapping
commands.)
Group: Source
Syntax
- [SOURce[n]:]VOLTage[:LEVel][:IMMediate]:OFFSet <NRf>
- [SOURce[n]:]VOLTage[:LEVel][:IMMediate]:OFFSet?
```
> Add 'offset' parameter to Tektronix AWG Channels

- src/qcodes/dataset/experiment_container.py
Instead of checking with just the length of the experiment list.
Check that the exp_id is in the experiment list.
Useful when working with an offset or missing entries in the database.
> Fix: Check exp_id in experiment list

- docs/changes/newsfragments/6306.improved_driver
- src/qcodes/instrument/sims/AMI430.yaml
- src/qcodes/instrument_drivers/american_magnetics/AMI430_visa.py
- tests/drivers/test_ami430_visa.py
* Don't trigger warnings when snapshotting a AMI430 without an enabled switch heater
* Deprecate confusing setter/getter methods that duplicate parameters
* Deprecate some more aliases
> AMI430 cleanup

- src/qcodes/instrument_drivers/Lakeshore/Lakeshore_model_336.py
The Lakeshore336 has a hardware option to set the input_channel of a heater output to 'None'. This option is currently not reflected in the driver/LakeshoreModel336CurrentSource and if it was manually set to 'None' at the hardware, the driver will fail to get or set the input_channel of the output remotely. 
This commit fixes this by adding `ch_name='None'` with `num_for_cmd=0` to `_input_channel_parameter_kwargs`.
> Lakeshore336: Add None as possible input_channel name for heater_outputs

- docs/changes/newsfragments/6422.improved
- src/qcodes/dataset/dond/do_nd.py
- src/qcodes/dataset/dond/do_nd_utils.py
- tests/dataset/dond/test_doNd.py
This is inspired by matplotlib [`plt.subplots` ](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html#matplotlib-pyplot-subplots)
It makes it easier to write type checked code since with sqeeze=False you can always assume the output type to be the same. In the same was it also makes it easier to write dynamic code where you may or may not do more than one measurement
> Extend doNd to support squashing not squashing output type

- docs/changes/newsfragments/6394.improved
- pyproject.toml
- src/qcodes/instrument/instrument_base.py
- tests/parameter/test_parameter_override.py
> Gracefully handle that a parameter could shadow a class attr

- src/qcodes/dataset/dond/do_nd.py
The overload introduced in #6422 did not correctly match on all instances where either squeeze was not given or a bool. This fixes that
> Fix typeing of dond

- docs/changes/newsfragments/6430.improved_driver
- src/qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
LakeShore335: fix typo in setpoint_ramp parameter group
> LakeShore335: fix typo in setpoint_ramp parameter group

- docs/changes/newsfragments/6439.improved
- pyproject.toml
- src/qcodes/logger/logger.py
This has been deprecated for a while so lets get rid of it.
> Remove opencensus telemetry

- docs/changes/newsfragments/6086.breaking
- docs/examples/DataSet/Offline Plotting Tutorial.ipynb
- src/qcodes/instrument/instrument.py
- src/qcodes/instrument/instrument_base.py
- src/qcodes/instrument_drivers/tektronix/AWG5014.py
- tests/drivers/test_tektronix_AWG5014C.py
- tests/test_instrument.py
Following the discussion in #6080 I think we should consider getting rid of these methods on the instrument classes.
All of this functionality can be done in ways that is more obvious, direct and more frequently used 
E.g. parameter and functions can be looked up from the `parameters` and `functions` delegate attr dicts if you need to look them up dynamically.
> Deprecate convenience methods on Instrument classes

- src/qcodes/instrument/sims/RSSGS100A.yaml
This should enable a mock instrument to be snapshotted without warnings
> Add more parameters to mock RohdeSchwarzSGS100A

- src/qcodes/dataset/data_set_protocol.py
- src/qcodes/dataset/threading.py
- src/qcodes/instrument_drivers/AlazarTech/ats_api.py
- src/qcodes/instrument_drivers/Keithley/Keithley_2450.py
- src/qcodes/instrument_drivers/Keithley/Keithley_7510.py
- src/qcodes/instrument_drivers/Keysight/Infiniium.py
- src/qcodes/instrument_drivers/Keysight/keysight_34934a.py
- src/qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
- src/qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
- src/qcodes/instrument_drivers/QDev/QDac_channels.py
- src/qcodes/instrument_drivers/rigol/Rigol_DG4000.py
- src/qcodes/logger/logger.py
- src/qcodes/metadatable/metadatable_base.py
- src/qcodes/validators/validators.py
Looks like ruff may not always detect this with quoted types
> Replace remaining use of optional / union with 3.10 style

- src/qcodes/extensions/installation.py
Handle that vscode config may contain comments which is not valid JSON
but valid in the json ext that VSCode uses.
> Improve robustness of VSCode config handling

- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/sqlite/queries.py
This is useful in case the user has written the data to a different db that they are trying to load from
> Add some logging for db location and guid

- src/qcodes/instrument/sims/lakeshore_model336.yaml
- src/qcodes/instrument_drivers/Lakeshore/Lakeshore_model_336.py
- src/qcodes/parameters/group_parameter.py
- tests/drivers/test_lakeshore.py
- tests/drivers/test_lakeshore_336.py
- tests/parameter/test_group_parameter.py
This driver update adds parameters to the Lakeshore 336 channel that allows query of the input channel curve header to read from the instrument:
- input_curve_number
- input_curve_name
- input_curve_sn
- input_curve_format
- input_curve_limit
- input_curve_coefficient
This is useful to verify remotely if the correct temperature calibration curve is selected.
> Add curve header parameters to Lakeshore model 336, make group parameter take callable get_cmd

- .github/workflows/docs.yaml
- .github/workflows/pytest.yaml
- pyproject.toml
Filter new warnings.
Requires pr to bump pywin32 to be merged
Still missing release with support for 3.13 for 
(could be disabled)
Other issues
> Mark python 3.13 as supported and test / type check with it

- README.rst
Fixes broken link to qcodes_loop documentation.
> Fix link to `qcodes_loop` docs

- docs/changes/newsfragments/6647.breaking
- docs/start/index.rst
- src/qcodes/__init__.py
- src/qcodes/utils/helpers.py
- src/qcodes/utils/spyder_utils.py
* Stop calling add_to_spyder_UMR_excludelist automatically and deprecate this function.
* Document that users should disable UMR when installing qcodes editable. 
Alternative to #6544
> Stop trying to exclude qcodes from Spyder UMR

- docs/changes/newsfragments/6648.improved
- src/qcodes/parameters/delegate_parameter.py
- src/qcodes/parameters/parameter_base.py
- tests/parameter/test_delegate_parameter.py
This PR fixes a bug observed when chaining multiple DelegateParameters, and changing the source at the bottom of the chain.
In the previous implementation, a DelegateParameter only updated it's internal `_settable` and `_gettable` attributes when the `source` was changed. But it is possible to set up a chain of DelegateParameters and then change the 'root' source Parameter. This updates the bottom-most DelegateParameter, but all of the other DelegateParameters in the chain will not update.
This PR changes the implementation to override the `ParameterBase` implementation of the `gettable` and `settable` properties, so that they reflect the underlying `source` parameter, no matter what it may be.
> DelegateParameters inherit their source's settable/gettable/snapshot_value/unit/label

- .github/workflows/docs.yaml
Now that wrapt 1.17.0 is released we can build docs with 3.13
Lifted from #6494 since this is currently failing.
**Issue is resolved in wrapt 1.17.0rc1 just need to wait for release and we can merge this**
Disabling parallel build does not seem to make a difference.
Disabling the extensions one by one seems to indicate that the docs build error is related to autodocsumm, other debugging points towards viewsource. It may be a combination of these extensions
> Enable building of docs using 3.13

- .github/workflows/pytest.yaml
file has been replaced by files (called the same way since we only upload one file)
> Fix deprecation warning from codecov action

- docs/changes/newsfragments/6671.improved
- src/qcodes/parameters/parameter.py
- src/qcodes/parameters/parameter_base.py
- tests/parameter/test_delegate_parameter.py
**Bug description:**
When a dyno test point is read, it calls external_parameter  which should redirect to its source for the value but instead <function Parameter.__init__.<locals>._get_manual_parameter> is called and 0.0 is returned.
**Cause**
The reason why DelegateParameter doesn't call its source for the value is because of the following lines in Parameter.__init__:
```
elif not self.gettable and get_cmd is not False:
if get_cmd is None:
self.get_raw = MethodType(_get_manual_parameter, self)
```
When external_parameter is created, its source is None so it's not gettable and its get_raw is thus bound to _get_manual_parameter.
**Solution**
It turns out that even though gettable property of DelegateParameter is False when source is None, _gettable attribute is True because `get_raw` is …
> Fix bug: delegate parameter doesn't call its source to get value

- src/qcodes/instrument/instrument_base.py
As noted in #6648 this really should be documented.
> Add note about deprecated methods to docstrings

- pyproject.toml
* Only filter warnings that we actually expect 3th party code to trigger, since many of these have been fixed upstream.
* Rename a ruff rule that has been renamed upstream
> Warnings cleanup

- docs/changes/newsfragments/6722.improved
- src/qcodes/instrument/instrument_base.py
- tests/parameter/test_parameter_registration.py
Closes #6715 
@thangleiter Could you check if this is a reasonable solution
> Fix delegate parameter warning

- docs/changes/newsfragments/6792.improved
- src/qcodes/instrument_drivers/oxford/triton.py
This patch tests if the Triton can communicate with the magnet. If not, parameters pertaining to the magnet are not added to the instrument. This avoids complications when snapshotting the instrument for instance.
Reasons for communication failure are 
1) no magnet is equipped to begin with.
2) the magnet power supply (Mercury iPS) is set up for a different communication protocol (TCP/IP for example).
> Oxford Triton driver: only add magnet parameters if one is present

- docs/examples/index.rst
Remove the repetitive toctree entry to remove repetitive "Logging" entries in the document index.
> Fix repetitive logging document index

- src/qcodes/instrument_drivers/american_magnetics/AMI430.py
- src/qcodes/instrument_drivers/american_magnetics/AMI430_visa.py
- src/qcodes/math_utils/field_vector.py
- src/qcodes/parameters/parameter_base.py
- src/qcodes/parameters/permissive_range.py
- src/qcodes/utils/types.py
In several places code tests variables for numeric type using `isinstance(value, (int, float))`. This creates problems for native numpy types (among others I would presume). For example, `isinstance(np.int32(0), int)` evaluates to false.
Checking instead for `numbers.Real` should resolve this.
> Check for numeric type using numbers.Real

- docs/changes/newsfragments/6585.improved
- src/qcodes/parameters/delegate_parameter.py
- src/qcodes/parameters/parameter_base.py
- tests/dataset/measurement/test_measurement_context_manager.py
- tests/parameter/test_delegate_parameter.py
Extracted from #6832
Add validators from source to DelegateParameter. This ensures that a non numeric DelegateParameter is registred with the correct type in measurements
> Add source validators to delegate parameter validators

- .github/workflows/pytest.yaml
- pyproject.toml
Move configuration of which package to cover to pyproject.toml which makes more sense 
Unfortunately does not silence warnings when using xdist.
> Set coverage config in pyproject.toml

- docs/changes/newsfragments/6889.improved_driver
- src/qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
Added several parameters into the oxford MercuryiPS driver, enabling the control of the heaters and the sensing of internal temperatures (magnet, PT1, and PT2 stage of cryogenic system). The new driver has been tested on a real-world iPS device with only a z-axis magnet and all three temperature sensors.
This pull request includes several updates to the `src/qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py` file, focusing on adding new parameters and a parser function. The most important changes include the addition of a temperature parser function and new parameters for heater switch and temperature readings.
* Added `_temp_parser` function to parse response strings into SI temperature values.
* Added `heater_switch` parameter to manage the heater switch status and settings. The …
> Oxford ips driver new parameters

- .pre-commit-config.yaml
- docs/changes/newsfragments/6919.breaking
- pyproject.toml
- requirements.txt
- setup.py
* Regenerate requirements.txt now that setuptools is no longer a runtime dependency with new versions of towncrier
* Remove legacy setup.py script. This means we don't import setuptools so types-setuptools can be removed
* Upgrade precommit hooks
> Remove setuptools runtime dependency and upgrade precommit hooks

- src/qcodes/logger/logger.py
Avoid private import and use non deprecated run_line_magic
> Add support for ipython9

- .gitmodules
- pyproject.toml
- src/qcodes/instrument_drivers/Minicircuits/USBHIDMixin.py
Pyright now infers types at runtime so this adds little value and risk using out of date stubs
> Remove typing stubs

- docs/changes/newsfragments/6946.breaking
- pyproject.toml
- src/qcodes/__init__.py
- src/qcodes/utils/__init__.py
- src/qcodes/utils/deprecate.py
- src/qcodes/utils/helpers.py
- tests/sphinx_extension/test_parse_parameter_attr.py
- tests/test_deprecate.py
There is no good reason to keep this around and along with https://github.com/microsoft/Qcodes/pull/6942 this will eventually allow us to drop the dependency on wrapt in qcodes
> Deprecate qcodes deprecation utils

- .github/package.json
- pyproject.toml
- src/qcodes/dataset/plotting.py
- src/qcodes/instrument_drivers/rigol/Rigol_DG1062.py
- tests/dataset/measurement/test_measurement_context_manager.py
- tests/drivers/test_ami430.py
- tests/drivers/test_ami430_visa.py
- tests/test_logger.py
- tests/validators/test_enum.py
These rules are standard and quite important so should never have been disabled in the first place.
Also various small cleanups of pytest and ruff settings
> Enable Pyright standard rules

- docs/changes/newsfragments/6942.breaking
- pyproject.toml
- src/qcodes/dataset/__init__.py
- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/data_set_cache.py
- src/qcodes/dataset/data_set_in_memory.py
- src/qcodes/dataset/data_set_info.py
- src/qcodes/dataset/database_extract_runs.py
- src/qcodes/dataset/database_fix_functions.py
- src/qcodes/dataset/dataset_helpers.py
- src/qcodes/dataset/experiment_container.py
- src/qcodes/dataset/experiment_settings.py
- src/qcodes/dataset/measurements.py
- src/qcodes/dataset/sqlite/connection.py
- src/qcodes/dataset/sqlite/database.py
- src/qcodes/dataset/sqlite/db_upgrades/__init__.py
- src/qcodes/dataset/sqlite/db_upgrades/upgrade_2_to_3.py
- src/qcodes/dataset/sqlite/db_upgrades/upgrade_3_to_4.py
- src/qcodes/dataset/sqlite/db_upgrades/upgrade_5_to_6.py
- src/qcodes/dataset/sqlite/db_upgrades/version.py
- src/qcodes/dataset/sqlite/initial_schema.py
- src/qcodes/dataset/sqlite/queries.py
- src/qcodes/dataset/sqlite/query_helpers.py
- tests/dataset/test_database_creation_and_upgrading.py
- tests/dataset/test_dataset_in_memory.py
- tests/dataset/test_guid_helpers.py
- tests/dataset/test_sqlite_connection.py
Newer versions of python makes it possible to subclass sqlite connection.
This will make it possible to drop wrapt as a direct dependency of qcodes
> Replace ConnectionPlus with a subclass of sqlite Connection

- docs/changes/newsfragments/7017.new
- docs/examples/writing_drivers/Creating-Instrument-Drivers.ipynb
- src/qcodes/instrument/instrument_base.py
- src/qcodes/instrument_drivers/Galil/__init__.py
- src/qcodes/instrument_drivers/Galil/dmc_41x3.py
- src/qcodes/instrument_drivers/american_magnetics/AMI430_visa.py
This makes it possible to assign the submodule to an attribute for station completion and documentation. Updated one example with this
> Return submodule from add_submodule

- docs/changes/newsfragments/7065.improved
- src/qcodes/dataset/dond/do_0d.py
- src/qcodes/dataset/dond/do_1d.py
- src/qcodes/dataset/dond/do_nd.py
Will close #7061 together with #7066
> Replace do0d and do1 with a wrapper around dond

- src/qcodes/dataset/descriptions/dependencies.py
Fix incorrect rendering such as
> Fix typo in Raises docstrings

- src/qcodes/instrument_drivers/rohde_schwarz/SGS100A.py
Add units and docstrings for a few parameters of the SGS100 driver.
> Add units and docstring to SGS100 driver

- MANIFEST.in
- pyproject.toml
* Avoid warning by not trying to include missing files in MANIFEST.in
* Adapt license configuration to pep639 to silence warnings from setuptools
* Bump min version of setuptools for building for pep 639 support
> Small build fixes

- docs/changes/newsfragments/7186.improved
- src/qcodes/logger/instrument_logger.py
- tests/test_logger.py
`InstrumentLoggerAdapter` by default discards any information that is added to the LogRecord via extra. This extends the new 3.13 feature to allow the user to add extra information to the messages logged via the `InstrumentLoggerAdapter` regardless of the version of python.
> Allow extra on log messages via InstrumentLogger

- .github/workflows/copilot-setup-steps.yml
E.g. there are warnings that pip cannot install to the global sitepackages dir and falls back to user dir
> Set python version in copilot ci job

- docs/changes/newsfragments/7413.underthehood
- src/qcodes/dataset/exporters/export_to_xarray.py
- tests/dataset/measurement/test_inferred_parameters_fix.py
- tests/dataset/test_dataset_export.py
When the shape is known up front there is no need to go via pandas multi index
TODO
> Export data directly to xarray when shape is known

- docs/changes/newsfragments/4783.readonly
- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/sqlite/database.py
- tests/dataset/test_dataset_basic.py
- tests/dataset/test_sqlite_base.py
Note we probably want to make use of this in lots of places. However, I think its fine to merge this as is and then usage can be improved later. However, at a minimum the following should be done.
> Add basic read only mode to connect

- docs/changes/newsfragments/7344.improved_driver
- docs/changes/newsfragments/7344.new
- docs/examples/driver_examples/Qcodes example with Rohde Schwarz SGS100A.ipynb
- src/qcodes/instrument/sims/RSSGS100A.yaml
- src/qcodes/instrument_drivers/rohde_schwarz/SGS100A.py
- tests/drivers/test_RS_SGS100A.py
This PR brings the capability to change the operation mode in the Rohde & Schwartz SGS100A instrument. The two operation modes the instrument support are:
- NORMal (normal operation mode, default.)
- BBBYpass (bypass operation mode).
When resetting the instrument, the operation mode defaults to NORMal.
> operation mode for SGS100A instrument

- docs/changes/newsfragments/7520.improved
- src/qcodes/instrument/channel.py
- tests/test_autoloadable_channels.py
- tests/test_channels.py
This ensures that the type of the element of the ChannelList can be found correctly (like it can for a ChannelTuple)
To make this works requires changing the types in the AutoLoadable channels classes to match ChannelList/Tuple
> Add generic argument to ChannelList

- docs/changes/newsfragments/7432.breaking
- docs/changes/newsfragments/7432.improved
- src/qcodes/dataset/data_set.py
- src/qcodes/dataset/data_set_cache.py
- src/qcodes/dataset/data_set_in_memory.py
- src/qcodes/dataset/data_set_protocol.py
- src/qcodes/dataset/exporters/export_to_pandas.py
- src/qcodes/dataset/exporters/export_to_xarray.py
- tests/dataset/measurement/test_inferred_parameters_fix.py
- tests/dataset/test_dataset_export.py
Export inferred to and from parameters related to setpoints with the same shape as the setpoints when exporting to xarray and the shape is known. Export inferred related to data parameters as data parameters.
TODO
> Export inferred parameters related to dependencies
