- qcodes/plots/base.py
The config isn't loaded in plots/base.py, resulting in an error upon initialization
- from qcodes import config
> Fix: Import config

- qcodes/loops.py
Previously, when running a loop, the dataset was always set to None before its results were printed. As a result, it always prints None.
- Print dataset before clearing
- Remove print(USE_MP), seems unnecessary
> Fix: print dataset before removing dataset

- qcodes/loops.py
Fixes #389 
- Add a warning if you try to run a background Loop with no DataManager
@peendebak @giulioungaretti
> fix: warn on background Loop without data_manager

- qcodes/tests/test_format.py
FileNotFoundError is not raised, if the directory exists (very much like Linux).
So safer to check for the file we actually want to check for existence.
Closes #407
> fix: Don't append if file does not exist.

- requirements.txt
Trying to figure out whats wrong with travis here https://travis-ci.org/QCoDeS/Qcodes/builds/188466963
seqfault during `setup.py develop`
I can reproduce it locally on OSX and it looks like 
the upgrade of sip from 4.18.1 to 4.19 causes it
So I guess that either sip 4.19 isn’t compatible with pyqt 5.7 but requires pyqt 5.71 but thats not reflected in the dependencies. It may also just be an abi compatibility issues with the binary wheels between the 2 packages. 
This is just restoring previous behaviour. We could also just upgrade pyqt to 5.7.1
> Travis failures

- docs/examples/Qcodes example with Decadac.ipynb
- qcodes/instrument_drivers/Harvard/Decadac.py
Add a parameter to control the Decadac output mode and set its default to ON. Add offset parameters for each channel.
Breaking changes: rename the voltage parameters from volt0, volt1, ... to ch0_voltage, ch1_voltage, ...
Fixes Decadac output mode problem.
- Add important Decadac parameters.
@nataliejpg @giulioungaretti
> fix: Fix Decadac output off problem

- qcodes/data/data_set.py
- qcodes/data/format.py
- qcodes/instrument/base.py
- qcodes/tests/data_mocks.py
- For the `write_copy` function the formatter should always write the data.
- Better debugging output for instruments being pickled
@unga @core
> Fix write_copy

- docs/examples/Measure without a Loop.ipynb
- docs/examples/toymodel.py
- qcodes/data/data_set.py
- qcodes/instrument/mock.py
- qcodes/tests/test_loop.py
fixes #380 by avoiding to overwrite data
with partial data from disk
- Make sync a no opt in local mode rather than read data from disc
I don't think that sync has any function in local mode but if that is too intrusive https://github.com/jenshnielsen/Qcodes/commit/fd2b0d3859627d882a9986f7aa453b980e60a9c6 is a less intrusive fix
@giulioungaretti @nataliejpg
> fix: make sync a no-opt on local data

- docs/user/configuration.rst
It should be relative to the location of the rst file, Currently missing here http://qcodes.github.io/Qcodes/user/configuration.html#default-config
> Docs fix link to json shema

- qcodes/instrument/parameter.py
Remove the warning when a val_mapping is set for a StandardParameter.
Fixes issue 469
- Remove said warning from instrument/parameters.py
> fix: remove parameter warning icw val_mapping

- qcodes/instrument/base.py
Fixes #391 
- Add a print_readable_snapshot to the base instrument class 
@nulinspiratie, I think you said you liked this. 
Below two pictures to compare the conventional snapshot and the readable version. 
Note that the readable snapshot is not intended to replace the existing snapshot function.
> Added print human readable snapshot to base instrument class

- qcodes/loops.py
Closes #504
-  log exception in background task
-  exit loop 
@alan-geller , and @QCoDeS/core  the question here is if we want to exit (early return) or not.
My feeling is that we may as well not exit, technically the data could be still good even if the background task failed, but one never knows.
The clean way is to return, but I am curious about your 💎  feedback    !
> fix: Log exception and exit

- qcodes/plots/base.py
- qcodes/plots/pyqtgraph.py
- qcodes/plots/qcmatplotlib.py
Use units for plotting. Pyqtgraph uses units in a clever way! 
Needs #494  to be 100% great.
> feature: Use unit in label

- qcodes/instrument_drivers/AlazarTech/ATS.py
The AlazarParameter were non serializable because an explicit reference was stored.
The way that baseparameter works, now only the name is stored.
Fixes #503 
@jenshnielsen
> Make ATS instrument serializable

- qcodes/instrument/parameter.py
- qcodes/loops.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_loop.py
- qcodes/tests/test_measure.py
@QCoDeS/core 
This replaces #500 #501 and #502 
Simpler to do in one as the tests are strongly coupled
> Multiparameter fixes

- qcodes/instrument/base.py
Fixes #517 .
@unga @AdriaanRol
> remove warning for get_idn, add default value

- qcodes/plots/qcmatplotlib.py
@QCoDeS/core 
Following the merge of #495 trying to do multiple lineplots with matplotlib as in 
```python
plot = qc.MatPlot()
plot.add(data.this)
plot.add(data.that)
```
results in labels such as "None (None)" on both axes. This is because axsetter is called with the string "None (None)" the same issue does not exist for pyqtgraph as it directly supports units and
setLabel is called as `setLabel(None, None)` which is simply interpreted as a noop 
This pr restores matching behaviour to matplot
> Fix: restore handling of labels on multi line plots in matplot

- qcodes/instrument_drivers/devices.py
Else it would crash with the metadata as the instrument object  is made no pickable by the old multiprocessing madness.
> fix: Remove obj ref from metadata

- qcodes/instrument_drivers/american_magnetics/AMI430.py
change all string comparisons to int comparisons
Fixes #524 .
- compare int based values instead of string based values
@Rubenknex
> Fixes to AMI430 driver

- qcodes/instrument_drivers/tektronix/Keithley_2700.py
@giulioungaretti @jenshnielsen @WilliamHPNielsen
> rename units to unit; remove commented out code

- qcodes/instrument_drivers/american_magnetics/AMI430.py
pause not working suspected target is write_confirmation
By removing the write_confirmation, pausing the magnet now works.
The magnet does not seem to give a confirmation after a write
@Rubenknex
> Fixes to AMI430 driver, write confirmation

- qcodes/instrument_drivers/tektronix/AWG5014.py
One missing units -> unit transition in the awg driver. Spotted during our work with the alazar driver
> Fix: awg5014 missing units

- qcodes/instrument_drivers/tektronix/Keithley_2600.py
Fixes #530.
- Fix parsing of output and mode 
- minor adjust style
@core
> fix: Keithley mode and output parser

- docs/examples/Qcodes example with Keysight 33500B.ipynb
- qcodes/instrument_drivers/Keysight/Keysight_33500B.py
Add a driver and a notebook.
Fixes the fact that we don't have a driver
Made in an extreme hurry for a fast measurement
> driver: Keysight 33500B

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
Fixes garbage data on ZI 
@WilliamHPNielsen @jana-d fixes what we spent most of friday debugging
> Fix: zi ensure single trigger mode is always set

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
The issue with changing number of segments seems to be that old data may be returned along with the new data. Clear data to ensure that this can not happen.
> ZI: clear history when reusing scope

- docs/examples/Agilent 34411A versus Keysight 34465A.ipynb
- docs/examples/benchmarking/Agilent 34411A versus Keysight 34465A.ipynb
- qcodes/instrument_drivers/Keysight/Keysight_34465A.py
- Keysight DMM driver with data_buffer parameter
@jenshnielsen
> Driver/Keysight DMM

- qcodes/instrument_drivers/oxford/mercuryiPS.py
Some small issues found while working with the code on T10
@MerlinSmiles @QCoDeS/core
> Mercury fixes

- qcodes/instrument_drivers/oxford/triton.py
@MerlinSmiles I think this is mainly your driver does this make sense to you?
> Triton fixes

- qcodes/instrument_drivers/QuTech/IVVI.py
- Add locks to the IVVI driver
The locking is optional, so without enabling them the behaviour of the driver is unchanged. The locks are needed for safety of our systems (otherwise we could have set random values to the DACs).
@giulioungaretti @AdriaanRol @WilliamHPNielsen @jenshnielsen
> Add locking to IVVI driver

- qcodes/instrument_drivers/Keysight/Keysight_33500B.py
Make the driver print the connect_message. Also add a bare minimum of docstrings.
- The driver now prints a connect message upon connecting
> fix: Make driver print connect_message

- qcodes/instrument_drivers/tektronix/AWG5014.py
Add a float('inf') mapping to the .awg-file maker.
@jenshnielsen
> fix: Correctly translate float('inf')

- qcodes/instrument_drivers/oxford/triton.py
- qcodes/utils/validators.py
@MerlinSmiles  As far as I can see this call to `_get_control_channel` would always return the previous channel (since force defaults to True now) We can either do like this or explicitly call `_get_control_channel`  with `Force=False` Does this make sense to you?
> fix: Triton: Don't read existing channel

- qcodes/utils/helpers.py
Changes proposed in this pull request
- Adds optionality for an object to have a custom JSON encoder. The encoder checks if the object has a method _JSONencoder. If it does, this method is used to generate a JSON dict.
> Feat: Jsonencoder addition

- .travis.yml
- docs_requirements.txt
- test_requirements.txt
* Split dependencies out from travis file so they are easier to install locally
* When building from a pr build the actual pr docs rather than the master docs so we can verify these from the travis logs
> Small tweaks to docs build

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
When making the sweeper setpoints, the wrong value was used to check for linear mapping.
- Fix the aforementioned problem.
@jenshnielsen
> driver/ fix wrong comparison for xmapping

- qcodes/instrument/parameter.py
- qcodes/tests/test_instrument.py
Note that this PR replaces #325 because the older branch disappeared
If a parameter contains a large amount of data, such as a trace acquisition parameter, it is often undesirable to save a full trace of data when creating a snapshot. Therefore I have added a snapshot_value kwarg to the Parameter init that can remove the parameter's 'value' from a snapshot.
Note that this is not achieved when providing the kwarg snapshot_get=False, since this only stops the parameter from performing a get when a snapshot is created.
Add snapshot_value to the Parameter init kwargs.
If param.snapshot() is called, and param._snapshot_value==False, remove 'value' from the state dictionary.
If param.snapshot() is called and snapshot_value==False, do not perform a …
> feat: parameter snapshot_value (recreated)

- qcodes/instrument_drivers/Harvard/Decadac.py
This broke the docs build because it's not importable. Noticed because the tutorial was not updated.
> Fix: typos in decadac driver

- qcodes/plots/qcmatplotlib.py
Fixes #609.
The add plot api assumes that `self.subplots` is always a 1d array, However the array returned from `plt.subplots` dimensionality depends of the number of subplots (unless squeeze=False) The code correctly handled the 1d case but not the 2d. This should handle all 3 cases
> Fix: Handle 2d subplot arrays from pyplot.subplots

- docs/examples/driver_examples/Qcodes example with TPS2012.ipynb
Make the headers in the TPS2012 example notebook more uniform.
- Add a headline to the example notebook. This should make the autgenerated docs more readable.
@jenshnielsen
> docs: Give TPS2012 example a headline

- qcodes/tests/test_instrument.py
New versions of pytest (3.1) prints warnings per default so this allows us to get rid of some output 
from the test runner 
```
================================================================================================================ warnings summary ================================================================================================================
qcodes/tests/test_instrument.py::TestInstrument::test_snapshot_value
/Users/jhn/src/Qcodes/qcodes/tests/test_instrument.py:111: DeprecationWarning: Please use assertEqual instead.
snapshot['parameters']['has_snapshot_value']['value'])
-- Docs: http://doc.pytest.org/en/latest/warnings.html
```
> AssertEquals has long been deprecated and replaced by AssertEqual

- qcodes/instrument_drivers/devices.py
This makes it possible to add a voltage divider to an instrument (subclass)
with `add_parameter` and then get snapshotted correctly as in 
```
class DUMMYDACVD(DummyInstrument):
"""
A DummyDac with a voltage divider
"""
def __init__(self, name, gates, **kwargs):
super().__init__(name, gates, **kwargs)
topo_channel = self.parameters['ch1']
self.add_parameter('topo_bias',
parameter_class=VoltageDivider,
v1=topo_channel,
division_value=10)
```
which includes the VoltageDivider in the snapshot of the instrument
rather than the current pattern on t10
```
class DUMMYDACVD(DummyInstrument):
"""
A DummyDac with a voltage divider
"""
def __init__(self, name, gates, **kwargs):
super().__init__(name, gates, **kwargs)
topo_channel = self.parameters['ch1']
self.topo_bias = …
```
> Fix: make voltage divider take an instrument

- qcodes/tests/test_validators.py
- qcodes/utils/validators.py
- A validator for callable objects
- includes tests 
> Validator for callables as parameter

- qcodes/plots/qcmatplotlib.py
Fixes #257, and replaces #337 since that branch was deleted.  Also includes fixes proposed in #615.
- Interpolation of x and y coords in pcolormesh. Previously, MatPlot used to ignore edgepoints.This is because MatPlot treats the x and y values as grid corners instead of grid centers. This also resulted in data points being shifted by half a grid. Now the x and y values are transformed to grid corners (which increases their arrays by 1). Doing this allows the edgepoints to be included as well. If the array only contains one element, the grid size cannot yet be determined, and defaults to 1. This also works with non-equidistant setpoints.
- Args passed in initial instance creation are treated as data that should be plotted on individual subplots. This …
> feat: MatPlot updates (Updated version of #337)

- qcodes/utils/slack.py
@nulinspiratie I could not find a proper branch in your repo to make a PR against. 
@giulioungaretti @jenshnielsen
> Add help command, add fix for new users

- qcodes/instrument_drivers/stanford_research/SR830.py
Fixes the fact that author of the buffer parameters had not anticipated that anyone would acquire data with triggered acquisition
- Take care of the triggered case
@jenshnielsen
> fix: Don't break setpoint in case of trigger

- qcodes/instrument_drivers/tektronix/AWG5014.py
`pack_waveform` in `Tektronix_AWG5014` uses Python native functions like `min`, `max` and `count`,
which are slow compared to the numpy alternatives. This update replaces the Python function calls
with numpy alternatives considerably improving the speed of programming the Tektronix AWG5014
while leaving the functionality the same.
As an example, on my machine:
```
> data = np.random.choice([0, 1], 10000)
> %timeit list(data).count(0) + list(data).count(1) == len(data)
100 loops, best of 3: 5.23 ms per loop
> %timeit np.all(np.in1d(data, np.array([0, 1])))
The slowest run took 9.76 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 70.3 µs per loop
```
- Change native Python functions in …
> perf: Improve Tektronix_AWG5014 performance

- qcodes/config/qcodesrc.json
- qcodes/config/qcodesrc_schema.json
- qcodes/plots/pyqtgraph.py
Fixes #647 
Currently pyqt graph plots may close spontaneously if you don't keep a reference to the plot around. This creates a deque as a Class parameter in QtPlot that automatically keeps the last n (default 100) plots in reference. The number of plots to keep can be configured. In my tests 100 plots of a (100,100) heatmap is roughly 1 GB of memory so this should be safe enough
Currently on top of #661 so that should be merged first
@QCoDeS/core
> Pyqtgraph automatically store ref to the last 100 plots (configurable)

- qcodes/utils/slack.py
Sometimes the slack bot generates an error due to a network timeout. This PR prevents this from happening by catching a timeout error.
@giulioungaretti @nulinspiratie
> add catch for network timeouts

- qcodes/loops.py
- qcodes/tests/test_combined_loop.py
- qcodes/tests/test_combined_par.py
Fixes #669 
The issue is that the base parameters within the combined parameter were being looked up from an index that always starts at 1. This is only true if there is only one parameter/task being measured/executed within the loop. This corrects the counting
> Correctly count number of actions when updating combined measurements

- qcodes/utils/slack.py
@WilliamHPNielsen @jenshnielsen @nulinspiratie
> add one more exception to the catch in slack module

- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
-  makes setpoint_names of FrequencySweep parameter not have any spaces in because this prevents ability to load back datasets (among other things)
@jenshnielsen
> Fix ZNB space in setpoint names

- qcodes/instrument/base.py
- qcodes/instrument/visa.py
- qcodes/instrument_drivers/QDev/QDac.py
- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/utils/metadata.py
This significantly speeds up the qdac snapshotting such as when adding it to a station. This is done by using _get_status to read parameters at once rather than one by one. 
My benchmark shows 
Creating a station with a QDac. Before 30 s, with this change 0.5 s without updating currents.
Updating currents adds about another 11 seconds both to the instrument creation and snapshot
> Speedup qdac snapshot

- qcodes/instrument_drivers/Spectrum/M4i.py
If memsizes are not a multiple of 16 the card will go into error mode. The behavious is the same for cases where the size was already a multiple of 16.
@jenshnielsen
> make sure memsizes for M4i card are multiples of 16

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
Otherwise an interrupt will result in a scope left in the middle of a scope acquisition which cannot be closed or reused
> ZI Wrap scope in try finally to fix interrupt

- qcodes/instrument/base.py
This log the failure and continue, fixes #691
There are lots of parameters that you may not be able to snapshot cleanly and typically it makes little sense to do so
> Snapshot(update=True) may fail for array parameters and such

- docs/examples/benchmarking/Benchmark of Keysight DMM software trigger vs set-get.ipynb
- qcodes/instrument_drivers/Keysight/Keysight_34465A.py
Relates to #720 
- Add a notebook benchmarking the use of software triggers for the Keysight DMM
- Minor driver improvements 
@jenshnielsen
> Benchmark - Keysight DMM software trigger

- qcodes/instrument_drivers/QDev/QDac.py
- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/instrument_drivers/stanford_research/SR830.py
* add support for faster setting of qdac voltage
* add option to qdac to ignore return read on voltage set
* SR830 fail early in buffered readout if butffer is not full as expected
> Faster qdac (#53)

- qcodes/instrument_drivers/QDev/QDac_channels.py
As suggested by @WilliamHPNielsen 
Rather than disabling the second write this concatenates the commands and counts the numbers 
of reads to perform afterwards.
Both the new and old way has the same speedup from 32 to 16 ms for a single set command
> Smarter way of speeding up qdac

- qcodes/instrument/ip.py
As I understand it that is a sign of a closed socket
This should probably be an error in the future
Also use sendall to ensure that we dont drop data. Fixes #748
> Fix: ip instrument log empty responce and ensure all data is send

- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
They are slow and may not even function correctly if the trigger is not set and there is no point of snapshotting array parameters
> ZNB don't snapshot traces

- qcodes/instrument/visa.py
Add a new parameter in VisaInstrument class to perform 'device clear' (default True, so current behavior is retained). Some instruments react badly to a device clear (Rigol DS4000 serie scopes, for example, see here: https://forums.ni.com/t5/Instrument-Control-GPIB-Serial/RIGOL-DS2072-USB-NI-VISA-Initialization-Error/td-p/2554657 ), so this pull request make it optional.
> Make 'device clear' optional in VisaInstrument initialization

- qcodes/actions.py
- qcodes/tests/test_threading.py
Fixes #621, to some extent
- Raise an exception if users try to multi-thread read several values from one instrument
- Add a simple test for the exception
@jenshnielsen
> fix: protect threading users against clutter

- environment.yml
The h5py dependency was pinned to a fixed version. Thus numpy won't update as it depends on it.
found by
@jenshnielsen
> unpin h5py dependency

- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/Harvard/Decadac.py
- qcodes/instrument_drivers/QDev/QDac.py
- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/instrument_drivers/QuTech/IVVI.py
- qcodes/instrument_drivers/Spectrum/M4i.py
- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/devices.py
- qcodes/instrument_drivers/ithaco/Ithaco_1211.py
- qcodes/instrument_drivers/oxford/mercuryiPS.py
- qcodes/instrument_drivers/signal_hound/USB_SA124B.py
- qcodes/instrument_drivers/stanford_research/SIM928.py
- qcodes/instrument_drivers/stanford_research/SR560.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_channels.py
- qcodes/tests/test_combined_loop.py
- qcodes/tests/test_instrument.py
- qcodes/tests/test_loop.py
- qcodes/tests/test_measure.py
- qcodes/tests/test_parameter.py
- qcodes/tests/test_sweep_values.py
Fixes a number of warnings following the merge of #600
> Fix parameter warnings

- qcodes/tests/test_helpers.py
I have seen this failing frequently on windows but seems less common on other platforms including travis(linux)
Add a tiny offset as this test may fail if otherwise if the two calls to perf_counter are close enough to return the same result as a + b - a cannot in general be assumed to be <= b in floating point math (here a is perf_counter() and b is the wait time)
> make wait time test more robust

- qcodes/instrument_drivers/Keysight/KeysightAgilent_33XXX.py
- qcodes/instrument_drivers/Keysight/Keysight_33500B.py
- qcodes/instrument_drivers/Keysight/Keysight_33500B_channels.py
- qcodes/instrument_drivers/agilent/HP33210A.py
Since these instruments basically have not changed through three vendors (and at least one decade), they might as well have a common driver. This will also allow for seamless exchange of one unit with another.
- Add GUD
I have not yet put in deprecation warnings nor created shim drivers pointing to this one. I'll do so if everyone likes the idea.
@jenshnielsen
> driver: Add GUD for Keysight/Agilent/HP wfm gens

- qcodes/instrument_drivers/oxford/mercuryiPS.py
As requested by t10 @WilliamHPNielsen
> Mercury when aborting a ramp switch the magnet to hold

- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/Keysight/Infiniium.py
- qcodes/instrument_drivers/ithaco/Ithaco_1211.py
- qcodes/instrument_drivers/oxford/mercuryiPS.py
- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
- qcodes/instrument_drivers/stanford_research/SR560.py
- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
- qcodes/tests/test_parameter.py
This is an alternative to #797 works by disabling snapshot storage for Array and Multiparamters by default
Pro this 
* we retain the wrappers including delays etc for all parameters:
Against
* This is an still an api break. (Array/Multi)Parameters that used to do explicit _saveval will no longer  be snapshotted unless they explicitly pass snapshot_value=True to the super class constructor, I have verified that this is the case for all current QCoDeS drivers.
* If you don't want the wrappers in any _BaseParameter subclass you will have to replace them in your subclass with a noop
@WilliamHPNielsen  @nulinspiratie
> Don't snapshot array and multiparameters per default

- qcodes/plots/qcmatplotlib.py
X and Y arguments to pcolormesh have never been allowed to be masked
but it worked by coincidence with older versions 
@WilliamHPNielsen @Dominik-Vogel
> Fix matplotlib 2.1 compatibility

- qcodes/instrument_drivers/QuTech/IVVI.py
> fix arguments of IVVI driver

- .travis.yml
As suggested by @AdriaanRol  Currently on top of #805
> Travis run plot tests

- qcodes/data/data_set.py
- qcodes/data/format.py
- qcodes/data/gnuplot_format.py
- qcodes/data/hdf5_format.py
- qcodes/loops.py
- qcodes/tests/test_loop.py
Fixes #821 
- Add more `log.debug` to the data saving process
- Make the `qc.Loop`'s final writing of data more robust
@jenshnielsen @sohailc
> add debugging and make the final write more robust

- qcodes/measure.py
This is a convenience function to get the data set directly from a Measure object, without going through the dummy loop. It is needed to remove the qcodes-dk dependencies
> Measure: get_data_set

- qcodes/instrument_drivers/Harvard/Decadac.py
I want to add this class variable so that the implementation of the customized driver (eg. T3) becomes easier.
> added slot_mode_default to decadac channel

- qcodes/instrument/base.py
If a parameter does not have a value in the snapshot (e.g. because it is an ArrayParameter), the `print_readable_snapshot` function can not iterate through all parameters and values. This PR fixes that.
- Make `print_readable_snapshot` handle missing values
@jenshnielsen @AdriaanRol
> make print_readable_snapshot work with value-less parameters

- qcodes/instrument_drivers/QuTech/IVVI.py
@AdriaanRol @CJvanDiepen 
With the new Parameter updates in qcodes the IVVI driver `adjust_parameter_validator` function stopped working.
@jenshnielsen @WilliamHPNielsen You might want to check other drivers on the usage of `_vals` as well.
> fix IVVI driver

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
- Use latest value in get_ramp_value as starting value
After switching the order of scaling and ramping (#788), the starting value should no longer be the raw value, but the scaled value.
> fix: use latest value instead of raw value in ramp

- docs_requirements.txt
- requirements.txt
- setup.py
Fixes #863 #750 and bumps numpy and pyqt/sip to latest bug fix releases @QCoDeS/core
> Requirements cleanup

- qcodes/data/data_set.py
- qcodes/data/gnuplot_format.py
Allow users to save multiple files with a custom filename to a single
folder containing no snapshots
- Hack in kwargs `filename` and `write_metadata` 
@jenshnielsen
> feat: make gnuplot dataset writing more flexible

- qcodes/instrument_drivers/yokogawa/GS200.py
Running mypy in #824 over the GS200 driver found a few issues. Most are unimportant but there is a missing * in the kwargs forwarding to the VisaInstrument class that could be important.
@QCoDeS/core @spauka
> Fix type annotation in gs200

- qcodes/utils/validators.py
- Add allowed_keys kwarg to dict validator. If not None, the validator will raise an error if the proposed new dict contains keys not in allowed_keys.
> feat: add allowed_keys to dict validator

- docs/start/index.rst
An updated documentation for getting everybody started.
Created with @jenshnielsen and @WilliamHPNielsen
> New documentation for getting started

- qcodes/instrument_drivers/QuTech/D5a.py
use the correct validator ranges (-4 to 4 and -2 to 2, cf. d5a driver) and adjust naming
@peendebak @jenshnielsen
> Correct dac validators

- qcodes/utils/magic.py
@nulinspiratie, how many times do I have to tell you this?! 😛 
Merging PR #723 broke everything. Travis is not using IPython, so he didn't notice. Perhaps we should have a dedicated IPython test?
- Remove python 3.6 f-strings from `magic.py` 
@QCoDeS/core
> remove f-strings

- qcodes/.coveragerc
- qcodes/instrument/sims/Keysight_33xxx.yaml
- qcodes/instrument/sims/RTO_1000.yaml
- qcodes/tests/drivers/test_Keysight_33XXX.py
- qcodes/tests/drivers/test_rto_1000.py
Mainly because I wanted to experiment with the pyvisa sim backend
This also changes the blacklisting of driver from code coverage to not include the drivers that actually have tests
> Add tests for Keysight_33XXX 

- qcodes/instrument_drivers/stanford_research/SR830.py
- qcodes/instrument_drivers/stanford_research/SR86x.py
Replaces all set_validator calls in the SRS instruments with directs sets of self.vals
Fixes #950.
- Replace references to `set_validator` with direct sets of `self.vals`
@jenshnielsen
> Remove references to deprecated set_validator in SRS instruments

- qcodes/instrument/base.py
IPInstrument base class does not have an _instance
attribute.
Fixes #948.
- Add getattr to remove_instance to provide an empty list for instruments that don't supply a _instance attribute
@jenshnielsen
> Fix AttributeError in remove_instance for IPInstruments

- qcodes/instrument/sims/AMI430.yaml
- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/tests/drivers/test_ami430.py
Fixes #952, #953.
In addition, adds a switch heater submodule that allows for setting of SwitchHeater parameters.
- Allows the AMI430 to be operated with ramp rates specified in minutes, allows field units in kiloGauss.
- Adds an instrument specific exception for instrument errors (i.e. allows us to differentiate why ramps may have failed between validation errors and instrument state)
- Fixes bug in current_ramp_limit code that prevents user from setting a limit higher than 0.6A/s
- Allows user to set `field_ramp_limit`, `field_rating` in instrument units, rather than having to convert to Amps.
- Adds `AMI430_SwitchHeater` submodule that allows configuration of switch heater parameters.
- Removes duplicated code between `set_field`, `_set_field` and …
> Driver/ami430 allow all units & fix warnings as exceptions

- qcodes/plots/base.py
- qcodes/plots/pyqtgraph.py
- qcodes/plots/qcmatplotlib.py
- qcodes/tests/test_plots.py
- Return plot handle for `MatPlot` and `QTPlot`. This can then be used for changes later on, such as legends.
@WilliamHPNielsen @jenshnielsen
> feat: return plot handle

- qcodes/instrument_drivers/QDev/QDac_channels.py
All drivers should pass on kwargs to the instrument/VisaInstrument class.
For example if one wants to use the simulation backend one has to use the visalib kwarg. As of now this is not possible for the QDac
> added kwargs to init of QDac

- .travis.yml
- test_requirements.txt
We need 1.7 to fix issues with forward references
> Use beta release of sphinx rather than a custom tag

- qcodes/instrument_drivers/Harvard/Decadac.py
The current Decadac driver does not specify the value of _VERSA_EEPROM_available by default. It is only set to false if the feature is unavailable but never gets set to True. In this PR I set it to False by default instead of inserting the probably missing assignment of True, in order to prevent inserting a so far untested and also not missed feature.
> Setting _VERSA_EEPROM_available to False by default

- .travis.yml
there seems to be issues with 1.7.0 and apidoc not working correctly see #968
> Pin sphinx to 1.7.0b2

- qcodes/instrument_drivers/Spectrum/M4i.py
This PR does the following:
- Allows the `blockavg_hardware_trigger_acquisition` to use `naverages=1`
- Add functions to start data acquisition and retrieve data independently (all functions so far combined these two). Any suggestions for the names `start_acquisition` and `retrieve_data` are welcome.
- Put common code into `_transfer_buffer_numpy`
> Spectrum M4i: improve blockavg functionality and add acquisition functions

- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_dataset_basic.py
As pointed out by @sohailc 
- Make paramspecs have their `inferred_from` parameters retrieved correctly
- Add a test that didn't pass before this fix
@jenshnielsen
> Fix incorrect inferred_from retrieval

- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/tests/drivers/test_ami430.py
Hopefully fixes Travis failing 
We change the warning to be ami specific and only capture that
We have to rewrite the checking code because exeinfo will contain data for all warnings
not just the captured ones so use the context manager instead to to the check
> Fix tests for pyvisa19

- .travis.yml
This prevents the dependency on pyvisa-sim in test_requirements.txt from upgrading pyvisa regardless of the fact that we pinned the version in requirements.txt
> Travis only upgrade if needed

- test_requirements.txt
The bug in coverage 4.5.0 should be fixed in 4.5.1, see https://bitbucket.org/ned/coveragepy/issues/638/run-omit-is-ignored-since-45
@QCoDeS/core
> Unpin coverage

- environment.yml
- setup.py
Fixes annoying warning at the start of qcodes sessions
> limit numpy to 1.13.x until h5py is compatible with 1.14

- qcodes/utils/deferred_operations.py
The `DeferredOperations` allow to postpone the calculation with parameters to a later stage, so that expressions that depend on parameters can be formed and evaluated with the value of the parameter at evaluation time.
This is problematic especially for the __eq__ operator. With a deferred identity comparison, parameters can e.g. not be removed from a list.
Here we remove the creation of a deferred operation on identity comparison. I cannot think of any application, but this PR has to be taken with caution as it affects the code in so many places.
> Make comparison of parameters not deferred

- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/instrument/parameter.py
- qcodes/tests/test_channels.py
This PR adds a get_root_instrument method to InstrumentBase, InstrumentChannel, and _BaseParameter.
as of now channels are treated as instruments that have a parent. To find the actual instrument a parameter in a channel belongs to, one has to iterate up until one finds an instrument that is not a channel.
With this PR one simply gets this root experiment with the added function.
>  add root_instrument property

- qcodes/monitor/monitor.py
Should make it compatible with the latest release of websockets python package and fixes issues with restarting the monitor
@Dominik-Vogel
> Simplify monitor websocket use

- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
This was missed when converting from non channel version that injects this in  a different way. Matches V and I
> add missing channel to keithley 2600 resistance 

- qcodes/monitor/monitor.py
@Dominik-Vogel This should mitigate issues such as #1008 if for some reason the monitor was not closed correctly earlier.
> make the monitor not crash qcodes if the socket cannot be bound

- qcodes/dataset/sqlite_base.py
- qcodes/instrument_drivers/Spectrum/pyspcm.py
Ignore an issue in the bundled pyscm code and work around an issue with typing of sqlite3
See https://github.com/python/mypy/issues/4916
@QCoDeS/core
> Support mypy 0.590

- qcodes/actions.py
Otherwise this triggers the warning because it's at Class level so the warning is displayed as soon as this module is imported. @QCoDeS/core
> `is_function` has moved so don't import from deprecated module

- docs/examples/DataSet/subscriber json exporter.ipynb
- qcodes/dataset/data_set.py
Fixes https://github.com/QCoDeS/Qcodes/issues/1057
the hash function may return the same hash for two subs created just after each other due to the low resolution of time.time. Rather than fixing this by adding extra entropy from a random number i suggest using the python uuid module 
> Use uuid over homegrown function

- .appveyor.yml
- .travis.yml
This is an issue with the new MyPy 0.600
> MyPy: We don't cleanly pass strict optional so disable that for now

- qcodes/instrument_drivers/stanford_research/SR86x.py
Fixes #1114 .
- Change validator in `SR86x.py` to allow 0 amplitude.
@jenshnielsen
> Allow SR86x amplitude to be zero.

- qcodes/tests/dataset/test_measurement_context_manager.py
Partially fixes #1124 
The test for subscriptions for the dataset is not stable, which means that it occasionally passes. This pull-request makes the test stable by actually making it more explicit.
The test essentially checks whether subscribers get executed at the moment the data is flushed to the database. In order to test it, two subscribers are created, data is added in a loop, and assertions are performed in the same loop. Since data is flushed to the database only once within a write_period, the original code uses sleep method next to the call to add_result, where the sleep time is set to 120% of the write_period - this way the test "ensures" that the data is flushed to the database (hence, subscribers are called) and assertions can validly be performed.
The problem of this …
> qcodes-1124 Add explicit flushing to avoid instability of testing

- qcodes/instrument/base.py
In this special case it's better to catch catch bare exceptions since this is tear down code and any exception will stop closing the rest of the instruments
@QCoDeS/core
> Close_all catch all exceptions and log them

- qcodes/dataset/measurements.py
- qcodes/instrument/parameter.py
- qcodes/tests/dataset/test_measurement_context_manager.py
@WilliamHPNielsen Fixes an inconsistency between add_parameter and the register_parameter for ArrayParameters. At the one uses the name of the root instrument but the other users the full name. This fails for an arrayparameter inside a channel since one name will contain the name of the channel but the other one does not.
> make register_parameter match add_result for array_parameter

- qcodes/instrument/channel.py
- qcodes/tests/test_channels.py
We are currently calling channellists for measurements with alazar and VNA. Sometimes one wants to take data from only a subset of the channels in the channellists however currently one can only choose slices or a single channel.
This PR allows one to take data from a subset of a channellist defined by a tuple (e.g. alazar_ctrl.channels[2,4,6].data).
- Add functionality for channellist __getitem__ to allow for a tuple in addition to int and slice.
@jenshnielsen
> Allow tuple selection for ChannelLists

- qcodes/instrument/ip.py
Loglevel `info` for send/recv commands completely floods logfile when using ip instruments. Propose to change level to debug.
- Change loglevel for send/recv of ip instruments from info to debug.
@Dominik-Vogel
> Change loglevel for send/recv in ip.py

- qcodes/instrument_drivers/stanford_research/SR830.py
... and get rid of the corresponding warning
@WilliamHPNielsen @jenshnielsen
> apply get_raw recommendation SR830 driver

- qcodes/instrument_drivers/Spectrum/M4i.py
`active_channels` was not returning the correct channels (because `bool('0')` is true and incorrect order)
@peendebak @WilliamHPNielsen
> bugfix spectrum digitizer driver

- qcodes/instrument_drivers/Keysight/Keysight_N5183B.py
- qcodes/instrument_drivers/Keysight/N51x1.py
Added support for the Agilent/Keysight N5183B Signal Generator.
Fixed a string type error as well in val_mapping.
The set_cmd has the formatting of a string, so I changed the val_mapping to a string.
```
set_cmd='OUTP:STAT ' + '{:s}'
```
Additionally this device doesn't really match the model number of the previous devices, but it's effectively the same.  I leaned toward adding it despite the name not matching exactly vs creating a whole new driver which would just be a copy of the original with a very slight name change.
> Added support for N5183B Signal Generator

- test_requirements.txt
@QCoDeS/core this should unbreak travis and appveyor
> pin hypothesis to less than 3.62 which adds problematic typehints

- qcodes/dataset/data_set.py
- qcodes/dataset/measurements.py
- qcodes/tests/common.py
- qcodes/tests/dataset/test_measurement_context_manager.py
Fixes #1124 - flaky tests for subscribers. Now with much more assurance than in previous PR.
TL;DR - The reason for the tests being flaky in short is: upon exit of the Runner context manager, the subscribers may get unsubscribed *before* their internal queue is exhausted (e.g. callbacks are executed on *all* the saved data points). This happens when the CPU is too busy.
I was able to reproduce the failure when I was running the flaky test `test_subscriptions_getting_all_points` and watching a 4K video on YouTube while adjusting its playback speed (to make CPU even busier). Then I analyzed the logs which SQL debugging spits out, and I found that the subscriber's callback is not called on the very last data point.
The reason for that is that the subscriber may get unsubscribed *before* the …
> Fix flaky subscriber tests

- qcodes/tests/test_channels.py
Appveyor can be really slow for these tests
Failed in https://ci.appveyor.com/project/WilliamHPNielsen/qcodes/build/1.0.549 as part of https://github.com/QCoDeS/Qcodes/pull/1164
> Increase timeout for test_nested_loop_over_channels

- qcodes/dataset/plotting.py
Fixes a minor bug in the `plot_by_id` function of the new dataset: if the data has more than 3 dimenstions, a warning is given; so the bug was in the line of code that generates the warning - references to `data` dict object and its properties were incorrect.
@jenshnielsen
> Fix bugs in warning message

- qcodes/instrument/base.py
This makes it much easier to identify the relevant parameter when adding multiple instruments in a startup script.
> Log the instrument that a failed parameter update comes from.

- qcodes/instrument_drivers/tektronix/Keithley_2400.py
In the Keithley 2400 doing a read with output disabled is an error that leaves the instrument in a state where no commands can be sent to it without restart
To overcome this we check that output is on before doing a read. If not we return 'nan' as a result
Fixes #1149
> Keithley 2400 protect read commands

- qcodes/instrument/parameter.py
- test_requirements.txt
With the new release of mypy 0.620, the mypy part of the test started failing ([an example here](https://travis-ci.org/QCoDeS/Qcodes/builds/404452622?utm_source=github_status&utm_medium=notification)):
```
qcodes/instrument/parameter.py:1046: error: The type alias is invalid in runtime context
qcodes/instrument/parameter.py:1052: error: The type alias is invalid in runtime context
qcodes/instrument/parameter.py:1055: error: The type alias is invalid in runtime context
qcodes/instrument/parameter.py:1059: error: The type alias is invalid in runtime context
qcodes/instrument/parameter.py:1224: error: The type alias is invalid in runtime context
qcodes/instrument/parameter.py:1229: error: The type alias is invalid in runtime context
qcodes/instrument/parameter.py:1233: error: The type alias …
```
> Quick fix for mypy 0.620 behavior

- qcodes/dataset/data_set.py
- qcodes/dataset/sqlite_base.py
- qcodes/tests/common.py
Recently, two users have reported that it takes too much time to save data to the database during the experiment. In particular, saving 10,000 points for 5 parameters (2 dependent, and 3 independent) is reported to take 5-10s.
After investigating the `DataSaver` `add_results` method using `cProfile` profiler, I could improve the saving speed by a factor of ~2. Hence, this pull-request.
The fix is in the `insert_many_values` method. The data is split into chunks in order to pass as many values as possible within a single `INSERT` call. The problem was that each of these `INSERT` calls had a `commit` which was decreasing the performance. As it is suggested everywhere on the web, in this situation, all the `INSERT` calls should happen within one transaction, meaning there should be a single …
> Datasaver save speed

- qcodes/instrument_drivers/AlazarTech/ATS9870.py
- qcodes/instrument_drivers/AlazarTech/utils.py
This is already set correctly above by passing instrument to the super method
@wpfff Would be great if you can test if this resolves your issue.
> Dont assign to instrument property

- qcodes/instrument_drivers/QuTech/IVVI.py
Since set_pol_dacrack makes a call to set_parameter_bounds, and set_parameter_bounds references dacs, dacs (parameters) need to be added to the instrument before calling set_pol_dacrack
- slightly reorder inicialization of IVVI
@astafan8
> Reorder initialization of IVVI

- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/tests/drivers/test_ami430.py
The AMI430_3D magnet does not currently support non-blocking field ramps. A linear field ramp between two safe points is always safe if the ramp rates are safe, so this should be possible.
The new block_during_ramp parameter (default True), if set to False, will call the set_field methods of the children with the argument block=False, so that they get ramped in a non-blocking way.
> driver / add block_during_ramp parameter to AMI430_3D

- qcodes/config/config.py
- qcodes/tests/test_config.py
Fixes #1223 .
allows a config file path to be specified either in initialisation of the Config object or when running update. This path is then used for future updates.
How's this @jenshnielsen? I haven't tested it yet.
> allow config to update based on specified path

- qcodes/dataset/measurements.py
- qcodes/tests/dataset/test_datasaver.py
Fixes #1224
We test if a value is a "non-array-type" by our ability to recast it to a float. This is more robust than having a list of acceptable types as we can always miss types.
> Make data saver accept numpy type floats/ints 

- qcodes/instrument/group_parameter.py
- qcodes/tests/test_group_parameter.py
I have created a separate PR for the GroupParameter and added a basic test
> GroupParameter and Group (for visa commands that set/get more than one parameter at once)

- docs_requirements.txt
Most probably the reason is in this sphinx issue:
https://github.com/sphinx-doc/sphinx/issues/5291
Warnings that sphinx 1.7.7 gives look like this:
`WARNING: error while formatting arguments for xxx.xxx.xxx: '_Any' object has no attribute '__origin__'`
I could not understand why it happens. It also seems that more and more people are getting the same error, so just falling back to other sphinx versions should a good workaround, so that it does not block our work.
> Do not use sphinx 1.7.7 due to possible sphinx bug with type annotations

- qcodes/instrument_drivers/QuTech/IVVI.py
parameters can't have white spaces
> IVVI add missing underscore in parameter name

- docs/examples/driver_examples/QCodes_example_with_SR86x_with_buffered_readout.ipynb
- qcodes/instrument_drivers/stanford_research/SR86x.py
Adds the possibility to return multiple measured values at the same time, `get_values` by implementing corresponding visa commands. Also, add data channels, `data_channels`, which also allow to return 4 values of parameters assigned to them at once.
ToDo:
> SR86x lockin: get values of many parameters at once

- environment.yml
- requirements.txt
- setup.py
This upgrade was pending for a long time already. It is especially necessary for https://github.com/QCoDeS/Qcodes/pull/1248 because `matplotlib > 2.1.x` supports plotting categorical (i.e. string-valued) data out-of-the-box.
Other relevant updates to dependency requirements are performed in https://github.com/QCoDeS/Qcodes/pull/1120 PR.
> Upgrade matplotlib to 2.2.3

- qcodes/data/format.py
- qcodes/data/gnuplot_format.py
- qcodes/data/io.py
- qcodes/dataset/database.py
- qcodes/instrument/base.py
- qcodes/instrument/function.py
- qcodes/instrument_drivers/tektronix/AWG5014.py
- qcodes/instrument_drivers/tektronix/AWG70000A.py
- qcodes/loops.py
- qcodes/plots/base.py
- qcodes/plots/pyqtgraph.py
- qcodes/station.py
- qcodes/tests/test_channels.py
- qcodes/tests/test_deprecate.py
Pytest 3.8 has been released and this now shows deprecation warnings by default. Turns out we trigger a few of those. This should fix that. This is WIP until all of them have been fixed. Please don't merge just yet
> Fix deprecation warnings

- qcodes/dataset/plotting.py
maxval may be zero if all data is zero so protect against that. @Dominik-Vogel 
We have an example of this in one of the notebooks
> Fix potential divide_by_zero warning in scale selection

- qcodes/tests/test_config.py
Currently pytest may fail when run locally because some test for the config subsystem require an untouched `qcodesrc.json`.
This pr introduces a context manager to temporarily set all config paths to point to the defaults `qcodesrc.json` and uses this context manager to fix the failing test.
> Fix codebase to enable local testing

- qcodes/instrument/group_parameter.py
- qcodes/tests/test_group_parameter.py
> Base GroupParameter on Parameter instead of _BaseParameter

- .gitignore
When using mypy in VSCode, a lot of files are generated in `.mypy_cache`. Better to ignore them.
@Dominik-Vogel
> Ignore mypy_cache files

- qcodes/instrument/channel.py
- qcodes/utils/validators.py
- test_requirements.txt
Now that `mypy` version `0.630` is out, we can remove a few workarounds from our code.
@QCoDeS/core
> Remove mypy workarounds

- qcodes/instrument_drivers/tektronix/AWG70000A.py
fixes #1281 @wpfff I think this solves your problem
> Consider wait for trigger equivalent to running in wait for trigger

- environment.yml
- requirements.txt
Ipykernel 4.10/5.0 has been released with a bugfix for the issue in 4.9 that broke the kernel in spyder
I also took the chance to upgrade matplotlib to 3.0. I have checked the changelog and there does not seem to be any changes likely to break any functionality for us
> Remove pined version of ipykernel and upgrade matplotlib dependency

- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_guids.py
- qcodes/tests/test_config.py
- qcodes/utils/helpers.py
even if an exception is thrown. 
The code after a yield statement in a context manager (the ``__exit__`` code) is not run if an exception is thrown unless wrapped in a try finally construct. In these cases I think it makes sense to always run the `__exit__` code @WilliamHPNielsen
> Ensure that post actions are performed in some context managers 

- environment.yml
Discovered as part of #1297 should unbreak a conda install for now
> Pin testpath to fix conda/pip issue

- .travis.yml
- azure-pipelines.yml
> Generate fixture dbs on azure

- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
Fix formatting of set commands with more than 4 significant digits after the comma. The instrument supports exponential notation so there is no need for specific formatting.
Also took the chance to add some validators, docstrings and typehints
> Fix keithley 2600 formatting

- qcodes/instrument_drivers/AlazarTech/ATS.py
@astafan8 It would be great if you can test that this works as expected with the 9373 if you have the chance. I have tested it with the 9360 version 21.07
> Add firmware version to Alazar get_idn

- qcodes/tests/test_validators.py
- qcodes/utils/validators.py
This means that you can use another parameter to define the shape of a parameter with an array validator. This is part of doing #1263 with some more checks for consistency. 
I also did a bit of cleanup on the validators
* Did away with the super init method that cannot be called which is unusual and really doesn't add anything useful. 
* Added typehints to all validators 
* Improved a few docstrings
> Make Array validators shape optionally callable

- setup.py
We don't want these to block the install of qcodes fixes #1314
I am not sure if the code to check extra dependencies actually adds much value. Regardless of the output it will not be shown when you pip install qcodes unless you pass the `-v` flag. We could also just remove it
> Catch generic exceptions in import of dependencies. 

- qcodes/instrument/base.py
`log.info(..., exc_info=smth)` is correct, where `exc_info` is the name of the kwarg. See [logging module docs](https://docs.python.org/3/library/logging.html#logging.Logger.debug)
> Fix typo in log call with exc_info kwarg

- qcodes/config/config.py
- qcodes/data/data_array.py
- qcodes/dataset/experiment_container.py
- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/Advantech/PCIE_1751.py
- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/utils/helpers.py
- qcodes/utils/validators.py
Fixes #1319 .
- importing the abstract collections (like Sequences, Iterable, ..) directly from the `collections` module is deprecated. This patch changes the imports to`import from `collections.abc`.
- note that the fix as it is might break things for users who use python <3.3. 
@astafan8
> changes imports of abstract base class collections

- qcodes/dataset/data_set.py
- qcodes/tests/dataset/test_dataset_basic.py
Needed in #1227 
- Refactor the `__init__` method of the `DataSet` class to kill the `_new` method
This is to ensure a more uniform behaviour of the `DataSet` no matter how it is initialized, which in turn will make it easier to implement the DSL-objects in the `DataSet`.
@QCoDeS/core
> Refactor / dataset __init__ method

- qcodes/instrument_drivers/AlazarTech/ATS.py
- qcodes/instrument_drivers/AlazarTech/ATS9360.py
This is work in progress since it should probably not be merged before its used for anything
> Add functions to read and write registers on Alazar and Trigger holdoff for 9360

- qcodes/dataset/data_set.py
- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_dataset_loading.py
- qcodes/tests/dataset/test_sqlite_base.py
Currently when one uses `load_by_id` for non-existing `run_id`, the exception looks like `"Expected one row"`. This PR fixes it with:
* add `run_exists` method to `sqlite_base`
* call `run_exists` in `DataSet` constructor and raise exception with clear message if the `run_id` does not exist
* tests
Note that the used query seems to be quite fast according to [this stackoverflow discussion](https://stackoverflow.com/questions/1676551/best-way-to-test-if-a-row-exists-in-a-mysql-table).
> Meaningful exception when loading/creating dataset for non-existing run id

- qcodes/dataset/measurements.py
- qcodes/tests/dataset/test_snapshot.py
- qcodes/tests/test_helpers.py
- qcodes/utils/helpers.py
If an instrument parameter is set to a value of `numpy.int32` type, JSON dumping of the snapshot will fail with an exception that "int32 type cannot be serialized to JSON". It's easy to get into such a situation, for example, start an experiment after code like this has been executed: `... for x in np.arange(10, 20, 2): my_instrument.power(x) ...` (explanation: the code leaves the `power` parameter with the value of type `numpy.int32`, so if you start a new measurement afterwards, JSON-ifying the snapshot fails). Note however that using floats in that `arange` call removes the problem: `... np.arange(10.0, 20.0, 2)....`. This is has to do with the interesting fact that `json.dumps(numpy.float64(1))` works while `json.dumps(numpy.float32(1))` or `json.dumps(numpy.float16(1))` (or other) …
> Fix JSON-dumping of snapshots with numpy-typed values (and other)

- qcodes/dataset/experiment_container.py
- qcodes/tests/dataset/test_experiment_container.py
In the spirit of #1323, this PR proposed to do the same for the `Experiment` class
- Refactor the `__init__` of Experiment so that no `_new` method exists
- Add a test for the new behaviour
- Fix two broken properties of the `Experiment` (`started_at` and `finished_at`)
@astafan8 @QCoDeS/core
> Refactor / experiment init

- qcodes/dataset/data_set.py
- qcodes/dataset/experiment_container.py
- qcodes/dataset/measurements.py
- qcodes/dataset/param_spec.py
- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_experiment_container.py
- qcodes/tests/dataset/test_sqlite_base.py
Major changes proposed in this pull request:
* Raise when creating DataSet with path_to_db and connection both not-None
* Make run_id read-only attribute of DataSet + tests
* Make path_to_db read-only attribute of DataSet + tests
* Type annotation of load_or_create_experiment same as load_experiment
* Adding duplicate parameters: remove confusing todo and improve the test
* load_by_id does not allow None as argument (which would result in creating a new dataset)
* Only create new experiment if exp_id is not None
* load_last_experiment does not create new experiments if there a none in database
Minor changes proposed in this pull request:
* Remove comments that are outdated or useless
* Deprecate DataSet.add_parameters in favor of DataSet.add_parameter
* Experiment.last_data_set raises if …
> qcodes.dataset.* fool-proofing and minor fixes

- environment.yml
E.g fix failures such as https://quarcsw.visualstudio.com/QubitWorkbench/_build/results?buildId=7672&view=logs
> Hopefully unbreak on windows/azure by pinning python to 3.6.6

- qcodes/tests/dataset/test_database_creation_and_upgrading.py
@WilliamHPNielsen These new tests from #1227 are not skipped in the same way as the old ones
> Upgrade tests should be skiped if fixtures are not there

- docs/api/public.rst
- docs/conf.py
- docs/make.bat
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA.py
- qcodes/plots/base.py
- qcodes/plots/pyqtgraph.py
- qcodes/plots/qcmatplotlib.py
- qcodes/utils/plotting.py
- qcodes/utils/validators.py
* Restructure the conf file to be less confusing
* This uncovered a bug that meant that some of the pages that should have been included were not
* Those pages had rst syntax issues that I fixed
* Start adding api docs for the dataset
> More Documentation cleanup

- qcodes/instrument/channel.py
- qcodes/tests/test_channels.py
In the `extend` method of channel list, we did not update the channel mapping. As a result a `KeyError` was generated when removing the channel. This is fixed in this PR. A test is added to verify the effectiveness.
@jenshnielsen or @WilliamHPNielsen Can you perhaps look at this?
> Bugfix: removing a channel instance that was added with `extend`

- docs/conf.py
- qcodes/instrument_drivers/Minicircuits/USB_SPDT.py
So that we actually print the error message when this fails. 
In addition fix an infinite (well up to  maximum recursion depth) error that will happen when closing the instrument and some docstring fixes
> Minicircuits USB_SPDT catch the correct error

- docs/examples/driver_examples/Qcodes example with Stanford SR830.ipynb
- qcodes/instrument_drivers/stanford_research/SR830.py
I often need to auto range lock-ins mid-sweep. I think it's usually best for instrument drivers to only act as instrument drivers, so I went with as small a change as possible to let me implement autoranging outside of the driver. It would have also been possible to add autoranging behavior into the driver itself, and if y'all prefer that then I'd be happy to update this PR.
The two functions in this change make it possible to do things like the following in my measurement sweeps:
```python
def autorange(srs, max_changes=1):
def autorange_once():
r = srs.R.get()
sens = srs.sensitivity.get()
if r > 0.9 * sens:
return srs.increment_sensitivity()
elif r < 0.1 * sens:
return srs.decrement_sensitivity()
return False
sets = 0
while autorange_once() and sets < max_changes:
sets += 1 …
```
> SR830: Add increment/decrement sensitivity functions.

- qcodes/dataset/data_set.py
- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_sqlite_base.py
There is currently no way to query for the metadata associated with a particular dataset. One can only look up metadata by tag, which requires some auxiliary knowledge about the metadata.
- Add a `metadata` property to a `DataSet` object to see all associated metadata.
This little improvement is needed for #1352 in order to ensure correct copying of metadata.
@astafan8
> Improvement / dataset metadata

- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_dataset_basic.py
Fixes #1384.
There are two bugs in the underlying `get_data` function of `sqlite_base.py`:
* `0` are treated as `None`
* sql query has a typo in the `where` clause for `start` for the case where both `start` and `end` are not `None`
This PR fixes both. 
Note that the current behavior suggests a `1`-based indexing (unlike python `0`-based), with both `start` and `end` indexes being _included_ into retuned data. This behavior is captured by the test suite.
Ideally, the very same test should be done for `get_data` from `sqlite_base.py` but did not make it to this PR in order to avoid code duplication.
Note that `get_data` from `sqlite_base.py` was also refactored to reduce the possibility for bugs like the ones mentioned above. In case it made the function less readable, the refactoring can …
> DataSet.get_data bugs with start/end arguments

- qcodes/instrument/parameter.py
`Parameter`'s `post_delay` and `inter_delay` properties have confusing descriptions. This PR addresses this.
Also remove deprecated `get_delay`, `set_delay`, `get_step`, `set_step`. Make `delay` kwarg a noop.
Discovered by @damazter
> Fix unclarity about post_delay/inter_delay of Parameter, remove deprecated get/set delay and get/set step

- qcodes/instrument_drivers/QuTech/S5i.py
- Update qutech S5i driver
@astafan8
> Feature/dem 613/update s5i driver

- .appveyor.yml
- .travis.yml
- azure-pipelines.yml
- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/legacy_DB_generation/generate_version_3.py
- qcodes/tests/dataset/legacy_DB_generation/utils.py
- qcodes/tests/dataset/test_database_fixes.py
Background: "in the wild", we have encountered a database with corrupt `run_description`s.
- Add a function to fix wrong descriptions
- Add a test for it
- Generate version 3 database files, as a side effect of this PR
@astafan8
> Add function to fix wrong descriptions

- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
Needed over at #1352 
- Add a little convenience function to get the DB version of a database and the latest available DB version
@QCoDeS/core
> Feature / let database show version without upgrading

- qcodes/instrument_drivers/tektronix/AWG70000A.py
Substitute the annoying `print` statements in the driver with `log.debug`. Logging can be easily enabled when needed, qcodes has convenient infrastructure as well.
> Use log instead of print in AWG70000A driver

- qcodes/instrument_drivers/Keysight/KeysightAgilent_33XXX.py
Extends Qcodes/qcodes/instrument_drivers/Keysight/KeysightAgilent_33XXX.py
- Add support for model 33512B by adding its specs to `no_of_channels `and `self._max_freqs` dictionaries
> feat: add specs for model '33512B' in KeysightAgilent_33XXX

- qcodes/dataset/data_export.py
- qcodes/dataset/plotting.py
- qcodes/tests/dataset/test_plotting.py
Fixes #1426 
The problem in #1426 arose because of the way the `kwargs` to different plots were handled. It may well be that one call to `plot_by_id` produces several different plot types (heatmaps, line plots, etc.). They do not all consume the same `kwargs`, e.g. `'cmap'` is unknown to a line plot.  
- Introduce a context manager to handle passing on only the relevant `kwargs` to each plot.
@QCoDeS/core
> Fix / plot by id cmap kwarg

- docs_requirements.txt
The bug causing #1268 has been resolved so lets try building the docs with Sphinx 1.8.3
> Build docs with sphinx 1.8.3

- .travis.yml
It seems like Travis has deployed a new image today that breaks the way we used to start xvfb. This should fix that
> Try different way of starting xvfb

- qcodes/instrument/parameter.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_instrument.py
- qcodes/tests/test_parameter.py
This allows us to use InstrumentBase as the base class for virtual instruments
Fixes #1450.
- Use getattr to get ask/write from instruments
> Use getattr to get ask/write from instruments

- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
This can happen if you go back to an old git version and is dangerous
as it can result in inconsistent DBs
I suspect this is the reason why the fix in https://github.com/QCoDeS/Qcodes/blob/master/qcodes/dataset/sqlite_base.py#L2524 has been needed, A db has been upgraded and subsequently written to by an older qcodes version
> Don't allow connection to db that is newer than the one we support

- qcodes/logger/logger.py
- test_requirements.txt
To avoid failures in the future this locks mypy to version 0.670. If we go down this route someone should remember to regularly update our dependency on mypy
> Fix typechecking with mypy=0.670

- qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
Added additional parameters to oxford\MercuryIPS_VISA.py allowing the magnet to be set and ramped with a single call. This is useful when running in a loop.
> Add simultaneous blocking ramp parameters MercuryIPS

- docs/conf.py
- docs_requirements.txt
- qcodes/dataset/data_export.py
- qcodes/instrument/group_parameter.py
- qcodes/monitor/monitor.py
- qcodes/utils/magic.py
- qcodes/utils/slack.py
- qcodes/utils/zmq_helpers.py
This fixes a bunch of invalid restructured text in the api documentation.
This is cherry-picked out of #1478 to make that pr smaller since this should be straightforward to review
but does carry the risk of more conflicts. I have made no attempts of improving the language or content. This is purely a rst syntax fix
Edit: I also updated the version of sphinx to the latest bug fix.
> docs fix restructured text syntax.

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
We keep seeing these warnings in various instrument customization written by users.
This should make it easier to find and eliminate the last few cases of this outside qcodes and make it 
more obvious to users what they need to fix.
In addition make it more clear that this will eventually be an error.
> Add origin to parameter warnings

- azure-pipelines.yml
It seems like the `conda_hook` script is not being run correctly so we need to run it at each iteration before we are able to run `conda activate qcodes` this is arguably uglier than the original deprecated activation.
Furthermore it seems that conda then is a batch script so we need to add CALL in front of every invocation of conda to prevent it terminating the script early (at exit of conda)
> Use modern way of activating conda env on azure

- .gitignore
- azure-pipelines.yml
- qcodes/math/field_vector.py
* Run mypy, pytest, db generation, docs build independent of each others success or failure (say, still run pytest if mypy failed)
* publish coverage results after pytest results, not after docs build
* make more steps succeededOrFailed instead of always
* add more display names
* finally ignore .vscode files
> Azure pipeline: independent steps

- qcodes/dataset/measurements.py
- qcodes/tests/dataset/test_measurement_context_manager.py
Otherwise this will not work correctly when inserting as arrays
> Cast array params to np array before inserting

- qcodes/dataset/measurements.py
This reshape is redundant since ravel below does the same
The 0D numpy array insertion that needed this is tested by `test_datasaver_unsized_arrays`
> Remove redundant reshape

- qcodes/dataset/data_set.py
- qcodes/tests/dataset/dataset_fixtures.py
- qcodes/tests/dataset/helper_functions.py
- qcodes/tests/dataset/test_dataset_basic.py
> Add support for exporting variable len array data to pandas

- azure-pipelines.yml
.. useful when docs build is successful but, say, mypy failed.
> Publish docs even if the whole job failed

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- Set and Get the sampling rate of the ZIUHFLI using float. 
@WilliamHPNielsen @jenshnielsen @astafan8
> Feature/dem 805/implement sampling rate float parameter

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- Add support for enabling, and amplitude, for all devNNN/sigouts/ in ZIUHFL driver
- Change name of parameters `signal_outputN_enable` and `signal_outputN_amplitude` to `signalN_outputM_enable1` and `signalN_outputM_amplitude` in ZIUHFLI driver.
> Feature/dem 804/implement missing uhfli commands

- qcodes/instrument_drivers/ZI/ZIHDAWG8.py
- Compiler warnings in ZIHDAWG8 are caught and logged
- Compiler warnings can be elevated to errors
@astafan8
> [DEM-831] Compiler warnings in ZIHDAWG8 should be logged or raised.

- qcodes/instrument_drivers/AlazarTech/ats_api.py
- qcodes/instrument_drivers/AlazarTech/constants.py
This is useful as it among other things can be used to inspect the status of the buffers added to the card.
> Alazar add get/set parameter

- qcodes/instrument_drivers/Lakeshore/Model_336.py
- qcodes/instrument_drivers/Lakeshore/Model_372.py
- qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
- qcodes/tests/drivers/test_lakeshore.py
- qcodes/tests/drivers/test_lakeshore_336.py
This PR is a result of a wish of using Lakeshore Model 336 driver in Delft, which turned into fixing some bugs in the drivers.
Most notable:
* Add test for Model 336 that is very similar to test for Model 372 (quick copy-paste mostly)
* Fix BaseOutput's input_channel parameter creation. It has to be a group parameter, but other kwargs like val_mapping and/or vals and others can be now specified in the subclasses to allow aproprivate variations between models. in Lakeshore Model 336, Model 372, and their base class.
* Map input_channel values and sensor channel names. Add map between BaseOutput's input_channel values and sensor channel object names. Model 336 uses letters for sensor channel names, hence the values of the BaseOutput's input_channel parameter naturally become strings. Model …
> Lakeshore Model 336: make runnable, add minimal test, and fixes along the way

- qcodes/tests/common.py
- qcodes/tests/test_testutils.py
- qcodes/tests/test_wrong_address.py
* Handles cases where line information is missing (such as worked around in #1477 
* Only match against the root cause of the exception. This seems like what was always intended
* Add tests of the above
* Remove one incorrect use of error_caused_by
> Make error_caused_by more robust

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- If MF is enabled in ZI UHFLI there are 8 oscillators that can be controlled.
- Sampling rate as float should return exact value, not rounded off value. 
> Number of oscillators should be 8 if MF enabled

- qcodes/instrument_drivers/Keysight/Keysight_E8267D.py
> add parameter for Keysight E8267D IQ modulator 

- qcodes/instrument_drivers/cryocon/cryocon_26.py
* Make termination a kwarg of init, and pass it to super's init call.
* remove `reset` argument
Delft users discovered that the terminator is actually `\r\n` although `\n` also works. The hint to this was discovered when the queue of the visa responses got out of sync. But i've decided not to change the default terminator and just let the users set it, and if they confirm with usage that `\r\n` is the right one, then we'll change it.
> Cryocon / Allow setting termination character

- qcodes/instrument_drivers/american_magnetics/AMI430.py
- qcodes/tests/drivers/test_ami430.py
- qcodes/utils/types.py
The original user problem was that the driver would raise `ValueError` when initialized with a floating point value. This prevented the user to set the field limit to smth like 2.1T, and the workaround was to use an unsafe limit of 3T. 
This is the code:
https://github.com/QCoDeS/Qcodes/blob/1923c8d5c60580c902c93ec5e22b2cfd2bede401/qcodes/instrument_drivers/american_magnetics/AMI430.py#L493-L497
The problem is that `repr(field_limit).isnumeric()` is used to check whether the `field_limit` is "numeric" - which returns `True` for integer values but returns `False` for floating point values. Also, it's pretty bizarre that a string method is used to check for "numeric-ness", and is used wrongly.
This PR implements a fix for it, see the list below.
List of changes:
* Use `isinstance` for type …
> AMI430 driver: fix using numeric field_limit

- .travis.yml
- azure-pipelines.yml
- qcodes/dataset/data_set.py
- qcodes/dataset/plotting.py
- qcodes/dataset/sqlite_base.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_datasaver.py
Make `snapshot` column (of type "TEXT") always present in `runs` table. This way it becomes part of the stable schema, not a "metadata" column anymore.
Relies on version 4 database generator from here https://github.com/QCoDeS/qcodes_generate_test_db/pull/3.
Also couldn't resist fixing some of the style stuff.
ToDo:
> DB upgrade: version 5 - snapshot column ALWAYS present in runs table

- qcodes/instrument/base.py
- qcodes/instrument_drivers/ZI/ZIHDAWG8.py
- update parameter in ZIHDAWG.snapshot_base should work as advertised.
- feature_code should be ignored when getting an update snapshot.
> Remove warning when taking snapshot of ZIHDAWG8

- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
if-elif-else routines are replaced with dictionary methods 
to increase efficiency.  
> Increase efficiency in ZNB driver

- qcodes/instrument_drivers/QuTech/M2j.py
- qcodes/tests/drivers/test_m2j.py
- Move upper limit on M2j gain parameter from 55 to 110 
@astafan8
> Mj2 gain validator to narrow

- qcodes/instrument_drivers/tektronix/Keithley_6500.py
- Keithley6500 trigger_timer validator to should allow 0
@astafan8
> Keithley6500 trigger_timer validator to narrow

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- Add parameter to enable TCP/IP jumbo frames
- Add parameter to set the reference clock source
- Fix typo in demod{N}_ oscillator parameters
> Add jumbo frames and reference clock source parameters to ZIUHFLI

- qcodes/dataset/sqlite/__init__.py
> Avoid invalid escapse sequence by using raw string

- qcodes/tests/drivers/test_Keithley_2450.py
- qcodes/tests/drivers/test_keithley_s46.py
- qcodes/tests/drivers/test_keysight_34465a.py
- qcodes/tests/drivers/test_zihdawg8.py
- qcodes/tests/test_logger.py
- qcodes/tests/test_visa.py
- qcodes/tests/test_wrong_address.py
This avoids a bunch of warnings from pytest. 
Furthermore fix a test that depended on the state of the simulated instrument when being run.
This is caused by pyvisa-sim remembering state even when closing instruments
> Close instruments in tests.

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- Ignore  `sweeper_sweeptime` in `snapshot(update=True)` if `_sweeper_signals` is an empty list
- Getter for `scope_mode` and `scope_average_weight` should work
When taking a snapshot of the ZIUHFLI driver with update=True the following warnings are generated:
```
[ziuhfli(ZIUHFLI)] Snapshot: Could not update parameter: sweeper_sweeptime
[ziuhfli(ZIUHFLI)] Snapshot: Could not update parameter: scope_mode
[ziuhfli(ZIUHFLI)] Snapshot: Could not update parameter: scope_average_weight
``` 
This should no longer be the case.
> ZI UHF-LI: fix `scope_mode` and `scope_average_weight` parameters

- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
Add a list to the instrument class to make referencing the
channels easier
- Add list to hold channels
- 
- 
Hey @jenshnielsen 
I like to be able to loop over the channels for initialization etc, so adding a simple list to this driver. 
Thanks
> Keithley 2600: Add list to hold channels

- qcodes/instrument/sims/Tektronix_DPO7200xx.yaml
- qcodes/instrument_drivers/tektronix/DPO7200xx.py
- qcodes/tests/drivers/test_tektronix_dpo7200xx.py
This PR includes a bugfix. The measurement module returned strings instead of floats as measured value. Obviously, I forgot to include a get_parser.
> Tektronix DPO7200xx / bugfix / measurement should return floating point values

- qcodes/dataset/sqlite/queries.py
Snapshot is now in RUNS_TABLE_COLUMNS so this todo can go.
Noticed this as part of #1605
> Remove out of date todo with metadata columns

- qcodes/dataset/data_set.py
- qcodes/dataset/database.py
- qcodes/dataset/experiment_container.py
- qcodes/dataset/sqlite/connection.py
- qcodes/dataset/sqlite/database.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/temporary_databases.py
- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_experiment_container.py
- qcodes/tests/dataset/test_sqlite_base.py
- qcodes/tests/dataset/test_sqlite_connection.py
The conn could point to any file on disk so this will in general not be correct.
Fix this by looking up the db path from the connection supplied and using that rather than relying on the config. Only fall back to config if no path or conn is supplied. 
Also fix a small issue where the path separators could be inconsistent if the incorrect platform dependent path sepeartor was used in the config file. e.g. on windows `~/experiments.db` would previously expand to `c:\\users\\username/experiments.db` 
Another issue discovered as part of #1605 
This should preferably have a test.
> Don't get db location from config if conn supplied

- qcodes/instrument/sims/Keithley_s46.yaml
- qcodes/instrument_drivers/tektronix/Keithley_s46.py
- qcodes/tests/drivers/test_keithley_s46.py
Currently, to check if a channel on the Keithley S46 is closed we have to write the following: 
```python
s46.A1.get() == "close"
```
This can be error prone: typos can cause this code to fail (e.g. 'closed' instead of 'close', 'Close' with a capital C, accidental spaces, etc). 
Furthermore, a bug of this nature can go unnoticed for a long time and might be hard to track down, as the code above will not generate an exception when 'close' is spelled wrong. 
The following code is much more robust
```python
s46.A1.is_closed()
```
An understandable error message will be thrown when the above code is run with a typo in the method name.
> Add a method on the channel parameter to check if it is closed.

- docs/user/intro.rst
- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/instrument/ip.py
- qcodes/instrument/parameter.py
- qcodes/instrument/visa.py
- qcodes/loops.py
- qcodes/station.py
An extra note concerning the involvement of a custom class about the JSON-ability of snapshots is added to the relevant docstrings.  
@astafan8
> Add clarity on JSON-ability of snapshot in docs

- qcodes/.coveragerc
- qcodes/instrument_drivers/tektronix/AWG70000A.py
- qcodes/tests/drivers/test_tektronix_AWG5208.py
Fixes #1134 
- Add a test for the docstring
- Make the docstring model dependent
@astafan8
> Tektronix AWG 70000 5028 resolution docstrings

- qcodes/instrument_drivers/Spectrum/M4i.py
The m4i acquisition methods do not all set properties for the triggering in the same way. Fixing this would be backwards incompatible. This PR at least updates some of the docstrings.
@astafan8
> update m4i docstrings

- .travis.yml
I do honestly do not see the benefit of this limitation. And it prevents prs targeting feature branches to be build correctly.
> Build travis against all branches

- qcodes/instrument/base.py
- qcodes/logger/__init__.py
- qcodes/logger/logger.py
- qcodes/tests/test_installation_info.py
- qcodes/tests/test_logger.py
- qcodes/utils/installation_info.py
It can be very useful to have some basic information about the installation of qcodes in the logs.
This PR seeks to enrichen the log output with more useful info, in particular installation info. I am, however, not really sure about the logic when looking up the environment. It goes something like
- First check if the installation is from pip or from source
- If from pip:
-  record the version number and call it a day
- If from source
- check if editable
- compare `pip freeze` to `requirements.txt` (?)
The idea is to do all this as `qcodes.logger.start_logging` is called.
Or what do you think, @QCoDeS/core ? I'd like to make as few `subprocess` calls to `pip` as possible.
> Dev / log install info

- qcodes/instrument_drivers/Keysight/Keysight_E8267D.py
Fixes issue introduced with #1554. The constructor for the on-off value mapping has the order of arguments reversed.
@astafan8
> fix bug in on_off_mapping

- qcodes/instrument/sims/Keysight_N6705B.yaml
- qcodes/instrument_drivers/Keysight/Keysight_N6705B.py
- qcodes/tests/drivers/test_Keysight_N6705B.py
This is a bare bones driver for the Keysight N6705B DC power
supply.
- Add basic driver for this power supply 
@astafan8 
Hey guys, could you have a quick look over this please. I had a quick look around but couldn't find a driver for this power supply.  I mostly copied the driver for the B296A. The programming manual is [here](http://literature.cdn.keysight.com/litweb/pdf/N6705-90902.pdf)
> feat: Add basic driver for Keysight N6705B

- qcodes/instrument/base.py
- qcodes/instrument/ip.py
- qcodes/instrument/parameter.py
- qcodes/tests/test_snapshot.py
- Added a parameter to the instrument parameter to exclude it from the snapshot. 
Note that this is very similar to #1651, the goal is the same but it has a different implementation. To see the reason why we need this please look at #1651 which has a detailed problem description. This implementation was suggested by @jenshnielsen, which uses the instrument parameter to store the `snapshot_exclude` instead of providing a list to the snapshot function. 
@jenshnielsen, @AdriaanRol
>  Feature: Added instrument paramater snapshot_exclude 

- docs/examples/driver_examples/QCodes example with Tektronix DPO 72004C.ipynb
- qcodes/instrument/sims/Tektronix_DPO7200xx.yaml
- qcodes/instrument_drivers/tektronix/DPO7200xx.py
- qcodes/tests/drivers/test_tektronix_dpo7200xx.py
We add the following functionalities to the measurement submodule of the driver:
1) Ability to gather measurement statistics: mean, max, min and standard deviation 
2) Automatically turn a measurement on when calling a measurement method (Set `state` to True) 
3) Ability to globally set the statistics mode, time constant and buffer resetting
@astafan8 Can you have a look, please?
> Add functionalities to dpo measurement

- docs/examples/DataSet/The-Experiment-Container.ipynb
Modifying config is confusing and not needed. Even worse the examples are executed as part of the docs build so this may happen unnoticed
> Don't rewrite config file in exp container example

- qcodes/dataset/measurements.py
This is a very natural thing to log; that a measurement started.
@QCoDeS/core
> Add logging line to measurement

- qcodes/dataset/sqlite/db_upgrades/__init__.py
- qcodes/dataset/sqlite/db_upgrades/upgrade_2_to_3.py
- qcodes/dataset/sqlite/db_upgrades/upgrade_3_to_4.py
- qcodes/dataset/sqlite/db_upgrades/upgrade_5_to_6.py
All the DB upgrades should have a progress bar to make the output of the upgrading less confusing.
- Add a progress bar to all updaters
This PR doesn't feel particularly DRY, but I could only think of complicated ways of adding the progress bar to the `upgrader` decorator.
@QCoDeS/core
> Give all upgraders a progress bar

- setup.py
This will unconditionally install dataclasses but python 3.7 will normally prefer the std lib version over the site-package as site-packages is later in the path than the standard library
> Fix 3.6 wheels by always depending on dataclasses

- qcodes/utils/installation_info.py
- setup.py
see https://www.python.org/dev/peps/pep-0496/ for more info
This is the right solution for generating version independent whls that correctly handles dependencies
> use env markers for version specific deps

- environment.yml
- requirements.txt
- setup.py
* Add env markers for dataclasses in requirements.txt
* Matplotlib is a non optional dependency by now so add it to setup.py
* Add websockets to requirements.txt to align requirements.txt with setup.py
> Improve requirements 

- environment.yml
I think its about time to switch the default env to 3.7
This also upgrades pyvisa to the latest version and move most deps to conda-forge
> Update conda env to python 3.7

- docs/examples/driver_examples/Qcodes example with Keysight B1500 Parameter Analyzer.ipynb
Sampling measurement is taking a lot of time (~5 hrs) because the example notebook does not specify to set the averaging to 1. Setting this to one before starting sampling measurement is a default case scenario hence it makes sense to add it in the example notebook. 
Here, we explicitly specify in the example notebook to set the averaging to 1 before starting the sampling measurement. 
@astafan8
> Keysight b1500: Edit example notebook to set averaging during sampling measurement.

- qcodes/instrument_drivers/AlazarTech/ATS.py
The Alazar `AcquistionController` is an interface for the alazar ats instrument, that takes care of handling the buffer data. In the current implementation this interface is a qcodes instrument.
In my opinion this is an unnecessary coupling between pure number crunching code and qcodes instruments. I therefore suggest to refactor an `AcquisitionInterface` out of the `AcquisitionController`, which only contains the interface methods.
By letting the `AcquistionController` inherit from `AcquistionInterface` and `Instrument` the original functionality should stay untouched.
Additionally I removed the `NotImplementedError`s from some of the methods, which don't need to be implemented.
> Alazar: refactor `AcquisitionInterface` out of `AcquisitionController`

- docs/examples/driver_examples/Qcodes example with Lakeshore 325.ipynb
- qcodes/instrument_drivers/Lakeshore/Model_325.py
- In Lakeshore/Model_325.py  a new parameter "resistance" was added to obtain the resistance of the system
- In Lakeshore/Model_325.py, a new parameter "heater_output" was added to get the heater output (in %) of the system
- added examples to driver_examples/Qcodes example with Lakeshore 325.ipynb for the two new parameters
- minor formatting issue
@sohailc
> Lakeshore 325: adding two attri: resistance and heater_output

- qcodes/tests/drivers/test_ami430.py
The `Parameter` uses `datetime.now()` to define a timestamp of when it's value was set. `datetime.now()` may not always provide good resolution, so adding a `time.sleep` to the test code is a quick solution for the flakiness.
> AMI430 test: fix flakiness from asserting timestamps of Parameters

- qcodes/tests/test_parameter.py
... by adding `time.sleep(1)` to ensure that timestamps 
should be different regardless of the resolution 
of the function that produces the timestamps.
> Make test GetLatest stricter about timestamps

- azure-pipelines.yml
There have been cases where within a `bash` or `script` step one command would fail with non-0 exit code but the command after that would continue to execute. This is not desired because, for example, we don't want to run `mypy` if the `"qcodes"` environment wasn't activated.
In this PR, we use `&&` to glue commands together so that non-0 exit code prevents continuation of execution of a command sequence. Moreover, most of the `script` steps got converted to `bash` steps.
> CI: Link commands in all scripts by their exit code, use mostly 'bash'

- .travis.yml
- requirements.txt
Since its scheduled for release soon 
There are a few outstanding questions.
> Testing on python 3.8

- qcodes/utils/plotting.py
Use get_clim on the mappable as suggested here https://matplotlib.org/3.1.0/api/api_changes.html#colorbarbase-inheritance
This is already done below in the same function so no breakage with older matplotlib versions needs to be considered.
> Dont use deprecated matplotlib cbar.get_clim

- qcodes/station.py
- qcodes/tests/test_station.py
Add a method to the Station that closes all instruments that have been registered as a component to the Station.
Open questions:
- should Instruments also be removed from the station?
> Add `Station.close_all_registered_instruments`

- qcodes/station.py
This fixes the shortcoming of PR #1713, to also remove parameters from the monitor.
> Fix `Station.close_all_registered_instruments` to also remove from Monitor

- qcodes/dataset/data_set.py
... not ParamSpecBase's.
This was introduced some time ago when parameter info
was not written to database until the dataset is started.
This is an interface inconsistency, originally this DataSet
property was returning ParamSpec's.
> Make DataSet.paramspecs always return ParamSpec's

- README.rst
- setup.py
Due to the extra space at the beginning of the line it is not possible to upload the package to pypi
> Fix rst formatting in readme

- qcodes/tests/test_helpers.py
- qcodes/utils/helpers.py
* Add test for `create_on_off_val_mapping` explicitly for corner cases of True/False, 1/0, etc as on_val/off_val - this is needed because this shows a bug where the resulting `val_mapping` wouldn't contain `True`/`False`.
* Change `create_on_off_val_mapping` to NOT add `1`/`0` values to the resulting `val_mapping` because due to `hash(True) == hash(1)`/`hash(False) == hash(0)` using them already works.
> Bug: create_on_off_val_mapping doesn't work for 1/0 values

- environment.yml
- qcodes/utils/installation_info.py
- requirements.txt
- setup.py
This will be part of the standard lib in 3.8 and seems to be the recommend way. In addition  
use `requirements-parser` to do the parsing of the version requirements rather than writing our own parser
> Use importlib metadata

- qcodes/__init__.py
- qcodes/data/gnuplot_format.py
- qcodes/data/location.py
- qcodes/dataset/plotting.py
- qcodes/dataset/sqlite/database.py
- qcodes/instrument/channel.py
- qcodes/instrument/ip_to_visa.py
- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
- qcodes/instrument_drivers/Harvard/Decadac.py
- qcodes/instrument_drivers/Keysight/N52xx.py
- qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/server.py
- qcodes/plots/pyqtgraph.py
- qcodes/tests/drivers/test_lakeshore.py
- test_requirements.txt
This allows us to restrict ignore comments to only specific error codes. 
This has 2 benefits imho:
* We don't ignore any other errors than we should 
* This self documents why we need the ignore statements. 
For earlier versions of mypy this is simply ignored.
> Use Mypy 0.730

- test_requirements.txt
to workaround  what seems to be a bug in pip (19.2.3)
> explicitly install attrs 

- mypy.ini
- qcodes/instrument/base.py
- qcodes/instrument/visa.py
Since these are core parts of qcodes.
> Disallow missing types for instrument base and visa

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
This PR fixes a bug in `parameter.set_to` and reduces the amount of instrument communication (calls to `parameter.set`) that happens in the context manager.
The bugfix: if a parameter has been initialized, but not yet gotten, it will have a `_latest["value"]` of `None`. When exiting the context manager, the value that the parameter is restored to  should not be `None`, but instead the result of `parameter.get`.
The improvement: if `parameter` has value `X`, then `with parameter.set_to(X)` is now a NOOP.
The improvement allows us to write parameter getters that hinge on other parameters without introducing unnecessary communication. An example (simplified) for a DMM that can be in voltage or current mode:
```python
def _voltage_getter(self):
with self.mode.set_to("voltage"):
value = …
```
> Parameter set to improvements

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
If the parameter has never been captured it seems like `get_latest` should also call `get`
This is draft due to the missing tests
> Ensure that get_latest will call get on a parameter

- environment.yml
- requirements.txt
Install the latest patch release of numpy on the 1.16 branch and the latest version of pyvisa.
Note that h5py 2.10 and numpy 1.17 have been released. However they are not packaged in the default channel for conda so I have left them off for now.
> Bump installed versions of numpy and pyvisa

- qcodes/instrument/parameter.py
- qcodes/instrument/sweep_values.py
- qcodes/loops.py
- qcodes/measure.py
- qcodes/tests/test_metadata.py
- qcodes/utils/metadata.py
With the base class in metadatable. This is in all cases a no op
> make snapshot base signatures consistent

- qcodes/tests/dataset/test_subscribing.py
otherwise, it would sometimes fail because the CI infra is slow, which forces to restart the CI job completely and waste time.
> Use default delay for test subscriber from config

- azure-pipelines.yml
Less need to open the log file which should be a plus
> Add mypy output to test output upload

- qcodes/instrument_drivers/HP/HP_83650A.py
- qcodes/instrument_drivers/tektronix/Keithley_2400.py
@WilliamHPNielsen A Few months back we had decided to check for all the drivers which do not have the `connect-message` at init. Today, I went through all the drivers in (qcodes - qcodes_contrib_repo) repository and found that Keithley 2400 and HP 83650 needs connect message at init.
@astafan8 @GateBuilder
> QuickFix: Add connect message at init to Keithley 2400 and HP 83650

- docs/examples/writing_drivers/Creating-Instrument-Drivers.ipynb
- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/AlazarTech/utils.py
- qcodes/instrument_drivers/QDev/QDac.py
- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/devices.py
- qcodes/instrument_drivers/ithaco/Ithaco_1211.py
- qcodes/instrument_drivers/oxford/mercuryiPS.py
- qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
- qcodes/instrument_drivers/signal_hound/USB_SA124B.py
- qcodes/instrument_drivers/stanford_research/SR560.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_instrument.py
- qcodes/tests/test_parameter.py
... via `set_cache` or other fixes.
Requires merge of https://github.com/QCoDeS/Qcodes/pull/1757.
Note: Keysight B1500 use of `_save_val` is fixed in https://github.com/QCoDeS/Qcodes/pull/1789.
> Remove usage of _save_val in drivers and core qcodes

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
Drivers changed:
- Keysight B1500 and its modules
Requires merge of https://github.com/QCoDeS/Qcodes/pull/1757.
> Use set_cache instead of _save_val and setting raw_value attribute in Keysight B1500 driver

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
Refactor `Paramter.set_to` context manager to NOT directly use `._latest` cache. The idea also is that `set_to` defers the parameter-has-not-even-been-captured-hence-we-first-need-to-call-get logic to `get_latest()` as opposed to implementing it itself. Moreover, this PR adds some extra tests for `set_to(None)` edge cases.
@QCoDeS/core when reviewing, please let me know if I missed a test case so that I can add it to the test suite and hence ensure that this refactoring does not break the uncaptured behavior (note that I already added one extra test)
> Parameter.set_to: use get_latest, not _latest['value']

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
... that returns `._latest['raw_value']`. Reason - API consistency with `GetLatest.get` and `GetLatest.get_timestamp`.
In a later PR, this one https://github.com/QCoDeS/Qcodes/pull/1791, `_BaseParameter` will get all the three of these methods as well but named with a word `cache`.
> Add get_raw_value to GetLatest of Parameter

- .travis.yml
- qcodes/instrument_drivers/oxford/mercuryiPS.py
- qcodes/instrument_drivers/stanford_research/SR830.py
Now that 3.8 is out we should no longer need to use the dev branch
> test on travis using 3.8 release not dev branch

- qcodes/tests/test_deprecate.py
- qcodes/utils/deprecate.py
For classmethods the current deprecation mechanism was not transparent. That means it failed not in raising deprecation warnings, but in keeping the code operational. This goes back to the limitations of the underlying `@wraps(func)` decorator.
In this PR this decorator is replaced by the functionality provided by the `wrapt` package.
Additionally the tests are extended and cleaned up.
The previously failing test was:
```python
def test_class_method_uninhibited(self):
with warnings.catch_warnings():
assert C.class_method(1) == 2
c = C('pristine')
assert c.class_method(1) == 2
```
Interestingly only the second assert was failing.
> Fix deprecation for class methods

- qcodes/tests/test_deprecate.py
- qcodes/utils/deprecate.py
Turns out that my extensive tests were not extensive enough. Now, laugh and behold v3 of the vicious deprecation decorator, featuring no less then 200 LOC of test.
This time it fixes the issue that static methods could no longer be called uninhibitedly, as in the second part of this test:
```python
def test_static_method_uninhibited(self):
with _ignore_warnings():
assert C.static_method(1) == 2
with _ignore_warnings():
c = C('pristine')
assert c.static_method(1) == 2
``` 
Therefore I found dark magic to refrain from decorating static methods.
Lesson learned: it would have been better to just decorate the `__init__` method....
BTW. This PR does fix all tests of the driver deprecation PR.
> Fix deprecation of static methods

- mypy.ini
- qcodes/dataset/database_extract_runs.py
- qcodes/dataset/sqlite/queries.py
- qcodes/dataset/sqlite/query_helpers.py
This uncovers an actual bug in in database extract runs that was not correctly unpacking the run_ids. 
This bug happened to not matter since numpy.unique flattens nested arrays such that `[[1,2,3,3]] -> np.ndarray([1,2,3])` and was therefore not caught by tests
> Add types to sqlite queries

- mypy.ini
- qcodes/dataset/data_set.py
- qcodes/dataset/experiment_container.py
- qcodes/dataset/json_exporter.py
- qcodes/dataset/legacy_import.py
- qcodes/dataset/linked_datasets/links.py
- qcodes/dataset/measurements.py
- qcodes/dataset/plotting.py
- qcodes/dataset/sqlite/connection.py
- qcodes/dataset/sqlite/database.py
- qcodes/dataset/sqlite/db_upgrades/__init__.py
@jenshnielsen please feel free to improve this as you deem needed (and push to this branch).
> Type all of qcodes.dataset.*

- qcodes/utils/zmq_helpers.py
This is not used in QCoDeS and I don't expect that it will be soon
> Deprecate unused zmq module

- qcodes/dataset/measurements.py
- qcodes/tests/dataset/test_measurement_context_manager.py
Currently writing a complex valued standalone parameter to the db fails when trying to read it back. (See added test). This is e.g. the case for any `do0d`.
It feels that there is a lot of refactoring that can be done in the measurements, while this is only the quick fix.
@WilliamHPNielsen have I interpolated the situation correctly for array valued parameters, i.e. the 'if branch' of the added code?
> Fix error for writing complex valued standalone parameters

- qcodes/tests/dataset/test_paramspec.py
By limiting the sizes of strings generated
as recommended by hypothesis
> Try to fix random failures in tests

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
Because they may not be always gettable due to the nature of those parameters and the instrument. Dicovered when working on #1828
> Avoid getting Keysight B1517A voltage/current parameters upon snapshot

- azure-pipelines.yml
This is a simple PR that makes ~two last steps of "qcodes release process" (from wiki) automatic.
all sorts of improvements to pipelines is out of scope of this PR. Also getting rid of the need for having that "how to release" wiki is also out of scope.
> Add minimal steps to automatically publish qcodes to PyPI

- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
- qcodes/instrument_drivers/QDev/QDac.py
- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
- qcodes/instrument_drivers/signal_hound/USB_SA124B.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_instrument.py
- qcodes/tests/test_parameter.py
This PR takes another approach to #1791 - introducing `_Cache` class which:
- incorporates the `_latest` dictionary with `value`, `raw_value`, and `timestamp` (also `max_val_age`), and 
- `get` method that behaves as `get_latest` and 
- `set` method that behaves as `set_cache` that was introduced in #1757.
This PR subsumes significant part of https://github.com/QCoDeS/Qcodes/pull/1828 but not the improvements to `snapshot_base`.
- `GetLatest` and `get_latest` remain as is for backwards compatibility, but under the hood they reuse `_Cache` and its methods "as-is". In the near future we will be able to deprecate `GetLatest` altogether 
and move our users to use `.cache` only.
- Note that `_Cache.get` as opposed to `get_latest.get` has an additional `get_if_invalid` flag that is useful to …
> Add _Cache to _BaseParameter, use it in GetLatest, remove set_cache method, remove _latest

- qcodes/instrument_drivers/Keysight/Keysight_34410A_submodules.py
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
Add support for the Keysight 34410A DMM into qcodes, and add support for pulling other types of parameter (current and resistance) into the driver.
- Keysight 34410A support
- Support for current, resistance measurements
- Add some missing mypy annotations
> Add Keysight 34410A driver

- qcodes/plots/qcmatplotlib.py
The warning is issues because `colorbar.set_clim` is deprecated. See https://matplotlib.org/3.1.0/api/api_changes.html#colorbarbase-inheritance
@astafan8
> fix warning in matplotlib plotting 

- .travis.yml
packages needed for scipy as there are now wheels for scipy.
The last few packages need to remain until we have 3.8 wheels for h5py
> CI: Travis don't apt-get install

- qcodes/instrument/parameter.py
Question - is this fix correct? :)
> Fix return type of _BaseParameter.__call__

- qcodes/station.py
- qcodes/tests/test_station.py
There has been an error appending the station config files to the log messages if the station config validation has not been successful.
This error has not been caught by the tests, because it is specific to handling real station config files, while the tests work with simple strings.
A test has been added for this edge case.
@QCoDeS/core hotfix for v0.8.1
> Fix error created on logging station config validation

- qcodes/utils/installation_info.py
We're running Qcodes on a lab computer with no internet access. Running `pip list` looks online for the package index. This takes 20 seconds to time out, which makes `start_all_logging()` annoyingly slow. This fixes that.
> Run pip with --no-index in installation_info

- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
Added parameter 'electrical_delay' to rohde_schwarz/ZNB driver. 
Allows to get and set the electrical delay to de-embed the cabel length from the phase signal.
The electrical delay will be added to port2, this is currently hardcoded. When autosetting on the softbuttons on the physical instrument, this seems to be the default option. Also, it does not make a difference (as far as we can see) for the signal.
Added function 'set_electrical_delay_auto'. This function automatically sets the electrical delay to the active port. A wide frequency span during execution of the function leads to more accurate results.
- add parameter electrical_delay in rohde_schwarz/ZNB.py
- add function set_electrical_delay_auto in rohde_schwarz/ZNB.py
@astafan8 …
> add electrical delay parameter and function set_electrical_delay_auto for ZNB driver

- qcodes/instrument/parameter.py
- docstrings of properties
- docstrings formatting
- remove type annotations from docstrings
> Fix docstrings in parameter.py

- .travis.yml
... otherwise travis get swamped with useless build jobs on every commit of every branch on the main qcodes repo.
> Explicitly whitelist branches and tags to build

- qcodes/instrument_drivers/Keysight/keysight_34934a.py
This only works due to small string optimization which is an implementation detail that should not be relied on. Fixes a warning under python 3.8
> keysight 34934a: Don't use is to compare strings

- .pylintrc
Once we know this works we can remove the explicit line endings check from travis
> Check for line ending using codeacy

- qcodes/tests/drivers/test_keithley_s46.py
- qcodes/tests/test_snapshot.py
- qcodes/tests/test_visa.py
This PR tries to get rid of the following warnings in the CI tests run (tick box when the thing dissapears):
```
--- Logging error ---
Traceback (most recent call last):
File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 552, in close_all
inst = cls.find_instrument(inststr)
File "/home/travis/build/QCoDeS/Qcodes/qcodes/instrument/base.py", line 649, in find_instrument
raise KeyError('Instrument {} has been removed'.format(name))
KeyError: 'Instrument Joe has been removed'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/3.7.1/lib/python3.7/logging/__init__.py", line 1036, in emit
stream.write(msg)
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/capture.py", line 427, …
```
> Close instruments properly in tests

- qcodes/instrument_drivers/tektronix/Keithley_2400.py
Fixes 'bugginess' mentioned in #488 
- Added code to ensure Keithley 2400 instrument sends responses to READ? in correct format in the driver __init__ method.
- Modify 'output' parameter to use create_on_off_val_mapping instead of int.
Breaking changes: 'output' parameter type change could possibly break existing code that depends on 'output' being an int.
> fix: Keithley_2400 READ? format may be inconsistent

- docs_requirements.txt
In the mean time 2.3.1 has been released so go with that
> build docs with sphinx 2.3.1

- qcodes/instrument/parameter.py
- qcodes/instrument_drivers/Keysight/keysight_34934a.py
- qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
- qcodes/tests/test_parameter.py
And fix a number of places where this happens. 
In the future this should be an error but it seems safer for now to make it an error.
> Warn if unknown kwargs are passed to _BaseParameter

- qcodes/instrument_drivers/AlazarTech/ATS9870.py
Fixes [#1829](https://github.com/QCoDeS/Qcodes/issues/1829).
The user manual and SDK manual of the driver suggest that both AC and DC coupling on CHA, CHB, and EXT channels are supported by this card. However, the card in Delft does not support AC coupling.
I have contacted the Alazar tech support for this discrepancy. Indeed for external_trigger_coupling only DC mode is supported. This is captured in page 9 of the datasheet and specification page.
The driver is updated so that it does not allow AC coupling anymore.
~~In the meantime, as a solution, the `initial_value` of `external_trigger_coupling` is changed to DC. This also makes more sense till now the user has only used DC coupling.~~
@astafan8 
-  Only the `external_trigger_coupling` is the problematic case, rest is fine.
> AlazarATS9870: Set default external_trigger_coupling to DC 

- pytest.ini
- qcodes/tests/dataset/test_plotting.py
* Hopefully fix flaky test on azure by disabling health check. This seems to likely be due to an old and buggy version of hypothesis shipped by conda. But work around it here by disabling.
* Remove a deprecation warning from pytest by explicitly setting the output format. We stick to the old version as mypy only supports xunit1/junit output and the test uploader only support one type pr upload
> A few CI cleanups 

- environment.yml
- requirements.txt
- setup.py
The issue is reported here https://bitbucket.org/ruamel/yaml/issues/331/incorrect-type-annotations-of-taggedscalar
> Block ruamel.yaml version with broken type annotations

- qcodes/dataset/sqlite/database.py
Often one does
```python
db_location = qc.config["core"]["db_location"]
try:
qc.initialise_or_create_database_at(db_file)
some_operations_here(...)
finally:
qc.config["core"]["db_location"] = db_location
```
this can be replaced with:
```python
with initialised_database_at(db_file):
some_operations_here(...)
```
which is much cleaner!
I am using this in another code, however, @astafan8 recommended me to create a PR 👍
> add initialised_database_at contextmanager

- qcodes/instrument_drivers/tektronix/Keithley_2450.py
- add reset() method to the main module,
- add nplc parameter to the sense module,
- add user delay to the sense module,
- add delay, user delay, and auto delay setting to the source module.
The newly added user delay to both sense and source module can be used in the trigger model. However, the trigger model does not exist in the qcodes driver yet. So my next step is to write the trigger module for the driver, and a new example notebook for how to perform triggering.
Speaking of example notebook, the new features added in the PR do not really fit in the existing example notebook (methods like the reset() are well self-explained). I'll try to include as many as I can in the upcoming example notebook for trigger module.
@sohailc
> Add new features to keithley 2450

- qcodes/utils/installation_info.py
There are times where this is broken https://github.com/pypa/pip/issues/5599 and either fails to work or prints a warning. This currently happens in ci with pip from conda
> Avoid calling pip script

- qcodes/tests/drivers/test_lakeshore_325.py
This is needed for compatibility with hypothesis 550 and currently causes mypy to fail with hypothesis >= 0.550
> Convert hypothesis args to kwarg

- qcodes/instrument/base.py
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
This change implements a fix to the 344xx driver that stops the DMM from cycling through all its measurement modes on a snapshot/initialization.
- Don't include measurements in a snapshot that would cause the measurement mode to change.
- Make ask abstract in the AbstractInstrument class to fix a bunch of pylint errors.
> Improvements to 344xx driver

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
For some reason they were missing
> Keysight B1500: Add units to current/voltage parameters to B1571A SMU module

- qcodes/instrument/sims/Keysight_34465A.yaml
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
- qcodes/tests/drivers/test_keysight_34465a.py
In case the DMM tries to measure the voltage value outside the its range, it overloads and throws 9.9e37 instead of throwing an error. Here we substitute this number with np.nan. 
Side note: The error query does not throw any error even though the instrument display shows in bold that instrument is overloaded. 
To reproduce the error: 
> Fix: Keysight_34465A overload value 9.9e37 to be np.inf instead

- .gitignore
PR #1613 accidentally modified the `.gitignore`. This PR undoes that modification.
@Dominik-Vogel
> Remove superflous lines from gitignore

- docs/changes/0.12.0.rst
- qcodes/station.py
These see little use and are using the old dataset
> Deprecate default measurement

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
As promised in the warning message
> make it an error to overwrite get in a parameter

- docs/conf.py
Current release does not include .binder folder that contains requirements to run the notebooks through binder. Until next release we point the binder to create the environment for notebooks from master instead of the latest release. We do not want to keep this is as a permanent solution because pointing to master would lead to creation of docker image each time a new commit is made which is a very slow process. After next release we will revert back to creating docker image from latest release.
> Binder: Point to master instead of latest release

- qcodes/tests/test_hdf5formatter.py
Setting it to the current default and not the new one should give the same behaviour as always
> h5py tests: silence warnings about changing default by setting mode explicitly

- environment.yml
- test_requirements.txt
To prevent a large number of warnings about using function scope fixtures. 
Its not clear at the moment how to best avoid these
and open issues may result in changes https://github.com/HypothesisWorks/hypothesis/issues/2370
So lets limit this for now
> limit hypothesis version

- qcodes/station.py
- qcodes/tests/test_json.py
- qcodes/tests/test_station.py
- qcodes/utils/helpers.py
This was falling back to `str() repr` which is not great for reloading. This fixes that by serializing the data member of the userdict which is a regural dict
> Better snapshot of station.config (and other UserDicts)

- mypy.ini
- qcodes/instrument_drivers/Keysight/Keysight_34410A_submodules.py
- qcodes/instrument_drivers/Keysight/Keysight_34460A_submodules.py
- qcodes/instrument_drivers/Keysight/Keysight_34461A_submodules.py
- qcodes/instrument_drivers/Keysight/Keysight_34465A_submodules.py
- qcodes/instrument_drivers/Keysight/Keysight_34470A_submodules.py
- qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
These simply match the types in the base class. So it seems like a good idea to add them to ensure that the end user can get type checking
> add types to init functions of concrete keysight drivers

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
Coerce coefficient for nplc settings to int.  B1500 does not update integration time if it receives a non-int value.
@astafan8
> Keysight B1500: Coerce nplc to integer

- qcodes/tests/dataset/temporary_databases.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_sqlite_base.py
- qcodes/tests/test_config.py
- qcodes/tests/test_station.py
This should prevent the unable to unlink tmpdir because pytest has a reference to it failures that we see from time to time. https://docs.pytest.org/en/latest/tmpdir.html#temporary-directories-and-files
There are 3 context managers that I have still not changed. These should probably eventually be rewritten as pytest fixtures. 
The pytest fixtures will only create one tmp_path pr test so in tests that requires 2 distinct directories I have used the factory functions to generate another one
> Use pytest fixtures for tmp dir creation in tests

- test_requirements.txt
This version produces ImportError on collection of module (`pylint` issue https://github.com/PyCQA/pylint/issues/3524 )
> Do not use Pylint version 2.5.0 

- qcodes/tests/test_slack.py
- qcodes/utils/slack.py
The slack module generates an error when retreiving the latest timestamp if a user has not posted any messages. This PR assigns a None value in that case.
@astafan8
> fix for slack module when a user has not send any messages

- qcodes/instrument/parameter.py
- qcodes/tests/test_delegate_parameter.py
Otherwise issues may arise if the source is remapped
> Delegateparam ensure that cache matches source parameter

- qcodes/tests/test_doNd.py
This PR make the proper changes in tests of doNd utility so that temporary databases are used.
This change is necessary for parallel processing of tests.
@jenshnielsen
> Use temporary databases and files in doNd tests

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1500_module.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1520a_cmu.py
This PR fixes following 2 issues:
1) is_enabled functions was giving error when called before enabling channels. This is fixed by checking if activated_channels is not empty string. 
2) Adds get_cmd to voltage_dc, voltage_ac, frequency
The above two fixes allows user to use the `step` attribute of the parameter to slowly raise/decrease a parameter. Before these fixes the user was getting warning that parameter is jumping to designated value because starting value of the parameter is not found is there was no get_cmd available. 
@astafan8 @jenshnielsen
> Add get_cmd for voltage_dc, voltage_ac and frequency in KeysightB1520A

- qcodes/tests/test_delegate_parameter.py
A test wrapped in a class like this will never run
> Fix delegate parameter test that would never run

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
It makes no sense to both implement get_raw and supply a get_cmd. Which one should be used. So lets make this an error. There are already 2 subclasses that does the same. DelegateParameter and GroupParameter
> make it an error to supply get/set_cmd if get/set_raw is not abstract

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
This IMHO makes the logic a bit more clear. Functinality it should be the same. 
I have changed a case in the if/else statments that should never happen to an error from silently returning a not up to date value.
> Refactor parameter cache.get

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
Comparing strings with `is` only works due to an implementation detail (small string optimization)
> fix warning in b1500 driver

- qcodes/instrument/parameter.py
- qcodes/tests/test_delegate_parameter.py
- qcodes/tests/test_parameter.py
Similar to `initial_value` kwarg, but `initial_cache_value` will call `self.cache.set`.
ToDo:
> Add initial_cache_value kwarg to Parameter

- qcodes/instrument/base.py
- qcodes/instrument/channel.py
- qcodes/instrument/ip.py
- qcodes/instrument/parameter.py
- qcodes/instrument/sweep_values.py
- qcodes/instrument/visa.py
- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/stanford_research/SR86x.py
- qcodes/loops.py
- qcodes/measure.py
- qcodes/station.py
- qcodes/tests/instrument_mocks.py
- qcodes/tests/test_loop.py
- qcodes/tests/test_parameter.py
- qcodes/tests/test_snapshot.py
- qcodes/utils/metadata.py
`_BaseParameter.snapshot_base` has been refactored to use `cache` and rely on `cache.get`.
It has gaied a third value for update such that `update=True` means unconditionally update the cache. `update=None` means update if known to be out of date and `update=False` meas do not ever try to update the underlying value. It is the intention that `update=None` should become the default in many places but that will happen in a diffrent pr.
- Note that `_BaseParameter._snapshot_get` is passed to `cache.get` via this new `get_if_invalid` flag.
- `_BaseParameter.snapshot_base` got it's own set of parametrized set of tests so that its current behavior is captured (to the best of my abilities)
> Snapshot_base introduce new update=None, and use cache in parameter's snapshot_base

- qcodes/tests/test_metadata.py
- qcodes/utils/metadata.py
Hi,
Currently, `metadata.diff_param_values` allows only diffing snapshots genearated for datasets. It assumes the snapshots have the keys `"station"` and inside that `"instruments"`.
This PR allows diffing snapshots generated by Stations and Instruments. It only assumes that `"parameters"` is found in the snapshot. 
For example this works:
```
before = dummy_instrument.snapshot()
dummy_instrument.dac1(3)
after = dummy_instrument.snapshot()
diff_param_values(before, after)
```
This allows more flexible use of the diff tool.
Also included some new tests to check the different cases.
@jenshnielsen
> Allow diffing snapshots of stations and instruments

- qcodes/instrument/parameter.py
- qcodes/tests/test_parameter.py
* Make gettable/settable readonly as they always should have been
* Raise if you somehow manage to call get/set on a non gettable/settable parameter. This should never happen if only the public api is used.
> Make gettable/settable a read only property and raise

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1520a_cmu.py
For an unknown reason the get_capacitance method was checking for dtype to be of 'Y'. However, the impedance model does not allow the secondary parameter to be 'Y'.
This PR removes this check. 
Also if ac_dc_volt_monitor is on then the length of output (primary parameter, secondary parameter, ac voltage, dc voltage) is 4 instead of 2. 
This is quick fix. A better capacitance parameter would be which also sets proper labels and units depending on the impedance model. This is already planned and will be taken up in another later.
@astafan8
> B1500: Fix spot measurement of capacitance checking for wrong impedance model, and working with ac_dc_volt_monitor=True

- .gitattributes
As suggested here https://www.edwardthomson.com/blog/git_for_windows_line_endings.html
I had this problem again for some reason on #2005
> make sure that new lines are handled correctly on windows

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1500_module.py
Keysight B1500 responds with a string containing decimal numbers but with signs on both sides of the decimal. For ex: '-0.-1' this PR add function to covert such strings to float.
Once this is fixed in Keysight firmware the commits in this PR can be reverted.
> B1500: Transient fix for converting str as '-0.-1' to float 

- qcodes/instrument_drivers/agilent/E8527D.py
We had this commit lying around, I think it's a bit cleaner this way.
@astafan8
> Agilent E8527D: Use on_off_val_mapping instead of custom parser

- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/zurich_instruments/__init__.py
- qcodes/instrument_drivers/zurich_instruments/hdawg.py
- qcodes/instrument_drivers/zurich_instruments/mfli.py
- qcodes/instrument_drivers/zurich_instruments/uhfli.py
- qcodes/instrument_drivers/zurich_instruments/uhfqa.py
- setup.py
This PR add support for Zurich Instruments devices as drivers inside of QCodes.
The actual implementation is in https://github.com/zhinst/zhinst-qcodes/ as described in
https://blogs.zhinst.com/andrea/2020/05/24/control-your-measurements-with-qcodes-and-labber/
Here we propose to add stubs in Qcodes to help user to find and install such drivers.
We propose deprecation of the existing ZIUHF, since its functionality is replaced by this PR.
A new optional installation option, 'ZurichInstruments' is introduced. That add the package zhinst-qcodes as optional dependency of Qcodes, if the user wish so. 
@jenshnielsen
> Add Zurich Instruments drivers 

- qcodes/tests/dataset/test_dataset_basic.py
In `test_parent_dataset_links_invalid_input` we have seen ocational falilures since the merge of #2016 
I suspect this is due to the links and dataset being created within the same ms and therefore having the same guid. This extra assertion will confirm or disprove this hypothesis
> ensure that links and dataset does not share guid before testing

- qcodes/tests/dataset/test_links.py
https://travis-ci.com/github/QCoDeS/Qcodes/jobs/346553423 confirms that the issue is indeed due to timestamp collisions so lets ensure that links are generated with a timestamp in the past
> generate links with a timestamp in the past to avoid collisions

- qcodes/tests/dataset/test_database_extract_runs.py
- qcodes/tests/dataset/test_measurement_context_manager.py
- qcodes/tests/test_snapshot.py
Use a fixture for an instrument that otherwise triggers an error in tear down of the tests. 
Rename 3 test instruments so they have unique names.
> Slight improvements to test fixtures

- qcodes/tests/test_plots.py
I have occasionally seen this fail with issues related to tk/tcl. Since there is no need for a gui in this test lets not depend on it
> Use non interactive matplotlib backend in test

- qcodes/loops.py
- qcodes/station.py
- qcodes/tests/test_loop.py
- qcodes/tests/test_station.py
> Remove deprecated default measurement from station

- qcodes/tests/test_hdf5formatter.py
- qcodes/tests/test_instrument.py
Rewrite instrument tests to use pytest only (no Unittest.testcase) and ensuer that all instrumentes are clossed probably. 
This fixes some warnings during test teardown for me. Also explicitly close some instruments in hdf5 tests to fix more warnings
> Cleanup instrument tests

- qcodes/monitor/monitor.py
- qcodes/tests/test_monitor.py
I ocationally get failurs related to ports not beeing available when setting up the monitor tests locally. This seems likely to be due to the tests not probably closing down their websockets if interrupted so I have rewritten the tests using pytest fixtures and finalize to hopefully make this more robust.
> rewrite monitor tests with pytest

- qcodes/dataset/measurements.py
* Use Sequence for parent_datasets not List. This makes it clear that parent_datasets is not modified and avoid mutable default argument.
* Use Mapping for another input argument to make it clear that this is not mutable.
> Measurements.py Sligth improvments to types

- qcodes/instrument_drivers/Keysight/keysightb1500/message_builder.py
- qcodes/instrument_drivers/ZI/ZIUHFLI.py
- qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
This PR deprecates the use of "slave" as an argument name for a function and as a class name and variable name for magnet power supplies. We have one un-addressed master/slave reference in the code, but that is in `versioneer.py`, which should be addressed upstream.
I have played it safe by deprecation, but perhaps we can more aggressively simply remove/rename?
@QCoDeS/core
> Remove slave master references

- docs/conf.py
- docs_requirements.txt
- qcodes/data/data_set.py
- qcodes/instrument/channel.py
- qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
- qcodes/instrument_drivers/signal_hound/USB_SA124B.py
* Move some attibute docs inline so that we avoid duplicate entries and failures resulting from that.
* Disable nitpicky. Sphinx now tries to resolve all types to links. It does not seem meaningful to fix all of these
Also updated two intersphinx links. Python 3.6 -> 3.7 and redirect of numpy docs
> Build docs with Sphinx 3

- qcodes/tests/common.py
- qcodes/tests/dataset/test_guids.py
- qcodes/tests/dataset/test_subscribing.py
- qcodes/tests/test_config.py
- qcodes/tests/test_generic_formatter.py
- qcodes/tests/test_plot_utils.py
- qcodes/tests/test_station.py
The context manager used to protect the config in the guid tests that overwrites home config was insuffisient as it did not relocate the home config. Use the default_config config manager instead that does this correctly. 
In the process of debugging this issue I found that `test_generic_formatter` cannot be run standalone so fix that too. 
Since we use the `default_config` context manager in multiple locations I also moved that to a common location
> Fix guid tests overwriting home config

- qcodes/tests/common.py
- qcodes/tests/test_logger.py
- setup.py
To be released very soon (rc1 is out) 
This changes the logger slightly so that there are now 2 default loggers for pytest. 
It also adds types to pytest :) So fix one error related to that
> Add support for pytest 6

- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_sampling_measurement.py
- qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1500_module.py
- qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_sampling_measurement.py
Instead of passing dummy value 199.999e99 due to power compliance being reached in sampling measurements or measurement being aborted, NaN value is output.
Some relevant lines from Manual:
"Measurement data is over the measurement range. Or the sweep measurement was aborted by the automatic stop function or power compliance. D will be 199.999E+99 (no meaning)."
"The B1500 returns the data measured before any abort condition is detected. Dummy data 199.999E+99 will be returned for the data after abort."
@astafan8 @jenshnielsen
> B1500: Output NaN instead of 199.999e99

- qcodes/logger/logger.py
Currently telemetry only captures messages which are not formatted to contain logger name and other things. Here we make it similar to logging of file handler and console handler
@jenshnielsen
> Add formatting to the log messages of Telemetry

- README.rst
Update the zenodo DOI to point to the latest release.
@astafan8
> Update zenodo DOI to 0.16.0

- qcodes/utils/helpers.py
In the spyder environment for each new console a message is printed about the site kernels. This PR converts the message to a logging statement and adds the text spyder to make it more informative
@astafan8
> Fix: convert spyder kernels site print statement to logging message

- qcodes/utils/plotting.py
Unfortunatly this code relies on private details of the matplotlib colorbar. In 3.3 `_slice_dict` no longer exists. See #2087 
To simplify this I have simply copied `_slice_dict` into the function. 
I also took the chance to do a bit of cleanup of the types in this file
> Add support for matplotlib 3.3

- qcodes/station.py
- qcodes/tests/test_station.py
Orginal issue:
```yaml
my_qwe:
type: foo.bar.Qwe
init:
...
```
```python
from qcodes.instrument.base import Instrument
class Qwe(Instrument):
def __init__(some_arg, name, ...)
super().__init__(name, ...)
....
```
```python
my_qwe = station.load_instrument('my_qwe', some_arg='some_value')
```
This PR solves this issue. (inspired by https://github.com/qdev-dk/qdev-wrappers/blob/master/qdev_wrappers/station_configurator.py#L164)
Also:
> Station: Pass name as kwarg so that its order in instrument class is not relevant

- qcodes/dataset/data_set.py
- qcodes/dataset/measurements.py
- qcodes/tests/dataset/test_datasaver.py
- qcodes/tests/dataset/test_string_data.py
First step in creating a more clean interface between the dataset and the datasaver
> Move write cache to from datasaver to dataset

- test_requirements.txt
Will hopefully fix the test failure in #2114
> limit pytest xdist to version 1.x

- qcodes/dataset/data_set.py
- qcodes/dataset/measurements.py
Forgot this one in the code review of #2112
> mark flush as private

- qcodes/utils/plotting.py
Newer versions of matplotlib warn that it will be an error to modify a global colormap in the future. So lets not do that
> fix matplotlib deprecation warning

- qcodes/instrument/base.py
- qcodes/instrument/ip.py
Currently `__del__` first tries to remove the instrument from the instances list and then calls close which does the same + more.
It seems better to just call close. This also enables us to get rid of a subclassing of `__del__` in IPInstrument that does just that
> Simplify instrument destructor

- qcodes/instrument/group_parameter.py
- qcodes/tests/parameter/test_group_parameter.py
- Raise exception if get_cmd not defined for a group of parameters 
@jenshnielsen
> Raise exception if get_cmd not defined in a group

- qcodes/instrument_drivers/rohde_schwarz/ZNB.py
As of https://github.com/QCoDeS/Qcodes/pull/1493, this warning seems redundant. We've checked in an experiment that the measured complex values get stored and can be read out/plotted properly.
@astafan8
> Remove warning about complex numbers in R&S ZNB driver

- .travis.yml
used to build h5py which now has wheels for python 3.8
> Remove no longer needed apt deps from travis

- setup.py
As https://github.com/QCoDeS/Qcodes/pull/2161 reveals that there are some potential issues with this release
> restrict pyvisa to less than 1.11

- .travis.yml
This should make incorrect dependencies such as https://github.com/QCoDeS/Qcodes/pull/2166 a hard error.
The new resolver is documented [here](https://pip.pypa.io/en/stable/user_guide/#resolver-changes-2020) and will 
be the defaul in the future
Along with a few more cleanups along the way
* Don't install cython (this is no longer needed as we have all the wheels already)
* Don't pass upgrade to test requirements install. This is not needed as we specify dependencies already
* Ensure setuptools and wheel is up to date
> Use Pips new resolver when installing dependencies

- setup.py
Because of the Python >=3.7 requirement.
> remove dataclasses requirement

- setup.py
Since it is not used directly by qcodes
> remove pyzmq from dependencies in setup.py

- qcodes/instrument_drivers/Keysight/keysight_34980a.py
Removes a tab `\t` that has been mixed in accidentally.
> remove tab character

- requirements.txt
- setup.py
@astafan8  It seems like dependabot does not touch lines with environmental markers
> allow importlib metadata 2

- .pre-commit-config.yaml
As a followup from https://github.com/QCoDeS/Qcodes/pull/1945.
This adds pyupgrade as pre-commit filter.
This PR is blocked by
- #2201
- #2202
- #2203
- #2204
- #2205
- #2206
- #2207
- #2208
- #2209
- #2210
- #2211
> add pyupgrade to pre-commit

- qcodes/__init__.py
These imports are only useful with the legacy dataset. So it would seem natural that they are also only imported if legacy import is set,
> move matplot and qtplot to legacy import

- qcodes/tests/dataset/test_paramspec.py
Some of the branches in ParamSpecs implementation of `__eq__` seem to flip between being covered and not causing jobs like https://github.com/QCoDeS/Qcodes/pull/2260 to report a drop in coverage.
This is probaby because hypothesis may or may not generate input that covers all of them. This pr adds explicit tests for all 3 failure branches
> add explicit tests for paramspec equality

- qcodes/dataset/data_set.py
- qcodes/dataset/data_set_cache.py
- qcodes/dataset/database_extract_runs.py
- qcodes/dataset/descriptions/dependencies.py
- qcodes/dataset/descriptions/detect_shapes.py
- qcodes/dataset/descriptions/rundescriber.py
- qcodes/dataset/descriptions/versioning/converters.py
- qcodes/dataset/descriptions/versioning/rundescribertypes.py
- qcodes/dataset/descriptions/versioning/serialization.py
- qcodes/dataset/measurements.py
- qcodes/dataset/sqlite/queries.py
- qcodes/tests/dataset/conftest.py
- qcodes/tests/dataset/test_converters.py
- qcodes/tests/dataset/test_database_creation_and_upgrading.py
- qcodes/tests/dataset/test_dataset_basic.py
- qcodes/tests/dataset/test_descriptions.py
- qcodes/tests/dataset/test_detect_shape.py
- qcodes/tests/dataset/test_doNd.py
- qcodes/utils/dataset/doNd.py
Add shape information that can optionally be set for a dataset and extend dond functions to set this when generating a measurement. 
TODO:
> Add optional shape metadata to dataset 

- test_requirements.txt
* the codecov python package is unused since we upload with the github action
* Asv is no longer used in CI
> Cleanup test dependencies

- qcodes/tests/validators/test_sequence.py
- qcodes/utils/validators.py
sorted(Sequence) always returns a list so the previous comparison would be incorrect if the input sequence is not a list.
This fixes that by always casting to a tuple on both sides. 
Also add some basic tests for the sequence validator that was missing
> Fix sequnce validator for with sorted = True 

- qcodes/instrument_drivers/AlazarTech/ATS9373.py
- qcodes/instrument_drivers/AlazarTech/ATS9870.py
Fix two small issues.
In 9870 driver i is a string that can be either '1' or '2' so compare it against that and not the number 0
In 9373 driver correct a typo (wrong model number) in error message
> correct 2 small typos in alazar drivers

- test_requirements.txt
We are currently not using pylint in ci so no need to install it. 
Pylint is used via codecov
> remove pylint and its deps from test_requirements

- docs_requirements.txt
Due to the way these files were introduced the required version of zipp between them has gone out of sync. It seems like dependabot does not correct this (but will keep them in sync) so fix this manually
> sync dependency of zipp here with other reqirements files

- qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
This PR is to fix the following warning message that was seen during testing with the Keithley 2600 SMU
`c:\users\redlabq\repositories\qcodes\qcodes\instrument\visa.py:212: UserWarning: write message already ends with termination characters
nr_bytes_written, ret_code = self.visa_handle.write(cmd)`
The visa handle already end with termination character so passing in `\n` is not needed in the message
> Keithley 2600: remove new line char in visa_handle.write

- qcodes/logger/logger.py
seems to work, as in, opencensus warnings don't show up in console while others do show:
> Filter out telemetry messages in console handler

- qcodes/.coveragerc
While we don't have good coverage for these I do not see that as a reason to not measure coverage of them
> Don't exclude instrument drivers from codecov

- qcodes/instrument_drivers/QDev/QDac_channels.py
- qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
These two drivers have their own write routine that also needs update to support pyvisa 1.11
This was not found since the code is not type checked by mypy yet (I will add that later in another pr) 
@trevormorgan
> Qdac drivers: Don't check return from visa write

- qcodes/instrument_drivers/Keysight/Infiniium.py
- qcodes/instrument_drivers/Keysight/KeysightAgilent_33XXX.py
- qcodes/instrument_drivers/Keysight/Keysight_B2962A.py
- qcodes/instrument_drivers/Keysight/Keysight_N6705B.py
- qcodes/instrument_drivers/Keysight/N51x1.py
- qcodes/instrument_drivers/Keysight/N5230C.py
- qcodes/instrument_drivers/Keysight/N5245A.py
- qcodes/instrument_drivers/Keysight/N52xx.py
- qcodes/instrument_drivers/Keysight/keysight_34934a.py
- qcodes/instrument_drivers/Keysight/keysight_34980a.py
- qcodes/instrument_drivers/Keysight/keysight_b220x.py
- setup.cfg
Missing b1500 and SD_common module
SD_common module is unused in qcodes and should removed. It has been copied to qcodes_contrib_drivers along with the drivers using it
> Add types to keysight drivers

- setup.py
The constants used in device_clear are only avilable in 1.11
> Require pyvisa 1.11.1 as a minimum

- CONTRIBUTING.rst
- docs/help.rst
- setup.py
Update to new qcodes support distribution list email.
@jenshnielsen these were the only references I could find. Do you know if there are any others floating around in the docs?
> Update contact to new qcodes alias 

- qcodes/dataset/data_set.py
- qcodes/tests/dataset/test_dataset_basic.py
The code would try to remove a non existing element from a set. 
Fix this by both checking for the element first and never do the complete action for an already complted ds
Basic test included
@liangosc
> Fix error when calling mark_complted twice

- setup.cfg
We are not and have not for a long time been using nose to run our tests so lets remove it from setup.cfg
> remove nose config from setup.cfg

- qcodes/__init__.py
- setup.cfg
This way a module must explicitly be marked as not typed. This should help ensure that all new code is marked typed.
And add the remaing types to `__init__.py`
> Reverse logic for which modules are typed

- qcodes/instrument_drivers/ithaco/Ithaco_1211.py
The measurement context manager does not support measureing Multiparameters that do not have setpoints defined. So explicitly define the setpoints of this Multiparameter as empty (since the values are scalar)  @FarBo
> Fix Ithaco CurrentParameter so it can be measured correctly

- azure-pipelines.yml
For whatever reason Azure jobs on windows are sometimes subject to slowdown and timeout just before the job is done. To try to work around that this pr increases the timeout from 60 min to 90 min.
An example can be seen here https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=18670&view=logs&j=45dcd969-b885-5520-9571-e72cfd95beb6
> set higher timeout for Azure jobs

- qcodes/instrument_drivers/agilent/E8527D.py
As a result of #2030, querying the value of the `status` parameter causes an exception, because  without specifying the terminator, the query returns `"1\n"` or `"0\n"`, which the val_mapping doesn't accept. This fixes that. Sorry for not testing this properly before.
@astafan8
> Add default terminator for Agilent E8527D

- qcodes/utils/helpers.py
This PR fixes unwanted logging messages at INFO and DEBUG levels in the Spyder's console.
> Removed logging.info message from spyder part of helpers.py

- qcodes/configuration/config.py
- qcodes/data/data_set.py
- qcodes/station.py
- setup.cfg
The last few changes required to enforce disallow_any_generics  outside drivers and tests.
This requires Sub classing generic types. It seems like there is no Generic UserDict so I have replaced it with a regular dict. According to the documentation of UserDict there is no strong reason to use this anymore. It is perfectly ok to subclass a regular dict
> No implicit any generics outside drivers and tests

- setup.py
Fix for #2460 
It seems that dependabot has an issue with env markers that prevents it to bump the dependency correctly
> fix setup.py importlib metadata version
