microsoft/Qcodes

LICENSE.rst
README.rst

Renamed LICENSE to LICENSE.rst and fixed the link in README.rst

Changed license to .rst

---

docs/examples/Qcodes example with Decadac.ipynb
qcodes/instrument_drivers/Harvard/Decadac.py

Adds a driver for Decadacs
- Adds very basic decadac functionality: the ability to set, get, and ramp voltages.
- Small ipython notebook example included
Changes planned for the future:
- Implement arbitrary waveform generator functionality
- Make two channels mergeable into one
- Enable calibration

Feature: decadac driver

---

qcodes/data/data_set.py
qcodes/data/format.py
qcodes/data/gnuplot_format.py
qcodes/data/hdf5_format.py
qcodes/tests/data_mocks.py
qcodes/tests/test_format.py

Update docs of formatter, write metadata by default, pass arguments

---

qcodes/instrument_drivers/rohde_schwarz/SMR40.py

Update of #386
@giulioungaretti @core

adds microwave source driver SMR40

---

docs/roadmap.rst
docs/start/index.rst
docs/user/intro.rst
docs/user/tutorial.rst
qcodes/data/data_set.py
qcodes/data/format.py
qcodes/instrument/mock.py
qcodes/instrument/parameter.py

A few small RST syntax related issues I found last week reading the docs

Doc: RST fixes

---

qcodes/instrument_drivers/QuTech/IVVI.py

- better variable name
- add term character setting;
- replace version function with dummy

updates to IVVI driver

---

.travis.yml

Currently the docs don't build on travis because sphinx isn't installed. Fix that

Travis: install sphinx for docs build

---

.travis.yml

Travis: install coverage

---

.travis.yml

Travis: Ensure coverage is excluded with pytest

---

qcodes/data/hdf5_format.py

fix argument type of hdf5 formatter write_metadata function

---

qcodes/data/hdf5_format.py
qcodes/tests/test_hdf5formatter.py

Fixes #442 
@unga @AdriaanRol @core

fix for hdf5 formatter metadata

---

qcodes/data/io.py

fix: Removed unused code

---

qcodes/config/config.py
qcodes/config/qcodesrc.json
qcodes/config/qcodesrc_schema.json
qcodes/data/location.py
qcodes/tests/test_location_provider.py

The counter should be on by default
Use the config option for the default formatter.

fix: Use the defaults that were actually requested

---

requirements.txt

feature: Update matplotlib and numpy

---

qcodes/instrument_drivers/tektronix/AWG5014.py
qcodes/instrument_drivers/tektronix/AWG520.py

Fix two remaining rst syntax errors

Fix: docs AWG* fix rst

---

docs/conf.py

This makes docs build slightly less verbose. I am not sure if intersphinx is used at all

Correct some Intersphinx links

---

qcodes/instrument_drivers/rohde_schwarz/SGS100A.py

Cherrypicked from #400 where it doesn't belong @nataliejpg

SGS100A Change lower limit of freq allowed to 1 MHz

---

qcodes/instrument_drivers/american_magnetics/AMI430.py

change instrument type to IPInstrument
Append _connect to flush welcome message of the AMI 430 programmer
@Rubenknex

Fixes to AMI430 driver

---

qcodes/config/config.py

Closes #519
@eendebakpt does this fix your issues ?

fix: Recursively update the configuration object

---

qcodes/instrument_drivers/QDev/QDac.py

Fix a bug that occured if a QDac ramp was interrupted. Also enable a debugmode.
This is needed at QDev T10.
- Make the voltage ramper base it's calculation on a `get` command
- Enable a logging of everything written to the QDac
@jenshnielsen

fix: Make QDac ramp interruption-safe

---

qcodes/instrument_drivers/QDev/QDac.py

Cancel any voltage ramp with a duration less than 2 ms, since this can
cause undefined spurious voltages to be output.
@jenshnielsen

fix: Protect QDac from voltage jumps

---

docs/examples/benchmarking/QDac and Keysight 34465 sync and buffer.ipynb
qcodes/instrument_drivers/Keysight/Keysight_34465A.py
qcodes/instrument_drivers/QDev/QDac.py

WIP: Make a benchmark of the QDac and DMM fast measurement scheme. This PR includes necessary changes to drivers.

benchmark/QDac and Keysight DMM

---

qcodes/instrument_drivers/american_magnetics/AMI430.py

Fixes some wrong field parameter orders

fix: fixed spherical field order

---

.gitignore
docs/Makefile
docs/conf.py
docs/examples/Combined Parameters.ipynb
docs/examples/Datasaving examples.ipynb
docs/examples/Metadata with instruments.ipynb
docs/examples/Metadata.ipynb
docs/examples/Qcodes example with Keysight 33500B.ipynb
docs/examples/Qcodes example with ZI UHF-LI.ipynb
docs/examples/Qcodes location-format example.ipynb
docs/examples/Tutorial.ipynb
docs/examples/benchmarking/QDac and Keysight 34465 sync and buffer.ipynb
docs/examples/driver_examples/Qcodes example ATS_ONWORK.ipynb
docs/examples/driver_examples/Qcodes example with Agilent 34400A.ipynb
docs/examples/driver_examples/Qcodes example with Decadac.ipynb
docs/examples/driver_examples/Qcodes example with Ithaco.ipynb
docs/examples/driver_examples/Qcodes example with Keithley 2600.ipynb
docs/examples/driver_examples/Qcodes example with Mercury IPS (Magnet).ipynb
docs/examples/driver_examples/Qcodes example with QDac.ipynb
docs/examples/driver_examples/Qcodes example with Rohde Schwarz ZN20.ipynb
docs/examples/driver_examples/Qcodes example with Triton.ipynb
docs/examples/index.rst
docs/index.rst
docs/user/tutorial.rst
qcodes/instrument_drivers/tektronix/Keithley_2400.py

Add example notebooks to docs.
* Convert notebooks to rst as part of docs build and include in docs.
* For the notebooks to be cleanly imported they need exactly one 1 level header so change them all to have that. 
* Mock the Zi so it's driver docs can be build.
* Few other small docs fixes
In general many of these notebooks needs some work. Either deleted, expanded or just checked for errors.
@QCoDeS/core

Doc fixes and notebooks

---

.travis.yml

Fix build of docs following #569

Fix: install pandoc on travis to convert notebooks

---

qcodes/plots/base.py
setup.py

Make a couple of methods static and block a broken version of ipykernel

Small changes cherrypicked from qdev-dk version 

---

.travis.yml

chore: add to 3.6

---

requirements.txt

In practice this is what we will get using anaconda on qcodes-dk anyway so the dev deps might as well match it

Bump h5py and numpy versions

---

qcodes/instrument_drivers/oxford/mercuryiPS.py

@MerlinSmiles It seems to me like the easiest way to ensure that the magnet is stable is to wait for it to go into hold more before moving on. Do you see any issues with this

Mercury iPS make it possible to block on set until the magnet is in hold mode

---

docs/examples/driver_examples/Qcodes example with Keysight 33500B.ipynb
qcodes/instrument_drivers/Keysight/Keysight_33500B.py

Add trigger and burst mode options. Also add error message retrieval and
a notebook documenting the new features.
- Add trigger options
- Add burst mode options 
- Add error handling
@giulioungaretti @jenshnielsen

driver/Improve Keysight 33500B driver

---

.travis.yml

- 
- 
- 
@mention one core developer

Fix correct repo slug

---

.travis.yml

Still trying to get the travis logic right

Travis also check that this is not a pr

---

.travis.yml

At some point i might manage to get this right 😡

Travis Fix rebase gone wrong

---

specs/DataSet.rst

- Added the ability to modify an existing result in a DataSet, as requested on Slack by Adriaan Rol.

Added methods to modify results within an in-progress DataSet

---

qcodes/instrument_drivers/tektronix/Keithley_2400.py

Fixes #inf + 1.
- Fix depreached units in Keithley 2400 driver
@core

fix: units to unit

---

qcodes/instrument_drivers/Spectrum/M4i.py

@giulioungaretti @WilliamHPNielsen @jenshnielsen

allow for post_trigger buffer to be set in block reads; add check on buffer size

---

qcodes/instrument_drivers/oxford/mercuryiPS.py

@WilliamHPNielsen as seen by t10

Fix: mercury ips correct typo

---

requirements.txt
setup.py

Also make setup.py and requirementes.txt match
Purely bug fixes

Feature: Bump matplotlib version

---

qcodes/instrument/base.py
qcodes/tests/instrument_mocks.py

Multiparameters do not have a unit but a units tuple so handle that
Also just fix save_val for instrument mocks discovered when fixing this

Handle multi parameters in print_readable_snapshot

---

qcodes/tests/test_validators.py
qcodes/utils/validators.py

- validator for dictionary type objects
- includes test
@jenshnielsen

validator for dictionaries

---

qcodes/instrument_drivers/Spectrum/M4i.py

@giulioungaretti @WilliamHPNielsen @jenshnielsen

add printing of error message for M4i

---

qcodes/tests/test_validators.py
qcodes/utils/validators.py

@jenshnielsen @WilliamHPNielsen 
This solves the bug where a numpy boolean type is rejected by the boolean validator.

Also support numpy boolean type in validator

---

qcodes/utils/slack.py

@jenshnielsen @nulinspiratie
-    Add a custom SlackTimeoutWarning so one can filter the slack timeout messages
-    Make the default error logging less verbose
-    Add one more type of error to the except

better warning handling for slack class

---

qcodes/instrument_drivers/yokogawa/GS200.py

units -> unit, probably just got missed at some point and not even really a 'fix'
@jenshnielsen

fix: units -> unit on GS200 voltage

---

qcodes/instrument/base.py

respect update

---

qcodes/instrument_drivers/Keysight/Keysight_34465A.py

Keysight dmm pretrigger sample count is only avail with DIG option

---

docs/api/public.rst
qcodes/__init__.py
qcodes/config/qcodesrc.json
qcodes/config/qcodesrc_schema.json
qcodes/utils/helpers.py

Import plotting lib

---

qcodes/instrument/parameter.py

@WilliamHPNielsen @jenshnielsen

add increment function to parameter

---

qcodes/instrument_drivers/QuTech/IVVI.py

add function to round float to dac resolution

---

qcodes/plots/pyqtgraph.py

Work around for https://github.com/pyqtgraph/pyqtgraph/issues/533

Fix: Improve qtplot performance

---

qcodes/instrument_drivers/Harvard/Decadac.py

Fix: typo in decadac driver

---

qcodes/instrument/base.py

Add a function to close all instruments. This is handy for restarting sessions for example with atexit

Function to Close all instruments

---

qcodes/plots/pyqtgraph.py
qcodes/utils/helpers.py

Foreground qt window

---

docs/help.rst

Update Slack contact information

---

qcodes/instrument_drivers/rohde_schwarz/ZNB20.py

One step in the direction of sorting out the mess of #679
- add a file
@Dominik-Vogel

add ZNB20.py file referencing ZNB driver

---

qcodes/instrument_drivers/Keysight/Keysight_34465A.py

Corrected Typos

---

qcodes/instrument_drivers/Harvard/Decadac.py

Add channels to slots correctly so that they get snapshotted
@WilliamHPNielsen @Dominik-Vogel

Fix decadac driver

---

.gitignore

I have added the .idea folder to the gitignore file

Added .idea folder to the git ignore file

---

.idea/misc.xml
.idea/vcs.xml

They are now ignored anyway so lets delete them

remove idea files that should probably never have been committed

---

qcodes/instrument_drivers/QDev/QDac_channels.py

@WilliamHPNielsen as requested by T10

QDac make name formatter match channel name formatter

---

qcodes/data/gnuplot_format.py

Workaround for #620 Will be fixed when we use new dataset

Increase default gnuplot precision from 6 to 15 digits

---

qcodes/instrument_drivers/tektronix/Keithley_2600.py

Move definition of self.channel to before its used first time

Fix keithley no channel

---

qcodes/instrument_drivers/Keysight/N51x1.py

Basic driver for Keysight / Agilent N51x1 RF source
@Dominik-Vogel

driver/Keysight N51x1 RF source

---

qcodes/instrument/parameter.py

Fix typo in wrapping of set_raw method

---

qcodes/plots/pyqtgraph.py

setarr is a numpy array its not safe to cast that to a bool

---

qcodes/instrument_drivers/oxford/mercuryiPS.py

Mercury IPS change default hold_after_set to True

---

qcodes/monitor/monitor.py

_latest is no longer a function so make sure we do a deep copy rather than modify the dict
Also only try to convert time tuple if this is actually a datetime object
@WilliamHPNielsen sorry one more

Fix monitor with latest parameter changes

---

qcodes/instrument_drivers/oxford/IPS120.py

@peendebak this is the only other example I can see of _vals being used directly

IPS120 _vals -> vals

---

docs/examples/driver_examples/Qcodes example with Rohde Schwarz RTO 1000 series Oscilloscope.ipynb

Fixes #850
What can I say, @AdriaanRol is right.
- Fix the typo
@Dominik-Vogel

Docs/fix typo i RTO1000 notebook

---

qcodes/instrument_drivers/ZI/ZIUHFLI.py

make syncing happen at the right time

---

qcodes/instrument_drivers/QuTech/D5a.py

spi D5a driver:  validator has to be updated on span change 

---

docs/start/index.rst

fix rst link

---

qcodes/instrument_drivers/Keysight/Keysight_33500B.py

Add output polarity to keysight

---

qcodes/instrument_drivers/ZI/ZIUHFLI.py

Adds aux output functionality to ZI driver

Add aux output to zi driver

---

qcodes/instrument_drivers/ZI/ZIUHFLI.py

- 
- 
- 
@mention one core developer

correct typo

---

qcodes/instrument_drivers/ZI/ZIUHFLI.py

add perf logging to zi scope get

---

docs/start/index.rst

Add raw link to install docs to make it simpler to setup an environment

---

qcodes/tests/drivers/test_ami430.py
qcodes/tests/drivers/test_tektronix_AWG70000A.py
qcodes/tests/test_combined_loop.py

@WilliamHPNielsen Seems like 1000 ms is not always enough on travis so increase it here.

Hypothesis timings

---

.travis.yml
test_requirements.txt

because codeacy doesnt work for prs

Use Codecov for coverage measurement

---

qcodes/instrument_drivers/QuTech/IVVI.py

change delay to inter_delay

---

qcodes/tests/drivers/test_ami430.py

I just encountered the need for this in #918.
- Increase a deadline 
@QCoDeS/core

increase two deadlines

---

qcodes/utils/validators.py

Fixes #921 There is no good reason to store a string of the length of the max string

Dont store a max lenght string

---

README.rst
docs/start/index.rst

Fixes #833 
- Specify what features work exclusively in notebooks
- Remove installation instructions from README.md (let's have everything in one place)
- Add update instructions to the installation instructions
@QCoDeS/core

Docs/update readme.md

---

qcodes/instrument_drivers/tektronix/AWG70000A.py

Hotfix of incorrect validation just discovered while playing with the instrument
@jenshnielsen

fix fgen frequency validation

---

qcodes/instrument_drivers/oxford/kelvinox.py

@jenshnielsen @WilliamHPNielsen  @CJvanDiepen

fix typo in kelvinox driver

---

qcodes/data/io.py

@jenshnielsen @WilliamHPNielsen  Fixes  #939

fix error in io

---

qcodes/.coveragerc
qcodes/instrument/sims/Keysight_34465A.yaml
qcodes/instrument_drivers/Keysight/Keysight_34465A.py
qcodes/tests/drivers/test_keysight_34465a.py

- add test for keysight 45565a

added test for keysight 34465a

---

qcodes/dataset/experiment_container.py
qcodes/dataset/measurements.py
qcodes/tests/dataset/test_experiment_container.py

Bugfix: assign experiment id

---

qcodes/instrument_drivers/AlazarTech/ATS9360.py

alazar trigger delay must be a multiple of the alignment

---

qcodes/instrument/base.py

To make it easier to see if instruments are closed correctly

add logging to close_all

---

setup.py

we now support websockets 4 too

---

qcodes/instrument_drivers/Keysight/Keysight_34465A.py

@QCoDeS/core Fixes warning in init of Keysight dmm

Keysight dmm get -> get_raw

---

qcodes/__init__.py

This migrates from qdev-wrappers
@jenshnielsen

add to qcodes init: atexit  Instrument.close_all  

---

qcodes/tests/dataset/test_measurement_context_manager.py

Hopefully fixes a lot of random test failing.
- Extend a sleep period
@jenshnielsen

Extend a sleep period

---

qcodes/utils/helpers.py

As suggested by @Dominik-Vogel  on Slack

dont fail if SPY_UMR_NAMELIST is not set

---

environment.yml
qcodes/config/qcodesrc.json

This should not be verbose by default
@Dominik-Vogel this may be why users have had the need to change this locally

Change default warning level for stream output

---

environment.yml
setup.py

Add zmq to dependencies

---

qcodes/dataset/measurements.py

I think this should not only be a one tuple but could be a list or tuple of one or more parameters

Correct what looks like slightly wrong typing of sequences

---

qcodes/dataset/data_export.py
qcodes/dataset/plotting.py

Fixes #1059 and partly also corrects #1057 .
- Make both 1D and 2D plots fall back to scatter plot when setpoint are identical
- Refactor the plotting code slightly
- Remove a warning about scatterplotting and make it a `log.debug`
@jenshnielsen

Dataset / plotting identical setpoints

---

qcodes/instrument/visa.py
qcodes/instrument_drivers/QDev/QDac_channels.py

Make the QDac log what it writes similarly to the visa instruments.
@jenshnielsen

Change logging of written commands

---

qcodes/instrument_drivers/cryogenic/CryogenicSMS120C.py

Fixes feature request for operation at ScapucciLab (Leiden).
- Add function to go to field specified by positive and negative numbers (bidirectional) instead of setting absolute value and sign (direction) separately
- Add convenience function to block until requested field is reached
- Change driver to use RAMP ZERO when requesting a to go to exactly 0 Tesla
- Extra safety check for switch heater

driver / Update cryogenic magnet driver

---

qcodes/instrument_drivers/american_magnetics/AMI430.py

Fix AMI ValueError message

---

.gitignore

add hypothesis to gitignore

---

.gitignore

this is the last one I promise :-)

add pytest cache to gitignore

---

.gitignore

sorry, I should have all done it in one PR.... I guess

add vs code temp files to gitignore

---

qcodes/instrument_drivers/AlazarTech/ATS.py

@Dominik-Vogel  the merge on #1003 broke the mypy tests on travis. This fixes that

Correctly type this parameter in the alazar driver

---

qcodes/loops.py

- Add estimated finish time when progress interval is not None
@jenshnielsen

Make progress interval of Loops print ETA

---

qcodes/dataset/data_set.py
qcodes/dataset/measurements.py
qcodes/tests/dataset/test_dataset_basic.py

Nonetype accepted by datasaver

---

qcodes/instrument/channel.py

I managed to temper with the master branch by clicking on the synchronize button in VS code even though another branch was checked out and a different upstream was set and the qcdoes main ref was via https...

Revert Changes on Master

---

qcodes/instrument/sims/Tektronix_AWG5014C.yaml
qcodes/instrument_drivers/tektronix/AWG5014.py
qcodes/tests/drivers/test_tektronix_AWG5014C.py

Fixes a bug reported by @johnhornibrook 
- Add the appropriate underscore to use the correct method
- Add a test to catch the bug
@Dominik-Vogel

driver / hotfix for new awgfile generation

---

qcodes/instrument_drivers/stanford_research/SR860.py

Fix maximum frequency for SRS860 - it is 500 kHz

---

.appveyor.yml
.travis.yml
mypy.ini
qcodes/dataset/measurements.py
qcodes/instrument/base.py
qcodes/instrument_drivers/Spectrum/pyspcm.py
qcodes/instrument_drivers/devices.py
qcodes/plots/pyqtgraph.py
qcodes/utils/validators.py
test_requirements.txt

* Set setting in ini file
* Use warn_unused_ignores mad warn_redundant_casts to remove no longer needed workarounds
* Unpin Hypothesis which is now fixed. Fixes #1163 
* Rather than modifiying pyspcm source code ignore it from mypy

Improve MyPy support

---

qcodes/instrument_drivers/QuTech/F1d.py

- Improve docs
- Change units argument into unit
@jenshnielsen @WilliamHPNielsen @Dominik-Vogel @Christian-Volk

update docstrings in F1d driver

---

qcodes/instrument/parameter.py

Fix doc string of Set-to-context-manager

---

test_requirements.txt

Due to bug with 3.69.11 and log capture
Should hopefully unbreak master

Pin hypothesis

---

docs/start/index.rst

Just a few things that users saw when trying to upgrade their environment. @Dominik-Vogel

Add docs on issues that users had in Copenhagen when upgrading

---

docs/examples/index.rst

- 
- 
- 
@mention one core developer

fix heading in docs

---

azure-pipelines.yml

Should hopefully give a better output

First attempt at publishing results from Azure pipelines

---

environment.yml

Newest version of testpath should resolve the pip/conda issue

---

.travis.yml
qcodes/tests/test_parameter.py

Should hopefully make it simpler to catch issues such as #1319

Test with python 3.7 on travis

---

azure-pipelines.yml

Currently is is first installing 3.7 and then installing 3.6 on top of this. Hopefully this will speed things up at least a bit

Try to speed up azure by installing the correct python version

---

qcodes/tests/dataset/test_subscribing.py

fixes #1369 (possibly)
TIL: force push to a closed PR will render it unreopenable.

Fix flaky `test_basic_subscription` 

---

qcodes/instrument_drivers/tektronix/Keithley_6500.py

@lucblom @astafan8 @WilliamHPNielsen

add driver for keithley6500

---

.travis.yml

Remove slack integration

---

qcodes/instrument_drivers/stanford_research/SR830.py

Fix SR830's _change_sensitivity function.

---

environment.yml
requirements.txt

There is a new python version and a new h5py version

Upgrade dependencies

---

azure-pipelines.yml

The CondaEnvironment task has been deprecated so don't use it

Dont use deprecated condaenv

---

qcodes/dataset/data_set.py

remove an invalid escape seq warning

---

docs/dataset/spec.rst
docs/examples/DataSet/subscriber json exporter.ipynb
qcodes/dataset/data_set.py
qcodes/dataset/measurements.py
qcodes/tests/dataset/dataset_fixtures.py
qcodes/tests/dataset/test_database_extract_runs.py
qcodes/tests/dataset/test_datasaver.py
qcodes/tests/dataset/test_dataset_basic.py
qcodes/tests/dataset/test_dataset_loading.py
qcodes/tests/dataset/test_string_data.py
qcodes/tests/dataset_generators.py

Extracted from the dsi branch #1415 
This change is not really related to the dsi branch and applying this separately removes a lot of noise from that branch.

Rename mark_complete to mark_completed

---

docs_requirements.txt

Fix conda ci build by ensuring that we have a working combo of nbconvert/tornado

---

qcodes/tests/dataset/test_dataset_basic.py

Failed randomly in https://travis-ci.org/QCoDeS/Qcodes/jobs/505673065 as part of #1517

increase deadline on this test as it was failing randomly

---

qcodes/instrument_drivers/Spectrum/M4i.py

Fixes bug introduced in #1509
@astafan8

fix bug in averaging of m4i blockavg

---

docs_requirements.txt
qcodes/dataset/data_set.py
qcodes/instrument_drivers/ZI/ZIHDAWG8.py
qcodes/station.py

Sphinx 2.0 is out. So lets see if our docs build with it.

build docs with sphinx 2.0

---

docs/examples/driver_examples/Qcodes example with Rohde Schwarz ZNB.ipynb

Update notebook section title

---

README.rst

Update readme doi to point to latest release

---

docs_requirements.txt
test_requirements.txt

Latest dependencies

---

LICENSE.rst

Changes proposed in this pull request: 
The dates in license file are corrected. 

Add correct date to Copyright

---

qcodes/dataset/measurements.py

No longer used after #1477 and should probably never have been public in the first place

Deprecate is_number

---

qcodes/instrument_drivers/QuTech/D5a.py

- `vals` should be updated with `unit` 
- 
- 
@astafan8

Updating vals when unit is updated

---

.travis.yml

Make sure that travis has a full clone for db generation

---

azure-pipelines.yml

Hopefully will eventually get ci running again on windows

Fix CI build with conda on windows

---

qcodes/py.typed
setup.py

See https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages for docs on how
this works

make qcodes as safe for external typechecking

---

azure-pipelines.yml

Setting all the correct paths resolves the issue we had with conda 4.7 previously

Use conda 4.7

---

azure-pipelines.yml

Docsbuild: remove old files before checking in and use old style message

---

docs/changes/0.5.0.rst

Fix changelog v0.5.0

---

README.rst

update zenodo link for 0.5.2

---

docs/changes/0.6.0.rst
qcodes/dataset/sqlite/database.py

This should significantly improve performance when doing concurrent reads and writes from the db

Make WAL mode the default for new dbs

---

docs_requirements.txt
environment.yml
requirements.txt

* Pyvisa 1.10
* nbconvert 5.6.0

Update some requirements to latest version

---

.travis.yml

As documented here https://docs.travis-ci.com/user/gui-and-headless-browsers/

Use recomended way of running xvfb on travis

---

qcodes/instrument/base.py
qcodes/instrument/channel.py
qcodes/instrument/visa.py
qcodes/instrument_drivers/Gentec/Gentec_Maestro.py

This PR proposes some fixes in the docstrings of 
- qcodes.instrument.visa
- qcodes.instrument.channel
- qcodes.instrument.base

Fix docstrings in qcodes.instrument: visa, channel, base

---

qcodes/logger/__init__.py
qcodes/logger/instrument_logger.py
qcodes/logger/log_analysis.py
qcodes/logger/logger.py

W3: Fix the user-facing api docs in

Fix docs in qcodes.logger: instrument_logger, log_analysis, logger

---

qcodes/instrument_drivers/Keysight/Keysight_E8267D.py

- Add IQ adjustments on/off
- Add I offset and Q offset

[DEM-1061] Add missing parameters for Keysight vector source

---

qcodes/instrument_drivers/Keysight/Keysight_E8267D.py

- Pulse modulation 
- IQ quadrature

Add parameters to Keysight_E8267D

---

README.rst
docs/index.rst
docs/start/index.rst

Advertise the tutorial at prominent locations. 
SideFix: Also add a link to the example notebooks in docs/index.rst
@jenshnielsen

Link tutorial to "Getting started", "README"  

---

qcodes/instrument/mockers/simulated_ats_api.py
qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
qcodes/tests/conftest.py
qcodes/tests/mockers/test_simulated_ats_api.py

In this PR a simulator for the Alazar cards gets added. It is far from complete but enables simple testing.
An example can be found in the test.

Alazar Simulator

---

qcodes/instrument_drivers/Keysight/Keysight_E8267D.py

Keysight E8267D: fix SCPI command for IQadjustments

---

docs/examples/legacy/Datasaving examples.ipynb
qcodes/instrument/base.py
qcodes/tests/dataset/test_measurement_context_manager.py
qcodes/tests/test_instrument.py
qcodes/tests/test_visa.py

Actually forward metadata to the Metadatable superclass. This is work in progress since its still lacking tests

Fix instrument metadata

---

qcodes/instrument/visa.py
qcodes/instrument_drivers/Keysight/Keysight_N6705B.py
qcodes/instrument_drivers/rigol/DG1062.py
qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
qcodes/tests/test_visa.py
qcodes/utils/validators.py

Noticed from #1738 that this important code is not typed

Add mypy types to visa backend

---

qcodes/instrument/base.py
qcodes/instrument/channel.py
qcodes/tests/instrument_mocks.py

Was looking over this code and noticed a few issues. 
There are still more things that could be improved but this is imho a clean improvement

Pep8 and type cleanup in instruments

---

docs/changes/0.7.0.rst

New release yeah yeah
@QCoDeS/core

RELEASE v0.7.0

---

azure-pipelines.yml

Explicitly install pip and setuptools to prevent conda deciding to uninstall its own dependencies 😡

Try fixing conda install in pipelines on linux

---

docs/examples/Configuring_QCoDeS.ipynb
docs/examples/Station.ipynb

This PR propses small fixes to the notebooks "Station" and "QCoDeS Config".

Fix example notebooks: station and QCoDeS config

---

qcodes/instrument_drivers/Keysight/Keysight_E8267D.py

fix pulse_modulation_enabled parameter and add pulse_modulation_source

---

mypy.ini
qcodes/instrument/group_parameter.py
qcodes/instrument/specialized_parameters.py

Add full typing to Group and specialized parameters

---

mypy.ini
qcodes/dataset/descriptions/dependencies.py
qcodes/dataset/descriptions/param_spec.py
qcodes/dataset/descriptions/rundescriber.py
qcodes/dataset/descriptions/versioning/v0.py

Makes dataset.description fully typed

Add types to dataset descriptions

---

README.rst

With Azure pipelines and travis-ci.com

Update badges in readme

---

qcodes/instrument/channel.py
qcodes/instrument_drivers/rohde_schwarz/ZNB.py

This should  not break anything as it is more general.

Fix type annotation of `InstrumentChannel.__init__` 

---

environment.yml
requirements.txt
setup.py

I also took the change to add the missing 3.8 and 3.7 classifiers

Use websockets 8.1 with official python 3.8 support

---

azure-pipelines.yml

Forgot it in this PR https://github.com/QCoDeS/Qcodes/pull/1836

Trigger azure pipeline on tags

---

docs/changes/0.8.1.rst

Update change log

---

qcodes/instrument/parameter.py

... because `Union[int, float]` is equivalent to `float`.

Substitute Number type with float in parameter.py

---

docs_requirements.txt

build docs with sphinx 2.2.2

---

qcodes/dataset/sqlite/database.py
qcodes/utils/installation_info.py
test_requirements.txt

This enables us to get rid of a workaround

use Mypy 0.750

---

azure-pipelines.yml

Also trigger azure builds on release branches

---

azure-pipelines.yml

Azure twine -r name should match service endpoint

---

qcodes/utils/helpers.py

@Dominik-Vogel @jenshnielsen correct? :)

Move qcodes dependency into function that needs it

---

docs/changes/0.9.0.rst

In preparation to cut 0.9.0 release candidate asap

Changelog for 0.9.0

---

qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py

make new limit function signature match the original one

Mercury iPS improved type hints

---

docs/changes/0.9.0.rst

Once this is in I will backport to the 0.9.x branch and cut the release

final changelog for 0.9

---

qcodes/instrument/channel.py
qcodes/instrument/visa.py
qcodes/station.py
qcodes/utils/validators.py

These are all included in the signatures so can safely be removed

Remove some doc types

---

mypy.ini
qcodes/dataset/measurements.py
qcodes/instrument/ip.py
qcodes/instrument/parameter.py
qcodes/logger/instrument_logger.py
qcodes/logger/log_analysis.py
qcodes/logger/logger.py
qcodes/utils/delaykeyboardinterrupt.py

and enforce this via mypy config

Complete typing of logging module

---

mypy.ini
qcodes/monitor/monitor.py

Add types to monitor 

---

CONTRIBUTING.rst

Fix links to issues in contributing.rst

---

docs/examples/driver_examples/Qcodes example with Keithley 7510.ipynb
qcodes/instrument/sims/keithley_7510.yaml
qcodes/instrument_drivers/tektronix/keithley_7510.py
qcodes/tests/drivers/test_keithley_7510.py

- driver for Keithley 7510 DMM, including a few essential functions to perform measurement
- ipynb example to use the functions
- test file and yaml file to simulate the DMM
@sohailc

Driver for Keithley 7510 DMM

---

qcodes/monitor/monitor.py

Fixes #1921 .
- Corrects type of timestamp in the monitor
This could also be fixed in the web frontend code, but I can't seem to find that anywhere...
@jenshnielsen

Fix type of timestamp in monitor

---

qcodes/instrument_drivers/yokogawa/GS200.py

This change disables reading of the measure parameter during
snapshot, which fixes an exception in the log during initialization
if the output is off or measurements are disabled, since a
GS200Exception is thrown.
In addition, the cache mode variables are initialized in __init__
preventing an AttributeError if measure is called during initialization.
@jenshnielsen @GateBuilder

Yokogawa GS200: Fix exception during snapshot on initialization.

---

azure-pipelines.yml
qcodes/tests/drivers/test_keysight_34465a.py

This currently causes fails running the tests in ci

Fix issue running tests with pytest 5.4.0

---

azure-pipelines.yml

Correctly conform to the syntax here https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema

fix pr trigger syntax

---

qcodes/tests/dataset/test_measurement_context_manager.py
test_requirements.txt

Use pytest retry to reexecute known flaky test 

---

azure-pipelines.yml

Use latest Windows and Ubuntu images.
@jenshnielsen

Update azure pipeline images

---

qcodes/dataset/data_set.py

Remove the unnecessary debug output from data_set.
@jenshnielsen

Remove the debug log from data_set

---

README.rst

Update the DOI in the main README to point to version 0.12.0
@QCoDeS/core

Update DOI to point to v0.12.0

---

environment.yml
requirements.txt

Install h5py 2.10 from requirements 

---

qcodes/configuration/config.py
qcodes/instrument/base.py
qcodes/utils/helpers.py
qcodes/utils/metadata.py

Inline the documentation of attributes (and make them actual documental attributes by taking them out of the init) Name is not an attribute but a property (and already documented as such)

Better attribute documentation for parameter

---

environment.yml

install python 3.7.7 in conda env

---

docs/changes/0.12.0.rst
docs/changes/0.13.0.rst

These are not rendering correctly at the moment

add correct headers for changelog

---

README.rst

Update README w/ doi 0.12.1

---

qcodes/instrument/group_parameter.py

Do not overwrite get at init of GroupParameter

Do not overwrite get in GroupParameter

---

qcodes/instrument/sims/Keysight_34465A.yaml
qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
qcodes/tests/drivers/test_keysight_34465a.py

- Adding a method to increase the range of a keysight instrument
- accesses and searches the ranges and implements them into the setter for the range method

added range function into keysight submodule

---

qcodes/tests/test_combined_loop.py

This PR proposes minor fixes to the test for legacy combined loop. These changes necessary for the pytest-xdist to work.
@jenshnielsen

Fix the test for combined loop

---

qcodes/tests/test_combined_loop.py

The merge of #2009 moved the data generated out from a `data` folder. That does not seem needed so this changes that

keep generated data within a data folder

---

docs/changes/0.14.0.rst

changelog update for may release 
@astafan8 and @jenshnielsen

Full changelogs for 0.14.0 May release

---

README.rst

- 
- 
- 
@mention one core developer

zenodo update for may 0.14.0 release

---

qcodes/tests/test_channels.py

This PR introduces small fixes for pytest-xdist to work.
@jenshnielsen

Fix loop data location in channels test

---

.travis.yml
azure-pipelines.yml

We should also genete these so we can test the v8 -> v9 upgrade path

create v8 databases for tests

---

qcodes/instrument_drivers/rohde_schwarz/ZNB.py

This PR adds parameter limits for the R&S ZNB-40 VNA, and also some minor fixes.
@astafan8

Add support for R&S ZNB-40

---

environment.yml
requirements.txt
setup.py

Fixes deprecation warnings with 0.10 among other things

use pyqtgraph 0.11 in recommended env

---

qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1520a_cmu.py

This makes IVSweeper and CVSweeper class similar in their functionalities. Also, all the sweep related parameters are now clubbed in one class. 
This should not have any effect on the protocol. 
@astafan8

Move sweep parameters of B1520A to CVSweeper class

---

setup.py

Not just of the tests but also a runtime dependency

typing extensions is a dependency

---

qcodes/dataset/data_set.py
qcodes/dataset/sqlite/queries.py
qcodes/tests/dataset/test_database_extract_runs.py
qcodes/tests/dataset/test_datasaver.py
qcodes/tests/dataset/test_dataset_basic.py
qcodes/tests/dataset/test_measurement_context_manager.py
qcodes/tests/dataset/test_string_data.py
qcodes/tests/test_doNd.py

It turns out that get_parameter_data has slightly different ways of working for negative start and end. That has been fixed in this pr to match get_data as it was

Remove get_data, get_values from dataset and update tests to not use it

---

docs_requirements.txt

Build docs with Sphinx 3.1.2

---

pytest.ini

replace mixed spaces/tab mode with spaces

fix formatting of pytest.ini

---

README.rst

This PR introduces to small changes to the README that we've been talking about for a while:
- Remove the outdated "status" section (we can put a new one in later)
- Add a link to MS code of conduct
@jenshnielsen

Update readme with CoC

---

docs/examples/15_minutes_to_QCoDeS.ipynb

- minor text changes  in 15 minutes to Qcodes 
@jenshnielsen

minor text changes in quickStart

---

docs/changes/0.16.0.rst

This is the proposed changelog for release `v0.16.0`
@QCoDeS/core

Update v0.16.0 changelog

---

docs/user/faq.rst

Fixes #1571 .
- update link to 15 minutes to Qcodes

update qcodes usage link

---

qcodes/instrument/base.py

Fixes #2092 .
- update error message when pickling an instrument

Update error message for instruments pickling

---

environment.yml

this no longer works well together with the pip version of the package

remove conda ruamel package to hopofully fix pipelines ci build

---

qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1517a_smu.py

Dummy value can be returned when
measurement status is MeasurementStatus.V

B1500: convert dummy values to NaN for spot measurement

---

README.rst

Also clarify that we support python 3.7 and up

update Zenodo link for 0.17.0

---

qcodes/dataset/database_fix_functions.py
qcodes/dataset/descriptions/dependencies.py
qcodes/dataset/descriptions/rundescriber.py
qcodes/dataset/descriptions/versioning/rundescribertypes.py
qcodes/dataset/descriptions/versioning/serialization.py
qcodes/dataset/descriptions/versioning/v0.py

This makes the structure of the rundescibers more clear and easier to reason about

add types to run describer dict representations

---

qcodes/instrument/group_parameter.py
qcodes/tests/parameter/test_group_parameter.py

- Add a new group set parameters method 
- Remove deprecated method
- Add tests for the new method
@jenshnielsen

Add new group set parameters method and remove old

---

setup.py

require latest opencensus packages

---

qcodes/dataset/descriptions/versioning/serialization.py
qcodes/tests/dataset/test_converters.py

as in newer than the current version available

Allow from_dict_to_current to deserialize from new versions

---

docs/community/index.rst
docs/community/related_projects.rst

First version of a docs page with related projects. Please have a look and see if I missed anything

add page with related projects

---

.travis.yml
environment.yml
requirements.txt

Will make the coverage less confusing as python 3.7 and 3.8 should hit all the same tests

install pyqt for python 3.8

---

setup.py

fix missing , in install_requires

---

.travis.yml
azure-pipelines.yml
qcodes/tests/conftest.py

We seem to be getting more hypothesis deadline timeouts since we upgraded hypothesis. It seems like the simplest solution is to increase the deadline from the default value of 200 ms to something more resonable like 1000 
This pr aims to do that

Increase Hypothesis deadline when running in CI

---

qcodes/__init__.py

@astafan8 Broken out from #2178

set the same hypothesis deadline when running from within python

---

README.rst

Change zenodo link for v0.18.0

Change zenodo link for v0.18.0

---

qcodes/tests/dataset/test_dataset_loading.py
qcodes/tests/dataset/test_dependencies.py
qcodes/tests/dataset/test_measurement_context_manager.py
qcodes/tests/dataset/test_sqlite_base.py
qcodes/tests/drivers/test_ami430.py
qcodes/tests/drivers/test_tektronix_AWG70000A.py
qcodes/tests/instrument_mocks.py
qcodes/tests/parameter/conftest.py
qcodes/tests/test_data.py
qcodes/tests/test_format.py
qcodes/tests/test_helpers.py
qcodes/tests/test_location_provider.py
qcodes/tests/test_logger.py
qcodes/tests/test_station.py
qcodes/tests/test_validators.py

pyupgrade qcodes/tests

---

qcodes/dataset/data_export.py
qcodes/dataset/data_set.py
qcodes/dataset/descriptions/dependencies.py
qcodes/dataset/experiment_container.py
qcodes/dataset/plotting.py
qcodes/dataset/sqlite/connection.py
qcodes/dataset/sqlite/db_upgrades/version.py

pyupgrade qcodes/dataset

---

qcodes/instrument/base.py
qcodes/instrument/channel.py
qcodes/instrument/group_parameter.py
qcodes/instrument/mockers/ami430.py
qcodes/instrument/parameter.py
qcodes/instrument/sweep_values.py
qcodes/instrument/visa.py

pyupgrade qcodes/instrument

---

qcodes/instrument_drivers/Keysight/Infiniium.py
qcodes/instrument_drivers/Keysight/KeysightAgilent_33XXX.py
qcodes/instrument_drivers/Keysight/Keysight_B2962A.py
qcodes/instrument_drivers/Keysight/N51x1.py
qcodes/instrument_drivers/Keysight/N52xx.py
qcodes/instrument_drivers/Keysight/SD_common/SD_AWG.py
qcodes/instrument_drivers/Keysight/SD_common/SD_DIG.py
qcodes/instrument_drivers/Keysight/SD_common/SD_Module.py
qcodes/instrument_drivers/Keysight/private/Keysight_344xxA.py
qcodes/instrument_drivers/Keysight/private/Keysight_344xxA_submodules.py
qcodes/instrument_drivers/Keysight/private/error_handling.py

pyupgrade qcodes/instrument_drivers/Keysight

---

qcodes/instrument_drivers/tektronix/AWG5014.py
qcodes/instrument_drivers/tektronix/AWG5200.py
qcodes/instrument_drivers/tektronix/AWG70000A.py
qcodes/instrument_drivers/tektronix/AWGFileParser.py
qcodes/instrument_drivers/tektronix/Keithley_2000.py
qcodes/instrument_drivers/tektronix/Keithley_2400.py
qcodes/instrument_drivers/tektronix/Keithley_2600.py
qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
qcodes/instrument_drivers/tektronix/Keithley_3706A.py
qcodes/instrument_drivers/tektronix/Keithley_6500.py
qcodes/instrument_drivers/tektronix/Keithley_s46.py
qcodes/instrument_drivers/tektronix/TPS2012.py

pyupgrade qcodes/instrument_drivers/tektronix

---

qcodes/instrument_drivers/yokogawa/GS200.py
qcodes/math_utils/field_vector.py
qcodes/monitor/monitor.py
qcodes/plots/pyqtgraph.py
qcodes/plots/qcmatplotlib.py
qcodes/utils/command.py
qcodes/utils/helpers.py
qcodes/utils/magic.py
qcodes/utils/slack.py
qcodes/utils/validators.py

pyupgrade instrument_drives/yokogawa, math_utils, monitor, plots, utils

---

qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
qcodes/instrument_drivers/oxford/mercuryiPS.py
qcodes/instrument_drivers/oxford/triton.py
qcodes/instrument_drivers/rigol/private/DP8xx.py
qcodes/instrument_drivers/rohde_schwarz/RTO1000.py
qcodes/instrument_drivers/signal_hound/USB_SA124B.py
qcodes/instrument_drivers/stanford_research/SR830.py
qcodes/instrument_drivers/stanford_research/SR86x.py

pyupgrade qcodes/instrument_drivers/oxford,rigol,rohde_schwarz,signal_hound,stanford_research

---

qcodes/instrument_drivers/Lakeshore/Model_325.py
qcodes/instrument_drivers/Lakeshore/Model_372.py
qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
qcodes/instrument_drivers/Minicircuits/Base_SPDT.py
qcodes/instrument_drivers/Minicircuits/RC_SP4T.py
qcodes/instrument_drivers/Minicircuits/RC_SPDT.py
qcodes/instrument_drivers/Minicircuits/USB_SPDT.py
qcodes/instrument_drivers/QDev/QDac.py
qcodes/instrument_drivers/QDev/QDac_channels.py

pyupgrade qcodes/instrument_drivers/Lakeshore,Minicircuits,QDev

---

qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/server.py
qcodes/instrument_drivers/ZI/ZIUHFLI.py
qcodes/instrument_drivers/agilent/Agilent_34400A.py
qcodes/instrument_drivers/american_magnetics/AMI430.py
qcodes/instrument_drivers/rigol/DG1062.py
qcodes/instrument_drivers/rigol/DG4000.py
qcodes/instrument_drivers/rigol/DS1074Z.py
qcodes/instrument_drivers/rigol/DS4000.py
qcodes/instrument_drivers/rigol/private/DP8xx.py

pyupgrade qcodes/instrument_drivers/QDevil, QuantumDesign, ZI, agilent, american_magnetics, rigol

---

docs/conf.py
docs/user/meta.py
qcodes/configuration/config.py
qcodes/data/data_array.py
qcodes/data/data_set.py
qcodes/data/format.py
qcodes/data/hdf5_format.py
qcodes/data/io.py
qcodes/data/location.py
qcodes/instrument_drivers/devices.py
qcodes/instrument_drivers/test.py
qcodes/loops.py
qcodes/station.py

These are the final changes before https://github.com/QCoDeS/Qcodes/pull/2200 can be merged.

Remaining pyupgrade fixes

---

azure-pipelines.yml

use the hypothesis ci profile on azure linux builds too

---

.github/workflows/docs.yaml
.github/workflows/pytest-non-local.yaml
.github/workflows/pytest.yaml

* correcting a simple typo
* put python version into the cache-key as packages may be version specific.

use the correct file for docs dep cache

---

qcodes/tests/parameter/test_array_parameter.py
qcodes/tests/parameter/test_combined_par.py
qcodes/tests/parameter/test_instrument_ref_parameter.py
qcodes/tests/parameter/test_multi_parameter.py
qcodes/tests/parameter/test_parameter_context_manager.py
qcodes/tests/parameter/test_scaled_parameter.py
test_requirements.txt

Mostly done automatically by unittest2pytest

Rewrite parameter tests as pytest style tests.

---

qcodes/tests/parameter/test_instrument_ref_parameter.py
qcodes/tests/test_channels.py
qcodes/tests/test_config.py
qcodes/tests/test_monitor.py
qcodes/tests/test_visa.py

* test_channels
* test_config
* test_monitor (just removing an unused import)
* test_visa
* And add missing close logic that was missing in #2232

Unittest to pytest channels, config, visa

---

qcodes/tests/test_doNd.py

make sure that parameter names are unique
and check that interdeps are as expected

fix addtional setpoint tests

---

qcodes/tests/helpers/test_waitsecs.py

this test has been opserved to fail in ci
so tweek tol a bit to make that less likely

Tweek tol for wait_sec test

---

qcodes/interactive_widget.py
test_requirements.txt

Alternative to #2269 @astafan8

Widget sort None timestamps as oldest

---

.github/workflows/automerge.yaml

This enables you to automatically mark reviewed prs which parses ci with the label "automerge" to have then automatically merged
See here https://github.com/pascalgn/automerge-action for more docs

add basic automatic merge work flow

---

qcodes/tests/drivers/test_ami430.py

AMI 430: dont test deprecated kwarg

---

qcodes/dataset/measurements.py
qcodes/tests/dataset/test_string_data.py

Allow string and time/datetime data to be storred in array measurements

---

CONTRIBUTING.rst

Updated contact information for Core Developers listed in docs.

updated contact info

---

qcodes/tests/legacy/data_mocks.py
qcodes/tests/legacy/test_data.py
qcodes/tests/legacy/test_format.py

Prevents a race condition as seen here https://github.com/QCoDeS/Qcodes/runs/1292175152?check_suite_focus=true

Legacy: give name to datasets

---

docs/changes/0.19.0.rst

Quick spelling fix in change logs for current release

fixed spelling in stored

---

qcodes/instrument_drivers/Lakeshore/Model_325.py
qcodes/instrument_drivers/Lakeshore/Model_336.py
qcodes/instrument_drivers/Lakeshore/Model_372.py
qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
setup.cfg

Complete typing of lakeshore drivers

---

README.rst

updated rst for zenodo 0.19.1

---

qcodes/instrument_drivers/agilent/Agilent_34400A.py
qcodes/instrument_drivers/agilent/E8267C.py
qcodes/instrument_drivers/agilent/E8527D.py
qcodes/instrument_drivers/signal_hound/USB_SA124B.py
setup.cfg

Add compete types to signal hound and agilent drivers

---

qcodes/instrument_drivers/american_magnetics/AMI430.py
setup.cfg

And removes a deprecated method

Add full types to ami430 driver

---

qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_sampling_measurement.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1511B.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1530A.py
qcodes/instrument_drivers/Keysight/keysightb1500/message_builder.py
setup.cfg

@astafan8 Note that there are still a few untyped functions in message builder. These are unused and their tests are stubs so it is hard to guess what the intended types are. Perhaps you know better

Add full types to keysight b1500 driver

---

qcodes/instrument_drivers/stahl/stahl.py
qcodes/instrument_drivers/weinschel/Weinschel_8320.py
setup.cfg

add types for stahl and weinschel drivers

---

qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
qcodes/instrument_drivers/oxford/mercuryiPS.py
qcodes/instrument_drivers/oxford/triton.py
setup.cfg

@astafan8 and @WilliamHPNielsen Do you see any good reason not to deprecate the old Mercury driver

Type oxford Mercury VISA driver and Triton driver. Deprecate old Mercury driver

---

qcodes/instrument_drivers/rigol/DG1062.py
qcodes/instrument_drivers/rigol/DG4000.py
qcodes/instrument_drivers/rigol/DP821.py
qcodes/instrument_drivers/rigol/DP831.py
qcodes/instrument_drivers/rigol/DP832.py
qcodes/instrument_drivers/rigol/DS1074Z.py
qcodes/instrument_drivers/rigol/DS4000.py
qcodes/instrument_drivers/rigol/private/DP8xx.py
setup.cfg

Add types to Rigol drivers

---

qcodes/instrument/parameter.py
qcodes/instrument_drivers/tektronix/AWG5208.py
qcodes/instrument_drivers/tektronix/AWG70000A.py
qcodes/instrument_drivers/tektronix/AWG70002A.py
qcodes/instrument_drivers/tektronix/AWGFileParser.py
qcodes/instrument_drivers/tektronix/DPO7200xx.py
qcodes/instrument_drivers/tektronix/Keithley_2000.py
qcodes/instrument_drivers/tektronix/Keithley_2400.py
qcodes/instrument_drivers/tektronix/Keithley_2450.py
qcodes/instrument_drivers/tektronix/Keithley_2600_channels.py
qcodes/instrument_drivers/tektronix/Keithley_3706A.py
qcodes/instrument_drivers/tektronix/Keithley_6500.py
qcodes/instrument_drivers/tektronix/Keithley_s46.py
qcodes/instrument_drivers/tektronix/TPS2012.py
qcodes/instrument_drivers/tektronix/keithley_7510.py
setup.cfg

Except 5014c Also since most drivers are now typed revers the logic and mark drivers typed by default and exclude the not  typed ones

Type most tektronix drivers

---

qcodes/instrument_drivers/Keysight/SD_common/__init__.py

Mark Keysight sd common module as deprecated

---

qcodes/instrument_drivers/tektronix/AWG5014.py
setup.cfg

And remove a few deprecated methods

Type awg5014c driver

---

qcodes/utils/dataset/doNd.py
qcodes/utils/installation.py
qcodes/utils/plotting.py
setup.cfg

Complete typing of a few modules in utils

---

qcodes/utils/delaykeyboardinterrupt.py
setup.cfg

Add types to delaykeyboardinterrupt module

---

docs/changes/0.20.0.rst

Update the v0.20.0 changelog for release

---

README.rst

updated zenodo for v0.20.1

---

qcodes/configuration/config.py
qcodes/dataset/descriptions/versioning/serialization.py
qcodes/dataset/json_exporter.py
qcodes/dataset/measurements.py
qcodes/instrument_drivers/Keysight/keysight_34980a.py
qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/commandhandler.py
qcodes/interactive_widget.py
qcodes/tests/dataset/test_subscribing.py
qcodes/tests/drivers/test_lakeshore.py
qcodes/tests/parameter/test_snapshot.py
qcodes/utils/dataset/doNd.py
qcodes/utils/deprecate.py
qcodes/utils/helpers.py
qcodes/utils/metadata.py
qcodes/utils/validators.py

This will once complete allow us to run mypy with ` --disallow-any-generics`

Start replacing implicit use of Any with explicit

---

qcodes/dataset/sqlite/queries.py
qcodes/instrument/base.py

suggestions from review of #2453

Minor typing improvements

---

qcodes/instrument_drivers/Keysight/Infiniium.py
qcodes/instrument_drivers/Keysight/N52xx.py
qcodes/instrument_drivers/Keysight/keysight_e4980a.py
qcodes/instrument_drivers/QDev/QDac_channels.py
qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
qcodes/instrument_drivers/rigol/DG1062.py
qcodes/instrument_drivers/stahl/stahl.py
qcodes/instrument_drivers/stanford_research/SR86x.py
qcodes/instrument_drivers/tektronix/Keithley_s46.py

Remove implicit generic Any from some of the instrument drivers

---

qcodes/instrument_drivers/AlazarTech/ATS.py
qcodes/instrument_drivers/AlazarTech/ATS9360.py
qcodes/instrument_drivers/AlazarTech/ATS9373.py
qcodes/instrument_drivers/AlazarTech/dll_wrapper.py

no implicit generics in alazar driver

---

qcodes/instrument_drivers/Keysight/keysight_34934a.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
qcodes/instrument_drivers/Keysight/keysightb1500/message_builder.py
qcodes/instrument_drivers/Lakeshore/Model_325.py
qcodes/instrument_drivers/ZI/ZIUHFLI.py
qcodes/instrument_drivers/tektronix/AWG5014.py
qcodes/instrument_drivers/tektronix/AWG70000A.py
qcodes/instrument_drivers/tektronix/AWGFileParser.py
qcodes/instrument_drivers/tektronix/Keithley_2000.py
qcodes/instrument_drivers/tektronix/Keithley_2450.py
qcodes/instrument_drivers/tektronix/keithley_7510.py
setup.cfg

Qcodes no implicit generic in drivers

---

qcodes/instrument/channel.py
qcodes/instrument/function.py
qcodes/instrument/parameter.py
qcodes/instrument_drivers/tektronix/AWG70000A.py
qcodes/tests/parameter/conftest.py
qcodes/tests/validators/test_basic.py
qcodes/utils/types.py
qcodes/utils/validators.py
setup.cfg

To make this possible make the validator generic in the valid type which requires a few more modifications to typecheck nicely

Add complete types to Validators

---

docs/examples/writing_drivers/Creating-Instrument-Drivers.ipynb
qcodes/instrument_drivers/AlazarTech/ATS9870.py

Fix parameter name in ats9870: EXTERNAL_CLOCK_10MHz_REF

---

qcodes/instrument/sims/Keysight_34465A.yaml

... which result in warnings when making a snapshot of the simulated driver.

Keysight 34465A: Add missing parameters to pyvisa sim yaml file

---

qcodes/configuration/config.py
qcodes/configuration/qcodesrc.json
qcodes/configuration/qcodesrc_schema.json
qcodes/dataset/measurements.py
qcodes/tests/common.py
qcodes/tests/dataset/measurement/test_measurement_context_manager.py

Make it possible to set these globally. 
Along the way
* Remove unsupported plottr subscriber. 
@ThorvaldLarsen

Add config options for dataset write_in_background and write_periode

---

docs_requirements.txt
requirements.txt
science_requirements.txt
test_requirements.txt

corrected replacement for #2522

sync importlib metadata requirement

---

README.rst

Since we are no longer using Travis CI

update readme badge to point to github actions

---

qcodes/dataset/data_set.py

only typing adjustments were needed for that

Allow passing ParamSpecBase to DataSet's "get data" methods

---

qcodes/dataset/data_set.py
qcodes/dataset/data_set_cache.py
qcodes/dataset/sqlite/queries.py

This will eventually enable the addend logic to be used with other sources of data

Refactor data merging when loading from disk

---

qcodes/tests/dataset/test_data_set_cache.py

Additional tests for cache loading bug fixed in #2664

---

qcodes/dataset/sqlite/queries.py
qcodes/tests/dataset/test_data_set_cache.py

fix #2105 by expanding 1 elem arrays when loading

---

qcodes/instrument_drivers/agilent/E8527D.py

-determine the validators for the frequency and power parameter of the Agilent E8527D microwave source based on the installed options.
@jenshnielsen

automatic validator for agilent E8527D based on options

---

.github/workflows/upload_to_pypi.yaml
azure-pipelines.yml
setup.cfg

Based on the working script in plottr. 
This also fixes a warning about new lines not being allowed within the description field that I found while testing this,.

Move upload to pypi to Github actions

---

.github/workflows/docs.yaml
.github/workflows/pytest-min-versions.yaml
.github/workflows/pytest-non-local.yaml
.github/workflows/pytest.yaml
.github/workflows/verify-science-deps-installable.yaml

cache key should depend on setup.cfg not setup.py since this contains the dependencies

Update pip package caching

---

README.rst
docs/start/index.rst

Update to the readme:
Remove Azure badge
Use the correct target for docs build

Update install instructions

---

qcodes/dataset/data_set_cache.py

This fixes using to_pandas on a live dataset

don't try to load from disk in to_pandas

---

.github/static/environment_forge_full.yml
requirements.txt
setup.cfg

Explicit dependency on netcdf4

---

README.rst

Zenodo update in README for 0.23.0 release

zenodo 0.23.0 update

---

README.rst

update readme after release

---

docs_requirements.txt
requirements.txt
test_requirements.txt

Dependabot still does not do this automatically

upgrade importlib metadata to 3.10

---

docs/changes/0.25.0.rst
qcodes/dataset/data_export.py

This is actually used within one of the plotting functions

Revert deprecation of reshape_2D_data

---

docs/start/index.rst

- Replace link of NI VISA to Keysight IO Libraries Suite
@jenshnielsen

Update link from NI VISA to Keysight IO Libraries Suite on 'Getting Started' Doc

---

.pre-commit-config.yaml
qcodes/data/data_array.py
qcodes/data/data_set.py
qcodes/data/hdf5_format.py
qcodes/dataset/data_export.py
qcodes/dataset/sqlite/queries.py
qcodes/dataset/subscriber.py
qcodes/instrument/delegate/grouped_parameter.py
qcodes/instrument/parameter.py
qcodes/instrument_drivers/Lakeshore/lakeshore_base.py
qcodes/instrument_drivers/QDev/QDac_channels.py
qcodes/instrument_drivers/oxford/MercuryiPS_VISA.py
qcodes/instrument_drivers/stanford_research/SR86x.py
qcodes/tests/dataset/test_paramspec.py
qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_sampling_measurement.py
qcodes/tests/parameter/test_group_parameter.py
qcodes/tests/test_autoloadable_channels.py
qcodes/utils/slack.py

This mainly adds a feature that removes non needed list comprehensions

upgrade pypupgrade to 2.18.3 in pre-commit 

---

qcodes/dataset/data_set_cache.py
qcodes/dataset/descriptions/versioning/v0.py
qcodes/dataset/exporters/export_to_pandas.py
qcodes/dataset/exporters/export_to_xarray.py
qcodes/dataset/json_exporter.py
qcodes/dataset/measurements.py
qcodes/dataset/sqlite/db_upgrades/upgrade_2_to_3.py
qcodes/dataset/sqlite/query_helpers.py

As part of an ongoing effort to use more restrictive interfaces within the input arguments

Convert input arguments to Mapping in dataset module

---

docs/examples/15_minutes_to_QCoDeS.ipynb
docs/examples/DataSet/Performing-measurements-using-qcodes-parameters-and-dataset.ipynb

Adds info on name keyword argument of Measurements in relevant docs
@astafan8

Add information about `name` keyword argument of `Measurement` module in relevant docs

---

qcodes/dataset/data_set.py
qcodes/dataset/exporters/export_to_csv.py

In preparation to making this reusable in the future

Dataset: split out csv conversion

---

.pre-commit-config.yaml
qcodes/dataset/data_set.py
qcodes/instrument/delegate/grouped_parameter.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
qcodes/instrument_drivers/ZI/ZIUHFLI.py
qcodes/instrument_drivers/tektronix/DPO7200xx.py
qcodes/tests/drivers/test_ami430.py

upgrade pyupgrade to 2.19.1

---

.github/static/environment_forge_full.yml

This is required for mypy 0.9 to pass type checking

add typing packages to conda ci

---

test_requirements.txt

I must have overlooked this when I originally added these

pin typing packages in the same way as other test deps

---

.pre-commit-config.yaml

upgrade pyupgrade to 2.19.4

---

.github/static/environment_forge_full.yml

lock numpy to 1.20 until we can type check with 1.21

---

.pre-commit-config.yaml

Fixes some bugs where files would fail to verify

upgrade darker to 1.2.4

---

.pre-commit-config.yaml

Latest version of pyupgrade precommit hook

Pyupgrade 220

---

.pre-commit-config.yaml

upgrade pyupgrade to 2.21

---

.pre-commit-config.yaml

This fixes a few potentially incorrect rewrites

upgrade pyupgrade to 2.21.2

---

qcodes/tests/legacy/test_hdf5formatter.py

work around legacy test issue with hf51.12.1 on conda forge

---

.github/workflows/codeql-analysis.yml

using a workflow dispatch trigger

make it possible to manaully trigger codeql

---

CONTRIBUTING.rst

Mentioned GitHub Discussions in several places of this page to be used by users and contributors.

Update contributing page mentioning github discussions

---

qcodes/dataset/database_extract_runs.py
qcodes/dataset/sqlite/queries.py

Lifted from #3094
Since this is a relatively straightforward refactor it makes sense to apply it outside that pr

extract exp_id to attrs function

---

qcodes/dataset/database_extract_runs.py
qcodes/dataset/experiment_container.py

This reveals that this function is very similar to the `load_or_create_experiment` function. Perhaps we should unify them?

move _create_exp_if_needed to exp module where it belongs

---

qcodes/dataset/data_set.py

This makes the info significantly more useful

normalize path for export in dataset

---

qcodes/dataset/sqlite/database.py

This method takes in a path to a db and creates a connection but does never close it

close connection in get_db

---

qcodes/dataset/measurements.py
qcodes/tests/dataset/test_dataset_in_memory.py

Since that would mean just throwing away the data without storing it anywhere

Disallow the use of a DataSetInMemory without cache

---

.github/dependabot.yml
.github/workflows/conda-forge-install-and-test.yaml
.github/workflows/docs.yaml
.github/workflows/pytest-min-versions.yaml
.github/workflows/pytest-non-local.yaml
bors.toml

This sets up [Bors](https://bors.tech/) as a merge bot for merging qcodes pull requests. The idea is that rather than merging into master directly which effectively limits the throughput to one pr at a time (Since we require the prs to build against an up to date master) they are merged into a staging branch by doing bors r+ the staging branch can contain one or more prs. Once the staging branch passes ci it will be merged into master. Prs that are bors r+d will staging is running are automatically added to a queue and will be run as staging afterwards 
TODO

Use Bors to merge prs

---

bors.toml

Precommit does not trigger on branches so we should ensure that it runs and completes on prs before they are merged to staging

require pre commit before merging to staging

---

.github/workflows/docs.yaml
.github/workflows/pytest.yaml
qcodes/logger/instrument_logger.py
qcodes/tests/test_slack.py
setup.cfg

run test + docs build with python 3.10

---

docs/changes/0.30.0.rst
docs/changes/index.rst
docs/changes/newsfragments/3094.new
docs/changes/newsfragments/3397.underthehood
docs/changes/newsfragments/3431.new
docs/changes/newsfragments/3438.improved_driver
docs/changes/newsfragments/3450.improved_driver
docs/changes/newsfragments/3451.new
docs/changes/newsfragments/3452.improved_driver
docs/changes/newsfragments/3475.improved
docs/changes/newsfragments/3534.improved
docs/changes/newsfragments/3555.improved_driver
docs/changes/newsfragments/3576.improved
docs/changes/newsfragments/3586.improved

This is generated using towncrier for the first time. 
Apart from the title this should match https://qcodes.github.io/Qcodes/changes/unreleased.html

add changelog for 0.30

---

qcodes/dataset/data_set.py
qcodes/dataset/data_set_in_memory.py
qcodes/dataset/data_set_protocol.py

Research shows that these are fairly commonly uses so to make it easier to use the protocol I suggest adding them here. The implementation is also fairly straight forward

Add two more methods to dataset protocol

---

docs/changes/newsfragments/3644.Underthehood
qcodes/dataset/sqlite/queries.py
qcodes/tests/dataset/test_dataset_basic.py

Relax time stamp type assertions to allow ints in the database

---

.github/workflows/docs.yaml

see https://github.com/actions/upload-artifact/issues/270

Pin actions/upload-artifacts to v2.2.4

---

qcodes/instrument/base.py
qcodes/instrument_drivers/AlazarTech/ATS.py
qcodes/instrument_drivers/american_magnetics/AMI430.py

This should make it clear that the output type is the same as the input type
Also a small cleanup for the same module

Better typing of find_or_create_instrument

---

qcodes/dataset/exporters/export_to_xarray.py
qcodes/tests/dataset/test_dataset_export.py

fix export to xarray on empty ds

---

qcodes/instrument_drivers/Lakeshore/Model_325.py
qcodes/instrument_drivers/ithaco/Ithaco_1211.py
qcodes/instrument_drivers/stanford_research/SR560.py
qcodes/instrument_drivers/tektronix/keithley_7510.py
qcodes/logger/instrument_logger.py
qcodes/tests/drivers/test_lakeshore.py
qcodes/tests/helpers/test_issequenceof.py
qcodes/utils/dataset/doNd.py
qcodes/utils/delaykeyboardinterrupt.py
test_requirements.txt

* mark mypy 0.920 as supported
* Fix or work around new issues

Mypy 0.920 support

---

.github/workflows/cancel_old_jobs.yaml

add basic github actions job that cancels old jobs

---

.github/workflows/cancel_old_jobs.yaml
.github/workflows/pytest-min-versions.yaml

Cancle more jobs on new push

---

qcodes/tests/drivers/test_keithley_7510.py

For example here https://github.com/QCoDeS/Qcodes/runs/4591761964?check_suite_focus=true

disable timeout on test that sometimes fails in ci

---

.github/workflows/pytest.yaml
pyproject.toml
setup.cfg
test_requirements.txt

Move coverage config to pyproject.toml

---

pyproject.toml
qcodes/utils/metadata.py

Actually there was only a single type missing here

Add complete types to utils metadata

---

qcodes/data/data_array.py

importing xarray is slow so avoid doing this at qcodes import time
Locally this saves ~ 2 sec on a fresh import of qcodes

lazily import xarray in legacy dataset

---

qcodes/dataset/data_set.py

This saves around ~0.5 s of import time on importing qcodes

Do not import pandas at dasaset import time

---

qcodes/instrument/base.py
qcodes/tests/test_abstract_instrument.py
qcodes/tests/test_instrument.py

Together with https://github.com/QCoDeS/Qcodes/pull/3696 this implements the improvements suggested in https://github.com/QCoDeS/Qcodes/issues/1882

Use Weak dicts and sets rather than Dict and List of weakref to track instrument instances 

---

docs/changes/newsfragments/3781.breaking
docs/changes/newsfragments/3781.improved
qcodes/__init__.py

Fixes https://github.com/QCoDeS/Qcodes/issues/3778

Fix circular import in legacy api

---

docs/changes/newsfragments/3838.improved
qcodes/instrument/channel.py
qcodes/tests/test_channels.py

Fixes https://github.com/QCoDeS/Qcodes/issues/3836

ChannelList keep mapping in sync when inserting.

---

.pre-commit-config.yaml

See https://github.com/akaihola/darker/issues/264
Also fix to use the correct tag for darker

Pin black until darker supports black 22

---

.pre-commit-config.yaml

upgrade to darker 1.4.0

---

qcodes/instrument/parameter.py
qcodes/instrument_drivers/Keysight/N52xx.py

Such that its clear that calling with no arguments is get and calling with arguments is set.

Overload types for parameter calling

---

qcodes/dataset/data_set_protocol.py
qcodes/tests/dataset/test_dataset_in_memory.py
setup.cfg

https://github.com/QCoDeS/Qcodes/pull/3932 introduced a few warnings in the test suite. Fix those here @astafan8

Silence netcdf warnings

---

.github/static/environment_forge_full.yml
setup.cfg

Due to this bug https://github.com/h5netcdf/h5netcdf/issues/154

Exclude h5netcdf 0.14.0

---

docs/changes/newsfragments/3773.improved
qcodes/plots/pyqtgraph.py

Fixes a typo in legacy pyqtplot unit handling

fix typo from 3773

---

docs/execute_notebooks.cmd

This is being done (and has for a long time) with nbsphinx

remove unused execute notebooks script

---

docs/examples/15_minutes_to_QCoDeS.ipynb
docs/examples/Station.ipynb

This is part of my attempt to make modules more consistent and truly modular. 
The end goal is to ensure that end users can import every thing from separate modules (dataset, instrument ...) 
This is small step in that direction

Top level notebooks: Import from modules

---

qcodes/tests/drivers/test_ami430.py
qcodes/tests/drivers/test_ami430_visa.py

These tests fails occasionally in CI due to timeouts so lets drop these

Disable deadlines for ami tests

---

qcodes/instrument/sims/Yokogawa_GS200.yaml
qcodes/instrument_drivers/yokogawa/GS200.py
qcodes/tests/drivers/test_yokogawa_gs200.py

* Add a few basic pyvisa-sim tests mainly ensuring that we raise the correct error depending on the mode (curr/volt)
* Improvements to types (clarifying that mode can only be CURR or VOLT)

Small improvements to yokogawa gs200 driver

---

bors.toml

Should really have been a part of #4206

Update required bors jobs to match actual ci

---

qcodes/instrument/base.py
qcodes/instrument_drivers/tektronix/TPS2012.py

This fixes the warnings in https://github.com/QCoDeS/Qcodes/issues/4203 and also makes the logging around getting idn failure a bit better

Small fixes related to tps2012 

---

docs/conf.py

* Set language as required by sphinx 5
* Update intersphinx link for matplotlib to not trigger warning

Sphinx small fixes

---

docs_requirements.txt
qcodes/data/format.py
qcodes/data/gnuplot_format.py
qcodes/data/hdf5_format.py
qcodes/data/hdf5_format_hickle.py
qcodes/instrument_drivers/AlazarTech/dll_wrapper.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_module.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1511B.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1517A.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1520A.py
qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1530A.py
qcodes/instrument_drivers/Minicircuits/Base_SPDT.py

This tries to fix issue with multiple references in sphinx 4.4.0 and newer by importing fully qualified names. 
In https://github.com/QCoDeS/Qcodes/pull/4224 we use autodocsumm which officially does not support Sphinx 5 so we limit this to Sphinx 4.5 for now

Build docs with Sphinx 4.5.0

---

test_requirements.txt

Align sphinx for testing with sphinx for docs

---

docs/api/index.rst
docs/api/interactive_widget.rst
qcodes/interactive_widget.py

And fix formatting of the same

Docs: add api docs for interactive_widget

---

docs/changes/newsfragments/4301.improved_driver
qcodes/instrument_drivers/Keysight/N52xx.py

Add RF output parameter to VNA driver

Add RF output parameter for Keysight N52xx driver

---

qcodes/tests/common.py

* Handle that the error passed in may not have a chain to avoid an assert
* Import Exception type from pytest

Adapt error_caused_by to not depend on internals of pytest

---

docs/api/extensions/slack.rst
docs/api/index.rst
docs/api/utils/index.rst
docs/api/utils/magic.rst
qcodes/extensions/__init__.py

Since they only work with the loop dataset.

API: Document magic and slack as legacy

---

docs/api/utils/index.rst
docs/api/utils/threading.rst

Should have been included in #4348

remove old threading docs

---

qcodes/dataset/do_nd.py

Moved independent refactoring out of https://github.com/QCoDeS/Qcodes/pull/4325

Refactor internals of do_nd

---

.github/actions/setup-ubuntu-latest-xvfb/action.yml

As suggested in
https://github.com/actions/virtual-environments/issues/5894

Try fixing xvfb

---

docs/changes/newsfragments/4397.breaking
qcodes/instrument/visa.py
qcodes/tests/test_visa.py

* Refactor code to set attributes in ``__init__`` for clarity.
* Import pyvisa as pyvisa to ensure that intersphinx links work
correctly

Clean up Visa address handling

---

requirements.txt

Depdendabot does not automatically upgrade these due to the env markers

Test using latest importlib

---

.github/workflows/pytest.yaml

This should make it more likely that mypy will spot files missing from the install

Run mypy against installed qcodes

---

pyproject.toml
qcodes/instrument_drivers/QDevil/QDevil_QDAC.py
qcodes/instrument_drivers/signal_hound/SignalHound_USB_SA124B.py
qcodes/tests/parameter/test_snapshot.py

This explicitly configures all of mypys strict modes and enables some of them.
Along the way this fixes what looks like 2 bugs in drivers

Configure strict options for mypy and enable some of them

---

qcodes/parameters/array_parameter.py
qcodes/parameters/combined_parameter.py
qcodes/parameters/command.py
qcodes/parameters/delegate_parameter.py
qcodes/parameters/function.py
qcodes/parameters/group_parameter.py
qcodes/parameters/grouped_parameter.py
qcodes/parameters/multi_parameter.py
qcodes/parameters/named_repr.py
qcodes/parameters/parameter.py
qcodes/parameters/parameter_base.py
qcodes/parameters/parameter_with_setpoints.py
qcodes/parameters/permissive_range.py
qcodes/parameters/scaled_paramter.py
qcodes/parameters/sequence_helpers.py
qcodes/parameters/specialized_parameters.py
qcodes/parameters/sweep_values.py
qcodes/parameters/val_mapping.py

* Rerun pyupgrade
* Replace imports from typing with collections.abc when possible
* Remove unused imports

Add future __annotation__ to parameters

---

docs/changes/newsfragments/4969.improved
qcodes/dataset/sqlite/db_upgrades/__init__.py
qcodes/dataset/sqlite/db_upgrades/upgrade_2_to_3.py
qcodes/dataset/sqlite/db_upgrades/upgrade_3_to_4.py
qcodes/dataset/sqlite/db_upgrades/upgrade_5_to_6.py
qcodes/dataset/sqlite/db_upgrades/version.py

This should help mitigate the issue in #4566 by not showing the progress bar when creating a new db.
Fixes #4566

Don't show progressbars when upgrading an empty db

---

docs/Makefile
docs/drivers_api/QDev.rst
docs/make.bat
qcodes/instrument_drivers/QDev/QDac_channels.py
qcodes/instrument_drivers/QDev/__init__.py

 Update Qdev drivers to conform with standard 

---

docs/Makefile
docs/drivers_api/QuantumDesign.rst
docs/make.bat
pyproject.toml
qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/DynaCool.py
qcodes/instrument_drivers/QuantumDesign/DynaCoolPPMS/private/server.py
qcodes/instrument_drivers/QuantumDesign/__init__.py

Update Dynacool drivers to conform to docs standard

---

docs/changes/newsfragments/4610.fixed
qcodes/instrument_drivers/american_magnetics/AMI430.py
qcodes/instrument_drivers/american_magnetics/AMI430_visa.py

Add get_idn to AMI 430 3D virtual instrument driver that does not raise warning when added to station

---

pyproject.toml

Removes one more package from the list of not typed packages.
Inspired by the list in https://github.com/python/mypy/pull/13698

typecheck tqdm against stubs

---

.github/workflows/pytest.yaml
bors.toml

This will also need to reconfigure the jobs required to pass ci

revert pinning of python 3.10 now that mypy has fixed the bug

---

qcodes/instrument_drivers/Keithley/_Keithley_2600.py
qcodes/instrument_drivers/Keithley/__init__.py
qcodes/tests/drivers/test_keithley_26xx.py

This was missed as part of the original refactor but should be part of the api

Add Keithley2600MeasurementStatus to public api

---

qcodes/tests/test_channels.py

These 2 tests have been failing for me locally so increasing the deadline to avoid that

increase deadline of 2 tests

---

docs/changes/newsfragments/4770.improved
qcodes/dataset/plotting.py

This PR text-wraps long plot titles.

Add text-wrapping for extra-long plot titles

---

.github/workflows/docs.yaml
qcodes/dataset/descriptions/dependencies.py

Fixes https://github.com/QCoDeS/Qcodes/issues/4830

Fix type in ci env variable (sphinx warnings as errors)

---

pyproject.toml
requirements.txt

For some reason dependabot is not willing to do this update
```
updater | ERROR <job_565123915> Error processing pyvisa (RuntimeError)
updater | ERROR <job_565123915> Unexpected update strategy: bump_versions_if_necessary
updater | ERROR <job_565123915> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:91:in `updated_pyproject_requirement'
updater | ERROR <job_565123915> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:36:in `block in updated_requirements'
updater | ERROR <job_565123915> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:33:in `map'
updater | ERROR <job_565123915> /home/dependabot/python/lib/dependabot/python/update_checker/requirements_updater.rb:33:in …
```

Allow Pyvisa 1.13

---

.github/actions/setup-ubuntu-latest-xvfb/action.yml
.github/workflows/docs.yaml
.github/workflows/pytest.yaml

Seems like this currently causes not found packages

update apt before installing

---

docs/api/index.rst

Changes 
to the more manageable

Reduce toc dept of api docs

---

requirements.txt

revert ipykernel to 6.20.2

---

.github/workflows/docs.yaml
.github/workflows/pytest-min-versions.yaml
.github/workflows/pytest-non-local.yaml
.github/workflows/pytest.yaml

Needed to enable github merge groups which can hopefully replace bors

Trigger gh actions on merge_group

---

.github/workflows/docs.yaml
.github/workflows/pytest-min-versions.yaml
.github/workflows/pytest-non-local.yaml
.github/workflows/pytest.yaml

Work around for https://github.com/community/community/discussions/46757#discussioncomment-4908050

work around for merge queues not triggering

---

.github/workflows/docs.yaml
.github/workflows/pytest-min-versions.yaml
.github/workflows/pytest-non-local.yaml
.github/workflows/pytest.yaml

https://github.com/community/community/discussions/46757#discussioncomment-4908050
but will wait til confirmed before merging

Merge queues Revert no longer needed work around

---

qcodes/tests/dataset/test_subscribing.py

fix Usefixture on fixture has no effect

---

qcodes/instrument_drivers/tektronix/AWG70000A.py
qcodes/tests/common.py
qcodes/tests/dataset/dond/test_doNd.py
qcodes/tests/dataset/measurement/test_load_legacy_data.py
qcodes/tests/dataset/measurement/test_measurement_context_manager.py
qcodes/tests/dataset/test_snapshot.py
qcodes/tests/drivers/test_MercuryiPS.py
qcodes/tests/drivers/test_ami430.py
qcodes/tests/drivers/test_ami430_visa.py
qcodes/tests/drivers/test_lakeshore.py
qcodes/tests/drivers/test_tektronix_AWG70000A.py
qcodes/tests/test_monitor.py
qcodes/tests/test_plot_utils.py
qcodes/tests/utils/test_attributes_set_to_context_manager.py
qcodes/tests/utils/test_class_strings.py
qcodes/tests/utils/test_isfunction.py

This reduces the number of pyright errors in tests from > 300 to just under 200

Fix some of the pyright issues in tests

---

qcodes/dataset/sqlite/db_upgrades/__init__.py
qcodes/parameters/parameter_with_setpoints.py
qcodes/tests/dataset/dond/test_do0d.py
qcodes/tests/dataset/dond/test_do1d.py
qcodes/tests/dataset/dond/test_do2d.py
qcodes/tests/dataset/helper_functions.py
qcodes/tests/dataset/test_database_creation_and_upgrading.py
qcodes/tests/dataset/test_database_extract_runs.py
qcodes/tests/dataset/test_sqlite_connection.py
qcodes/tests/driver_test_case.py
qcodes/tests/drivers/keysight_b1500/b1500_driver_tests/test_b1517a_smu.py
qcodes/tests/drivers/test_lakeshore_336.py
qcodes/tests/drivers/test_lakeshore_336_legacy.py
qcodes/tests/helpers/test_delegate_attribues.py
qcodes/tests/helpers/test_strip_attrs.py
qcodes/tests/parameter/test_issequenceof.py
qcodes/tests/parameter/test_parameter_ramp.py
qcodes/tests/parameter/test_parameter_with_setpoints.py
qcodes/tests/parameter/test_scaled_parameter.py
qcodes/tests/test_channels.py
qcodes/tests/test_command.py
qcodes/tests/test_config.py
qcodes/tests/test_instrument.py
qcodes/tests/test_logger.py
qcodes/tests/test_metadata.py
qcodes/tests/test_sweep_values.py
qcodes/tests/test_visa.py

Reduce pyright issues in tests

---

pyproject.toml
qcodes/dataset/data_set_protocol.py
qcodes/tests/dataset/dond/test_do0d.py
qcodes/tests/dataset/dond/test_do1d.py
qcodes/tests/dataset/dond/test_do2d.py
qcodes/tests/dataset/dond/test_doNd.py
qcodes/tests/dataset/test__get_data_from_ds.py
qcodes/tests/dataset/test_converters.py
qcodes/tests/dataset/test_database_extract_runs.py
qcodes/tests/dataset/test_datasaver.py
qcodes/tests/dataset/test_dataset_basic.py
qcodes/tests/dataset/test_dataset_export.py
qcodes/tests/dataset/test_dataset_loading.py
qcodes/tests/dataset/test_dependencies.py
qcodes/tests/dataset/test_detect_shape.py
qcodes/tests/dataset/test_plotting.py
qcodes/tests/dataset/test_snapshot.py
qcodes/tests/dataset/test_string_data.py
qcodes/tests/drivers/test_lakeshore.py
qcodes/tests/test_channels.py
qcodes/tests/test_command.py
qcodes/tests/test_monitor.py
qcodes/tests/test_station.py

And fix remaining issues in the tests.
Only important change should be that 
the_same_dataset as has been promoted to be part of the dataset protocol

Run pyright on tests

---

CONTRIBUTING.rst

install test requirements from requirements.txt, since test_requirements.txt got removed.

CONTRIBUTING.rst: update test installation instructions

---

pyproject.toml

https://github.com/QCoDeS/Qcodes/security/dependabot/5

Pin min ipython to 8.10 due to security issue

---

docs/community/related_projects.rst

Adding Quantify to listing of related projects (finally, I might add ;-))
Also removed a stray colon in the QTT entry.

Add Quantify to Related Projects

---

qcodes/tests/dataset/test_dataset_export.py

Fix CI: remove no longer needed type ignores

---

.github/workflows/pytest.yaml

bump pyright to 1.1.303

---

qcodes/tests/dataset/test_string_data.py

Fixes a type check in the tests by ignoring the failure

ignore typing error in test

---

.github/workflows/upload_to_pypi.yaml

using the trusted flow at https://docs.pypi.org/trusted-publishers/

Switch publish to official pypi action

---

docs/examples/writing_drivers/Creating-Instrument-Drivers.ipynb

example notebook convert docs cell to markdown

---

pyproject.toml
qcodes/instrument_drivers/tektronix/AWG5014.py

remove support for never released package lomentum

---

.github/workflows/pytest.yaml
qcodes/instrument_drivers/american_magnetics/AMI430.py
qcodes/instrument_drivers/american_magnetics/AMI430_visa.py
qcodes/tests/dataset/test_guid_helpers.py
qcodes/tests/drivers/test_ami430.py
qcodes/tests/drivers/test_ami430_visa.py
qcodes/tests/test_threading.py

Needs a few typing improvements to kwargs unpacking and defaultdict

Type check with pyright 1.1.315

---

docs/examples/logging/logging_example.ipynb
qcodes/instrument/ip_to_visa.py
qcodes/tests/test_instrument.py
qcodes/tests/test_logger.py

* Port logging tests to use visa ami driver rather than adaptor
* Remove unused import from example
* Bring ip to visa adaptor in sync with base class (private field has been renamed)
* Add missing close to instrument "name" in test

Small test cleanups

---

qcodes/instrument/visa.py

See https://github.com/QCoDeS/Qcodes/pull/5360 for a working workaround.

remove non working pyvisa-sim workaround

---

docs/changes/0.39.1.rst
docs/changes/0.40.0.rst
docs/changes/index.rst
docs/changes/newsfragments/5278.improved
docs/changes/newsfragments/5289.new
docs/changes/newsfragments/5294.new
docs/changes/newsfragments/5297.improved
docs/changes/newsfragments/5316.improved_driver
docs/changes/newsfragments/5329.improved
docs/changes/newsfragments/5341.improved

Also merge 0.39.x into master to get the changes for 0.39.1 rendered correctly

Add changelog for 0.40.0

---

docs/community/related_projects.rst

Quick MR to update Quantify documentation links as we've moved to new domain

Update quantify doc links

---

.github/workflows/darker.yaml
.github/workflows/docs.yaml

Missed these due to not grepping into hidden folders

fix remaining master links

---

.github/workflows/pytest.yaml

upgrade pyright to 1.1.332

---

.github/dependabot.yml
requirements.txt
src/qcodes/dataset/plotting.py

See https://github.com/zhinst/zhinst-qcodes/issues/63
Also create a dependabot group to keep zhinst packages up to date in one pr

Pin zhinst-core in ci to fix typing issue

---

src/qcodes/tests/mockers/test_simulated_ats_api.py

Assert that debug logging works as expected in alazar mock tests

---

.github/workflows/pytest.yaml
src/qcodes/dataset/legacy_import.py
src/qcodes/dataset/plotting.py

And remove two no longer required ignores

upgrade pyright to 1.1.334

---

pyproject.toml

Some nice lints here that will prevent various issues

add numpy ruff lints

---

src/qcodes/instrument/instrument_base.py
tests/test_instrument.py

Fix print_readable_snapshot for empty InstrumentModule

---

README.rst
docs/start/index.rst

Docs and readme are updated to include the minimum working version of python as 3.9.

Updated docs and readme to include minimum python version 3.9

---

src/qcodes/instrument_drivers/Keysight/Infiniium.py

Fixed typo for a parameter label

---

README.rst

The ms recommeded scan was added in https://github.com/microsoft/Qcodes/pull/5671 this adds a badge of this to the readme

add Openssf scorecard badge

---

.github/workflows/codeql-analysis.yml

This will fix a reported security issue here https://github.com/microsoft/Qcodes/security/code-scanning/44

run codeql on prs

---

pyproject.toml
requirements.txt

Take 2 at trying to fix https://github.com/microsoft/Qcodes/security/code-scanning/52

upgrade min versions to fix flagged vulnerabilities

---

.pre-commit-config.yaml
pyproject.toml

Upgrade ruff to version 0.2.0 which include some config format changes

Precommit hooks update

---

docs/changes/0.44.1.rst
docs/changes/index.rst
requirements.txt
src/qcodes/dataset/data_set_in_memory.py
tests/dataset/test_dataset_export.py

Merge Release/v0.44.x into main

---

requirements.txt

limit min allowed version of cryptography

fix https://github.com/microsoft/Qcodes/security/code-scanning/52

---

.github/workflows/docs.yaml

Towards resolving https://github.com/microsoft/Qcodes/security/code-scanning/61

move deploy docs to its own job

---

requirements.txt

Rerunning 
```
uv pip compile pyproject.toml --extra test --extra docs -o requirements.txt
```

add pyarrow to requirements file

---

README.rst

We are now using ruff and not codacy so lets make the badge reflect this

replace codacy badge with ruff badge

---

docs/examples/driver_examples/Qcodes example with Keysight Network Analyzer.ipynb

Fixed typo in docs

---

.pre-commit-config.yaml
src/qcodes/dataset/export_config.py
src/qcodes/instrument_drivers/HP/HP_83650A.py
src/qcodes/instrument_drivers/tektronix/AWG5014.py
src/qcodes/parameters/array_parameter.py
src/qcodes/parameters/multi_parameter.py
src/qcodes/tests/common.py

And implement fixes for improved ruff rule

Upgrade precommit hooks

---

src/qcodes/instrument/instrument.py
src/qcodes/monitor/monitor.py
src/qcodes/utils/delaykeyboardinterrupt.py

that mypy requires when run as a deamon via dmypy

Add missing type annotations

---

.github/workflows/pytest.yaml
pyproject.toml

Except for the min versions job where we ignore them.

Make warnings hard errors in the test suite

---

docs/changes/newsfragments/6113.improved_driver
docs/drivers_api/AlazarTech.rst
docs/drivers_api/American_magnetics.rst
docs/drivers_api/Basel.rst
docs/drivers_api/CryoMagnetics.rst
docs/drivers_api/Galil.rst
src/qcodes/instrument_drivers/AlazarTech/ATS.py
src/qcodes/instrument_drivers/AlazarTech/ATS9360.py
src/qcodes/instrument_drivers/AlazarTech/ATS9373.py
src/qcodes/instrument_drivers/AlazarTech/ATS9440.py
src/qcodes/instrument_drivers/AlazarTech/ATS9870.py
src/qcodes/instrument_drivers/AlazarTech/ATS_acquisition_controllers.py
src/qcodes/instrument_drivers/AlazarTech/__init__.py
src/qcodes/instrument_drivers/AlazarTech/utils.py
src/qcodes/instrument_drivers/Galil/dmc_41x3.py
src/qcodes/instrument_drivers/american_magnetics/AMI430.py
src/qcodes/instrument_drivers/american_magnetics/AMI430_visa.py
src/qcodes/instrument_drivers/basel/BaselSP983.py
src/qcodes/instrument_drivers/basel/BaselSP983a.py
src/qcodes/instrument_drivers/cryomagnetics/_cryomagnetics4g.py
tests/drivers/AlazarTech/test_alazar_api.py

* Convert all drivers Alazar -> Galil to new add_parameter format. 
* Don't document inherited attributes
* Make Alazar base classes public
* Fix some small typing issues along the way
TODO

Refactor drivers Alazar -> Galil

---

src/qcodes/instrument_drivers/Harvard/Decadac.py

Silence output from mypy created by adding types for parameters

Silence mypy note

---

docs/changes/newsfragments/6164.improved_driver
docs/drivers_api/Tektronix.rst
src/qcodes/instrument_drivers/tektronix/AWG5014.py
src/qcodes/instrument_drivers/tektronix/AWG5208.py
src/qcodes/instrument_drivers/tektronix/AWG70000A.py
src/qcodes/instrument_drivers/tektronix/AWG70002A.py
src/qcodes/instrument_drivers/tektronix/DPO7200xx.py
src/qcodes/instrument_drivers/tektronix/TPS2012.py
src/qcodes/instrument_drivers/tektronix/Tektronix_70001A.py
src/qcodes/instrument_drivers/tektronix/Tektronix_70001B.py
src/qcodes/instrument_drivers/tektronix/Tektronix_70002B.py
src/qcodes/instrument_drivers/tektronix/__init__.py
tests/drivers/test_tektronix_AWG70000A.py

Refactor Tektronix drivers

---

docs/changes/0.46.0.rst

* Fix a few typos and ensure that release tag is a parent of main

Merge 0.46.x branch to main

---

docs/changes/0.47.0.rst
docs/changes/index.rst
docs/changes/newsfragments/6076.improved_driver
docs/changes/newsfragments/6207.improved_driver
docs/changes/newsfragments/6248.improved_driver
docs/changes/newsfragments/6306.improved_driver
docs/changes/newsfragments/6322.improved_driver

towncrier build for version 0.47.0 and additional updates to change logs for upcoming release.

Changelogs for v0.47.0 release

---

pyproject.toml
src/qcodes/instrument_drivers/Keysight/Infiniium.py

Keysight Infiniium: feat: add screenshot for keysight infiniium

---

docs/conf.py

This link should have been updated when we moved the repo to the microsoft org

Fix issue link in docs

---

pyproject.toml
src/qcodes/dataset/data_set_cache.py
src/qcodes/utils/spyder_utils.py
tests/dataset/measurement/test_measurement_context_manager.py
tests/test_plot_utils.py

Remove unused ruff pragmas and check for these

---

docs/examples/DataSet/Dataset_Performance.ipynb
docs/examples/logging/logging_example.ipynb
pyproject.toml

This now works fine for notebooks except 2 cells that had trivial issues

Remove disable of E402 lint for notebooks

---

docs/changes/0.50.1.rst
docs/changes/index.rst
docs/changes/newsfragments/6671.improved
src/qcodes/parameters/parameter.py
src/qcodes/parameters/parameter_base.py
tests/parameter/test_delegate_parameter.py

Backport #6671

---

src/qcodes/instrument/instrument_base.py
src/qcodes/parameters/delegate_parameter.py
src/qcodes/parameters/parameter.py
src/qcodes/parameters/parameter_base.py
tests/parameter/test_parameter_override.py

Small improvements to Parameter and Instrument logging

---

src/qcodes/dataset/experiment_container.py

Fix `Experiment.last_data_set` to pass `self.conn` to `load_by_id`

---

requirements.txt

A few dependencies have changed so it makes sense to regenerate this.

Regenerate requirements.txt

---

.github/package.json

workaround for https://github.com/dependabot/dependabot-core/issues/11373

Work around dependabot error

---

docs/examples/driver_examples/Qcodes example with keithley 2450.ipynb

Update Qcodes example with keithley 2450.ipynb

---

src/qcodes/monitor/monitor.py

Instrument handling of request in Monitor

---

docs/changes/0.53.0.rst
docs/changes/index.rst
docs/changes/newsfragments/6723.improved_driver
docs/changes/newsfragments/7017.new
docs/changes/newsfragments/7038.breaking
docs/changes/newsfragments/7065.improved
docs/changes/newsfragments/7186.improved
docs/changes/newsfragments/7187.breaking
docs/changes/newsfragments/7199.improved

Add changelog for 0.53.0

---

.pre-commit-config.yaml
pyproject.toml
src/qcodes/_version.py
src/qcodes/configuration/config.py
src/qcodes/dataset/data_set_in_memory.py
src/qcodes/dataset/descriptions/dependencies.py
src/qcodes/dataset/descriptions/rundescriber.py
src/qcodes/dataset/descriptions/versioning/serialization.py
src/qcodes/dataset/descriptions/versioning/v0.py
src/qcodes/dataset/json_exporter.py
src/qcodes/dataset/plotting.py
src/qcodes/dataset/sqlite/db_upgrades/__init__.py
src/qcodes/dataset/threading.py
src/qcodes/instrument_drivers/Keithley/_Keithley_2600.py
src/qcodes/instrument_drivers/Keysight/Infiniium.py
src/qcodes/instrument_drivers/Keysight/keysightb1500/KeysightB1500_base.py
src/qcodes/instrument_drivers/Minicircuits/_minicircuits_usb_spdt.py
src/qcodes/interactive_widget.py
src/qcodes/monitor/monitor.py
src/qcodes/plotting/matplotlib_helpers.py
src/qcodes/station.py
src/qcodes/utils/helpers.py
src/qcodes/utils/json_utils.py
tests/dataset/measurement/test_measurement_context_manager.py
tests/dataset/test_database_creation_and_upgrading.py
tests/drivers/keysight_b1500/b1500_driver_tests/test_b1517a_smu.py
tests/drivers/keysight_b1500/test_MessageBuilder.py
tests/drivers/test_keysight_b220x.py
tests/test_visa.py

This adds some more lints
Most importantly this links non module level imports.
* Extend list of modules banned at module level. This makes the modules automatically ok to import within a class / function
* Add pragmas where it makes sense
*

Upgrade to ruff 0.12.0

---

docs/changes/newsfragments/7398.new_driver
docs/examples/driver_examples/Qcodes example with Cryomagnetics TM-620.ipynb
src/qcodes/instrument/sims/cryo_tm620.yaml
src/qcodes/instrument_drivers/cryomagnetics/_TM620.py
src/qcodes/instrument_drivers/cryomagnetics/__init__.py
tests/drivers/test_cryomagnetics_TM620.py

- Added driver for Cryomagnetics TM-620
- Added simulator YAML configuration
- Added tests for TM-620 driver
- Added notebook containing usage examples for the TM-620

Add Driver for Cryomagnetics TM-620 Cryogenic Temperature Monitor

---

pyproject.toml

Work around for https://github.com/orgs/community/discussions/163397#discussioncomment-13888710

Hardcode default version due to github actions bug

---

src/qcodes/instrument_drivers/Keysight/KeysightAgilent_33XXX.py
src/qcodes/instrument_drivers/Keysight/__init__.py

Follow up to #7521  Missed a few type hints and docstrins + Public export that improves documentation

Export keysight33xxx

---

tests/dataset/test_dataset_export.py

It was previously not noticed that the oder would change in the case where a coordinate is decreasing. The new order is perhaps more correct since it matches what was stored in the database and the order that data was measured in but it is a change.

Add test showing change in export order for xarray export
